// SessionRegistry is the authoritative registry of live SMPP ESME binds (plan §7, M3).
//
// A single account may hold several concurrent binds spread across pods; the registry keeps the
// account -> {pod_id, bind_id}[] table, enforces max_sessions at bind time (invariant d), and routes
// an inbound deliver_sm to the pod that owns the target bind. The registry never speaks SMPP: PDUs
// cross it as opaque bytes already encoded by internal/smpp.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: session.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DisconnectScope names what a Disconnect targets. A customer-wide scope suspends every account of a
// customer without the caller enumerating them or issuing one call per account.
type DisconnectScope int32

const (
	DisconnectScope_DISCONNECT_SCOPE_UNSPECIFIED DisconnectScope = 0
	DisconnectScope_DISCONNECT_SCOPE_ACCOUNT     DisconnectScope = 1
	DisconnectScope_DISCONNECT_SCOPE_CUSTOMER    DisconnectScope = 2
	// SESSION targets one bind by its bind_id. Disconnect answers NotFound when no such bind is live.
	DisconnectScope_DISCONNECT_SCOPE_SESSION DisconnectScope = 3
)

// Enum value maps for DisconnectScope.
var (
	DisconnectScope_name = map[int32]string{
		0: "DISCONNECT_SCOPE_UNSPECIFIED",
		1: "DISCONNECT_SCOPE_ACCOUNT",
		2: "DISCONNECT_SCOPE_CUSTOMER",
		3: "DISCONNECT_SCOPE_SESSION",
	}
	DisconnectScope_value = map[string]int32{
		"DISCONNECT_SCOPE_UNSPECIFIED": 0,
		"DISCONNECT_SCOPE_ACCOUNT":     1,
		"DISCONNECT_SCOPE_CUSTOMER":    2,
		"DISCONNECT_SCOPE_SESSION":     3,
	}
)

func (x DisconnectScope) Enum() *DisconnectScope {
	p := new(DisconnectScope)
	*p = x
	return p
}

func (x DisconnectScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisconnectScope) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[0].Descriptor()
}

func (DisconnectScope) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[0]
}

func (x DisconnectScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisconnectScope.Descriptor instead.
func (DisconnectScope) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

// BindType mirrors control_plane.smpp_accounts.allowed_bind_types (a single kind per account).
type BindType int32

const (
	BindType_BIND_TYPE_UNSPECIFIED BindType = 0
	BindType_BIND_TYPE_TX          BindType = 1
	BindType_BIND_TYPE_RX          BindType = 2
	BindType_BIND_TYPE_TRX         BindType = 3
)

// Enum value maps for BindType.
var (
	BindType_name = map[int32]string{
		0: "BIND_TYPE_UNSPECIFIED",
		1: "BIND_TYPE_TX",
		2: "BIND_TYPE_RX",
		3: "BIND_TYPE_TRX",
	}
	BindType_value = map[string]int32{
		"BIND_TYPE_UNSPECIFIED": 0,
		"BIND_TYPE_TX":          1,
		"BIND_TYPE_RX":          2,
		"BIND_TYPE_TRX":         3,
	}
)

func (x BindType) Enum() *BindType {
	p := new(BindType)
	*p = x
	return p
}

func (x BindType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BindType) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[1].Descriptor()
}

func (BindType) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[1]
}

func (x BindType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BindType.Descriptor instead.
func (BindType) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

// DisconnectRequest names the account or customer whose sessions must be closed. id is the
// corresponding UUID as a string; reason is a short machine label (e.g. "credential_revoked")
// logged on the close, never a secret.
type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         DisconnectScope        `protobuf:"varint,1,opt,name=scope,proto3,enum=session.DisconnectScope" json:"scope,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *DisconnectRequest) GetScope() DisconnectScope {
	if x != nil {
		return x.Scope
	}
	return DisconnectScope_DISCONNECT_SCOPE_UNSPECIFIED
}

func (x *DisconnectRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DisconnectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DisconnectResponse reports whether the order was published to the fan-out. Because pods close
// their sessions asynchronously, it does not count the sessions actually closed.
type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Published     bool                   `protobuf:"varint,1,opt,name=published,proto3" json:"published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *DisconnectResponse) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

// Session identifies one live bind. account_id/system_id come from the control plane (account_id is a
// UUID carried as a string); pod_id/bind_id are operational Redis-registry identifiers.
type Session struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AccountId string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SystemId  string                 `protobuf:"bytes,2,opt,name=system_id,json=systemId,proto3" json:"system_id,omitempty"`
	PodId     string                 `protobuf:"bytes,3,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	BindId    string                 `protobuf:"bytes,4,opt,name=bind_id,json=bindId,proto3" json:"bind_id,omitempty"`
	BindType  BindType               `protobuf:"varint,5,opt,name=bind_type,json=bindType,proto3,enum=session.BindType" json:"bind_type,omitempty"`
	// pod_addr is the owning pod's dialable gRPC address (host:port), published by the pod itself at
	// bind time and returned by Lookup so the return path dials it directly (step-302). It is an
	// address, not an identity: pod_id stays the stable name the pod is traced by. Empty on a Lookup
	// means the pod has not published one — the caller skips that bind and falls back to the webhook,
	// which is the only state a rollout can briefly produce.
	PodAddr string `protobuf:"bytes,6,opt,name=pod_addr,json=podAddr,proto3" json:"pod_addr,omitempty"`
	// remote_addr, window_size and connected_at describe the bind to an operator (step-360). The pod sends
	// the first two at bind time; the registry stamps connected_at on the first bind, never on a refresh.
	// Lookup leaves them unset.
	RemoteAddr        string `protobuf:"bytes,7,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	WindowSize        int32  `protobuf:"varint,8,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
	ConnectedAtUnixMs int64  `protobuf:"varint,9,opt,name=connected_at_unix_ms,json=connectedAtUnixMs,proto3" json:"connected_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Session) GetSystemId() string {
	if x != nil {
		return x.SystemId
	}
	return ""
}

func (x *Session) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *Session) GetBindId() string {
	if x != nil {
		return x.BindId
	}
	return ""
}

func (x *Session) GetBindType() BindType {
	if x != nil {
		return x.BindType
	}
	return BindType_BIND_TYPE_UNSPECIFIED
}

func (x *Session) GetPodAddr() string {
	if x != nil {
		return x.PodAddr
	}
	return ""
}

func (x *Session) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *Session) GetWindowSize() int32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

func (x *Session) GetConnectedAtUnixMs() int64 {
	if x != nil {
		return x.ConnectedAtUnixMs
	}
	return 0
}

// BindRequest carries the session to register plus the account's max_sessions ceiling, so the registry
// is the sole atomic arbiter of invariant d without reading control-plane config itself.
type BindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	MaxSessions   int32                  `protobuf:"varint,2,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindRequest) Reset() {
	*x = BindRequest{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindRequest) ProtoMessage() {}

func (x *BindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindRequest.ProtoReflect.Descriptor instead.
func (*BindRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *BindRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *BindRequest) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

// BindResponse reports whether the bind was accepted and the account's session count after it.
type BindResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accepted       bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindResponse) Reset() {
	*x = BindResponse{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResponse) ProtoMessage() {}

func (x *BindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResponse.ProtoReflect.Descriptor instead.
func (*BindResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *BindResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BindResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

// UnbindRequest names the session to remove.
type UnbindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	BindId        string                 `protobuf:"bytes,2,opt,name=bind_id,json=bindId,proto3" json:"bind_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindRequest) Reset() {
	*x = UnbindRequest{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindRequest) ProtoMessage() {}

func (x *UnbindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindRequest.ProtoReflect.Descriptor instead.
func (*UnbindRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *UnbindRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UnbindRequest) GetBindId() string {
	if x != nil {
		return x.BindId
	}
	return ""
}

// UnbindResponse reports whether a session was actually removed.
type UnbindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindResponse) Reset() {
	*x = UnbindResponse{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindResponse) ProtoMessage() {}

func (x *UnbindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindResponse.ProtoReflect.Descriptor instead.
func (*UnbindResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *UnbindResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// LookupRequest names the account whose live sessions are requested.
type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

func (x *LookupRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// LookupResponse returns the account's live sessions.
type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

func (x *LookupResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// DeliverRequest targets a bind and carries a deliver_sm already encoded by internal/smpp as opaque
// bytes; the registry forwards it verbatim without parsing SMPP.
type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindId        string                 `protobuf:"bytes,1,opt,name=bind_id,json=bindId,proto3" json:"bind_id,omitempty"`
	Pdu           []byte                 `protobuf:"bytes,2,opt,name=pdu,proto3" json:"pdu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{9}
}

func (x *DeliverRequest) GetBindId() string {
	if x != nil {
		return x.BindId
	}
	return ""
}

func (x *DeliverRequest) GetPdu() []byte {
	if x != nil {
		return x.Pdu
	}
	return nil
}

// DeliverResponse reports whether the PDU reached the owning bind.
type DeliverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{10}
}

func (x *DeliverResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

// ListSessionsRequest selects one account's sessions (account_id set: all of them, cursor and limit
// ignored), or a page of every live session after cursor, a bind_id ("" = the first page).
type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListSessionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListSessionsResponse carries the sessions in bind_id order. next_cursor is "" on the last page;
// active is the account's live count as its max_sessions quota sees it (account_id requests only).
type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Active        int32                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{12}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListSessionsResponse) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\asession\"k\n" +
	"\x11DisconnectRequest\x12.\n" +
	"\x05scope\x18\x01 \x01(\x0e2\x18.session.DisconnectScopeR\x05scope\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"2\n" +
	"\x12DisconnectResponse\x12\x1c\n" +
	"\tpublished\x18\x01 \x01(\bR\tpublished\"\xb3\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tsystem_id\x18\x02 \x01(\tR\bsystemId\x12\x15\n" +
	"\x06pod_id\x18\x03 \x01(\tR\x05podId\x12\x17\n" +
	"\abind_id\x18\x04 \x01(\tR\x06bindId\x12.\n" +
	"\tbind_type\x18\x05 \x01(\x0e2\x11.session.BindTypeR\bbindType\x12\x19\n" +
	"\bpod_addr\x18\x06 \x01(\tR\apodAddr\x12\x1f\n" +
	"\vremote_addr\x18\a \x01(\tR\n" +
	"remoteAddr\x12\x1f\n" +
	"\vwindow_size\x18\b \x01(\x05R\n" +
	"windowSize\x12/\n" +
	"\x14connected_at_unix_ms\x18\t \x01(\x03R\x11connectedAtUnixMs\"\\\n" +
	"\vBindRequest\x12*\n" +
	"\asession\x18\x01 \x01(\v2\x10.session.SessionR\asession\x12!\n" +
	"\fmax_sessions\x18\x02 \x01(\x05R\vmaxSessions\"S\n" +
	"\fBindResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\"G\n" +
	"\rUnbindRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\abind_id\x18\x02 \x01(\tR\x06bindId\"*\n" +
	"\x0eUnbindResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\".\n" +
	"\rLookupRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\">\n" +
	"\x0eLookupResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.session.SessionR\bsessions\";\n" +
	"\x0eDeliverRequest\x12\x17\n" +
	"\abind_id\x18\x01 \x01(\tR\x06bindId\x12\x10\n" +
	"\x03pdu\x18\x02 \x01(\fR\x03pdu\"/\n" +
	"\x0fDeliverResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\"b\n" +
	"\x13ListSessionsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"}\n" +
	"\x14ListSessionsResponse\x12,\n" +
	"\bsessions\x18\x01 \x03(\v2\x10.session.SessionR\bsessions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x05R\x06active*\x8e\x01\n" +
	"\x0fDisconnectScope\x12 \n" +
	"\x1cDISCONNECT_SCOPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DISCONNECT_SCOPE_ACCOUNT\x10\x01\x12\x1d\n" +
	"\x19DISCONNECT_SCOPE_CUSTOMER\x10\x02\x12\x1c\n" +
	"\x18DISCONNECT_SCOPE_SESSION\x10\x03*\\\n" +
	"\bBindType\x12\x19\n" +
	"\x15BIND_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fBIND_TYPE_TX\x10\x01\x12\x10\n" +
	"\fBIND_TYPE_RX\x10\x02\x12\x11\n" +
	"\rBIND_TYPE_TRX\x10\x032\x8e\x03\n" +
	"\x0fSessionRegistry\x123\n" +
	"\x04Bind\x12\x14.session.BindRequest\x1a\x15.session.BindResponse\x129\n" +
	"\x06Unbind\x12\x16.session.UnbindRequest\x1a\x17.session.UnbindResponse\x129\n" +
	"\x06Lookup\x12\x16.session.LookupRequest\x1a\x17.session.LookupResponse\x12<\n" +
	"\aDeliver\x12\x17.session.DeliverRequest\x1a\x18.session.DeliverResponse\x12E\n" +
	"\n" +
	"Disconnect\x12\x1a.session.DisconnectRequest\x1a\x1b.session.DisconnectResponse\x12K\n" +
	"\fListSessions\x12\x1c.session.ListSessionsRequest\x1a\x1d.session.ListSessionsResponseB=Z;github.com/martialanouman/go-gateway/internal/session/pb;pbb\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_session_proto_goTypes = []any{
	(DisconnectScope)(0),         // 0: session.DisconnectScope
	(BindType)(0),                // 1: session.BindType
	(*DisconnectRequest)(nil),    // 2: session.DisconnectRequest
	(*DisconnectResponse)(nil),   // 3: session.DisconnectResponse
	(*Session)(nil),              // 4: session.Session
	(*BindRequest)(nil),          // 5: session.BindRequest
	(*BindResponse)(nil),         // 6: session.BindResponse
	(*UnbindRequest)(nil),        // 7: session.UnbindRequest
	(*UnbindResponse)(nil),       // 8: session.UnbindResponse
	(*LookupRequest)(nil),        // 9: session.LookupRequest
	(*LookupResponse)(nil),       // 10: session.LookupResponse
	(*DeliverRequest)(nil),       // 11: session.DeliverRequest
	(*DeliverResponse)(nil),      // 12: session.DeliverResponse
	(*ListSessionsRequest)(nil),  // 13: session.ListSessionsRequest
	(*ListSessionsResponse)(nil), // 14: session.ListSessionsResponse
}
var file_session_proto_depIdxs = []int32{
	0,  // 0: session.DisconnectRequest.scope:type_name -> session.DisconnectScope
	1,  // 1: session.Session.bind_type:type_name -> session.BindType
	4,  // 2: session.BindRequest.session:type_name -> session.Session
	4,  // 3: session.LookupResponse.sessions:type_name -> session.Session
	4,  // 4: session.ListSessionsResponse.sessions:type_name -> session.Session
	5,  // 5: session.SessionRegistry.Bind:input_type -> session.BindRequest
	7,  // 6: session.SessionRegistry.Unbind:input_type -> session.UnbindRequest
	9,  // 7: session.SessionRegistry.Lookup:input_type -> session.LookupRequest
	11, // 8: session.SessionRegistry.Deliver:input_type -> session.DeliverRequest
	2,  // 9: session.SessionRegistry.Disconnect:input_type -> session.DisconnectRequest
	13, // 10: session.SessionRegistry.ListSessions:input_type -> session.ListSessionsRequest
	6,  // 11: session.SessionRegistry.Bind:output_type -> session.BindResponse
	8,  // 12: session.SessionRegistry.Unbind:output_type -> session.UnbindResponse
	10, // 13: session.SessionRegistry.Lookup:output_type -> session.LookupResponse
	12, // 14: session.SessionRegistry.Deliver:output_type -> session.DeliverResponse
	3,  // 15: session.SessionRegistry.Disconnect:output_type -> session.DisconnectResponse
	14, // 16: session.SessionRegistry.ListSessions:output_type -> session.ListSessionsResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		EnumInfos:         file_session_proto_enumTypes,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
