// SessionRegistry is the authoritative registry of live SMPP ESME binds (plan §7, M3).
//
// A single account may hold several concurrent binds spread across pods; the registry keeps the
// account -> {pod_id, bind_id}[] table, enforces max_sessions at bind time (invariant d), and routes
// an inbound deliver_sm to the pod that owns the target bind. The registry never speaks SMPP: PDUs
// cross it as opaque bytes already encoded by internal/smpp.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: session.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionRegistry_Bind_FullMethodName    = "/session.SessionRegistry/Bind"
	SessionRegistry_Unbind_FullMethodName  = "/session.SessionRegistry/Unbind"
	SessionRegistry_Lookup_FullMethodName  = "/session.SessionRegistry/Lookup"
	SessionRegistry_Deliver_FullMethodName = "/session.SessionRegistry/Deliver"
)

// SessionRegistryClient is the client API for SessionRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionRegistry is served by session-manager-svc (gRPC :7000). Bind/Unbind/Lookup mutate and read
// the cross-pod registry; Deliver forwards an inbound deliver_sm to the pod owning the target bind.
type SessionRegistryClient interface {
	// Bind registers a new session, enforcing the account's max_sessions ceiling atomically.
	Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error)
	// Unbind removes a session from the registry (graceful unbind or connection loss).
	Unbind(ctx context.Context, in *UnbindRequest, opts ...grpc.CallOption) (*UnbindResponse, error)
	// Lookup returns the live sessions for an account, used to route return traffic.
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error)
	// Deliver forwards an already-encoded deliver_sm to the pod owning the target bind.
	Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
}

type sessionRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionRegistryClient(cc grpc.ClientConnInterface) SessionRegistryClient {
	return &sessionRegistryClient{cc}
}

func (c *sessionRegistryClient) Bind(ctx context.Context, in *BindRequest, opts ...grpc.CallOption) (*BindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindResponse)
	err := c.cc.Invoke(ctx, SessionRegistry_Bind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRegistryClient) Unbind(ctx context.Context, in *UnbindRequest, opts ...grpc.CallOption) (*UnbindResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindResponse)
	err := c.cc.Invoke(ctx, SessionRegistry_Unbind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRegistryClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupResponse)
	err := c.cc.Invoke(ctx, SessionRegistry_Lookup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionRegistryClient) Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, SessionRegistry_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionRegistryServer is the server API for SessionRegistry service.
// All implementations must embed UnimplementedSessionRegistryServer
// for forward compatibility.
//
// SessionRegistry is served by session-manager-svc (gRPC :7000). Bind/Unbind/Lookup mutate and read
// the cross-pod registry; Deliver forwards an inbound deliver_sm to the pod owning the target bind.
type SessionRegistryServer interface {
	// Bind registers a new session, enforcing the account's max_sessions ceiling atomically.
	Bind(context.Context, *BindRequest) (*BindResponse, error)
	// Unbind removes a session from the registry (graceful unbind or connection loss).
	Unbind(context.Context, *UnbindRequest) (*UnbindResponse, error)
	// Lookup returns the live sessions for an account, used to route return traffic.
	Lookup(context.Context, *LookupRequest) (*LookupResponse, error)
	// Deliver forwards an already-encoded deliver_sm to the pod owning the target bind.
	Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error)
	mustEmbedUnimplementedSessionRegistryServer()
}

// UnimplementedSessionRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionRegistryServer struct{}

func (UnimplementedSessionRegistryServer) Bind(context.Context, *BindRequest) (*BindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Bind not implemented")
}
func (UnimplementedSessionRegistryServer) Unbind(context.Context, *UnbindRequest) (*UnbindResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unbind not implemented")
}
func (UnimplementedSessionRegistryServer) Lookup(context.Context, *LookupRequest) (*LookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedSessionRegistryServer) Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedSessionRegistryServer) mustEmbedUnimplementedSessionRegistryServer() {}
func (UnimplementedSessionRegistryServer) testEmbeddedByValue()                         {}

// UnsafeSessionRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionRegistryServer will
// result in compilation errors.
type UnsafeSessionRegistryServer interface {
	mustEmbedUnimplementedSessionRegistryServer()
}

func RegisterSessionRegistryServer(s grpc.ServiceRegistrar, srv SessionRegistryServer) {
	// If the following call panics, it indicates UnimplementedSessionRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionRegistry_ServiceDesc, srv)
}

func _SessionRegistry_Bind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRegistryServer).Bind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRegistry_Bind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRegistryServer).Bind(ctx, req.(*BindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRegistry_Unbind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRegistryServer).Unbind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRegistry_Unbind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRegistryServer).Unbind(ctx, req.(*UnbindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRegistry_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRegistryServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRegistry_Lookup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRegistryServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionRegistry_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionRegistryServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionRegistry_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionRegistryServer).Deliver(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionRegistry_ServiceDesc is the grpc.ServiceDesc for SessionRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.SessionRegistry",
	HandlerType: (*SessionRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bind",
			Handler:    _SessionRegistry_Bind_Handler,
		},
		{
			MethodName: "Unbind",
			Handler:    _SessionRegistry_Unbind_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _SessionRegistry_Lookup_Handler,
		},
		{
			MethodName: "Deliver",
			Handler:    _SessionRegistry_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}
