package postgres

// The repositories in this package are hand-written, but the type-safe query methods they call are
// generated by sqlc from internal/storage/postgres/queries/*.sql into ./sqlcgen. `make generate`
// (go generate ./...) regenerates them. go generate runs from this package directory, so the
// directive points at sqlc.yaml at the repo root (three levels up).
//
//go:generate sqlc generate -f ../../../sqlc.yaml
