// ConfigSecrets seals and opens the control-plane secrets that the gateway REPLAYS to a third party —
// the outbound SMSC bind password (smsc_connectors, §6.8) and the external billing provider's
// credentials (external_billing_providers, §6.10). Those cannot be hashed: an outbound bind puts its
// password in clear in the bind_transceiver PDU (SMPP v3.4 §4.1.1), so the stored form must be
// reversible. The secrets the gateway VERIFIES instead of replaying (credentials.password_hash, the
// API key) stay hashed — see ADR-0016.
//
// It is served by content-key-svc (gRPC :7002) because that service already holds the KMS master key,
// and ADR-0011 wants that key in as few processes as possible. Sealing a password adds no dependency
// to it: still Postgres + gRPC, still no outbound client.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: configsecrets.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigSecrets_Seal_FullMethodName = "/configsecrets.ConfigSecrets/Seal"
	ConfigSecrets_Open_FullMethodName = "/configsecrets.ConfigSecrets/Open"
)

// ConfigSecretsClient is the client API for ConfigSecrets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigSecrets is DELIBERATELY not part of ContentKeys, which is customer-scoped and stateful (a key
// store, an active/retired/destroyed lifecycle, crypto-shred). This one is stateless: no store, no
// customer, no rotation.
//
// Being a separate service does NOT by itself keep the two apart — the mTLS allowlist is checked at the
// handshake, so it admits a binary and never sees the method, and both services share one master key
// whose ciphertexts are indistinguishable. Two mechanisms do the keeping apart, and the separate service
// only makes them legible:
//   - cmd/content-key-svc/authz.go authorises these RPCs per METHOD, to callers it names.
//   - internal/configsecrets prefixes a domain tag inside the ciphertext, so a content key cannot be
//     opened here and nothing sealed here can pass for a content key.
//
// Both RPCs handle plaintext secrets. A plaintext must never be logged nor persisted — only the sealed
// form is stored.
type ConfigSecretsClient interface {
	// Seal encrypts a secret under the KMS master key and returns the form to persist, plus the
	// reference of the key that sealed it. The plaintext is not retained.
	Seal(ctx context.Context, in *SealRequest, opts ...grpc.CallOption) (*SealResponse, error)
	// Open reverses Seal. Tampering, or a different master key, fails cleanly and returns no plaintext.
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
}

type configSecretsClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigSecretsClient(cc grpc.ClientConnInterface) ConfigSecretsClient {
	return &configSecretsClient{cc}
}

func (c *configSecretsClient) Seal(ctx context.Context, in *SealRequest, opts ...grpc.CallOption) (*SealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SealResponse)
	err := c.cc.Invoke(ctx, ConfigSecrets_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configSecretsClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, ConfigSecrets_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigSecretsServer is the server API for ConfigSecrets service.
// All implementations must embed UnimplementedConfigSecretsServer
// for forward compatibility.
//
// ConfigSecrets is DELIBERATELY not part of ContentKeys, which is customer-scoped and stateful (a key
// store, an active/retired/destroyed lifecycle, crypto-shred). This one is stateless: no store, no
// customer, no rotation.
//
// Being a separate service does NOT by itself keep the two apart — the mTLS allowlist is checked at the
// handshake, so it admits a binary and never sees the method, and both services share one master key
// whose ciphertexts are indistinguishable. Two mechanisms do the keeping apart, and the separate service
// only makes them legible:
//   - cmd/content-key-svc/authz.go authorises these RPCs per METHOD, to callers it names.
//   - internal/configsecrets prefixes a domain tag inside the ciphertext, so a content key cannot be
//     opened here and nothing sealed here can pass for a content key.
//
// Both RPCs handle plaintext secrets. A plaintext must never be logged nor persisted — only the sealed
// form is stored.
type ConfigSecretsServer interface {
	// Seal encrypts a secret under the KMS master key and returns the form to persist, plus the
	// reference of the key that sealed it. The plaintext is not retained.
	Seal(context.Context, *SealRequest) (*SealResponse, error)
	// Open reverses Seal. Tampering, or a different master key, fails cleanly and returns no plaintext.
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	mustEmbedUnimplementedConfigSecretsServer()
}

// UnimplementedConfigSecretsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigSecretsServer struct{}

func (UnimplementedConfigSecretsServer) Seal(context.Context, *SealRequest) (*SealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedConfigSecretsServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedConfigSecretsServer) mustEmbedUnimplementedConfigSecretsServer() {}
func (UnimplementedConfigSecretsServer) testEmbeddedByValue()                       {}

// UnsafeConfigSecretsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigSecretsServer will
// result in compilation errors.
type UnsafeConfigSecretsServer interface {
	mustEmbedUnimplementedConfigSecretsServer()
}

func RegisterConfigSecretsServer(s grpc.ServiceRegistrar, srv ConfigSecretsServer) {
	// If the following call panics, it indicates UnimplementedConfigSecretsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigSecrets_ServiceDesc, srv)
}

func _ConfigSecrets_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSecretsServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSecrets_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSecretsServer).Seal(ctx, req.(*SealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigSecrets_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigSecretsServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigSecrets_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigSecretsServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigSecrets_ServiceDesc is the grpc.ServiceDesc for ConfigSecrets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigSecrets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configsecrets.ConfigSecrets",
	HandlerType: (*ConfigSecretsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seal",
			Handler:    _ConfigSecrets_Seal_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _ConfigSecrets_Open_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configsecrets.proto",
}
