// ConfigSecrets seals and opens the control-plane secrets that the gateway REPLAYS to a third party —
// the outbound SMSC bind password (smsc_connectors, §6.8) and the external billing provider's
// credentials (external_billing_providers, §6.10). Those cannot be hashed: an outbound bind puts its
// password in clear in the bind_transceiver PDU (SMPP v3.4 §4.1.1), so the stored form must be
// reversible. The secrets the gateway VERIFIES instead of replaying (credentials.password_hash, the
// API key) stay hashed — see ADR-0016.
//
// It is served by content-key-svc (gRPC :7002) because that service already holds the KMS master key,
// and ADR-0011 wants that key in as few processes as possible. Sealing a password adds no dependency
// to it: still Postgres + gRPC, still no outbound client.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: configsecrets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SealRequest carries the secret to seal. plaintext is SENSITIVE: never logged, never persisted.
type SealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealRequest) Reset() {
	*x = SealRequest{}
	mi := &file_configsecrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealRequest) ProtoMessage() {}

func (x *SealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configsecrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealRequest.ProtoReflect.Descriptor instead.
func (*SealRequest) Descriptor() ([]byte, []int) {
	return file_configsecrets_proto_rawDescGZIP(), []int{0}
}

func (x *SealRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

// SealResponse carries the bytes to store in the *_sealed column, and the master key reference to store
// alongside them in the *_kms_key_ref column — so an operator can tell which KEK a row belongs to, and a
// future master-key rotation knows what it has to re-seal. It mirrors content_keys.kms_key_ref.
type SealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sealed        []byte                 `protobuf:"bytes,1,opt,name=sealed,proto3" json:"sealed,omitempty"`
	KmsKeyRef     string                 `protobuf:"bytes,2,opt,name=kms_key_ref,json=kmsKeyRef,proto3" json:"kms_key_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealResponse) Reset() {
	*x = SealResponse{}
	mi := &file_configsecrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealResponse) ProtoMessage() {}

func (x *SealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configsecrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealResponse.ProtoReflect.Descriptor instead.
func (*SealResponse) Descriptor() ([]byte, []int) {
	return file_configsecrets_proto_rawDescGZIP(), []int{1}
}

func (x *SealResponse) GetSealed() []byte {
	if x != nil {
		return x.Sealed
	}
	return nil
}

func (x *SealResponse) GetKmsKeyRef() string {
	if x != nil {
		return x.KmsKeyRef
	}
	return ""
}

// OpenRequest carries the stored sealed bytes. The key reference is NOT passed: the KMS unwraps with the
// master key it holds, exactly as ContentKeys.GetContentKey does — the stored ref is for operators and
// rotation, not for dispatch.
type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sealed        []byte                 `protobuf:"bytes,1,opt,name=sealed,proto3" json:"sealed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_configsecrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configsecrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_configsecrets_proto_rawDescGZIP(), []int{2}
}

func (x *OpenRequest) GetSealed() []byte {
	if x != nil {
		return x.Sealed
	}
	return nil
}

// OpenResponse carries the recovered secret. plaintext is SENSITIVE: never logged, never persisted.
type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_configsecrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configsecrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_configsecrets_proto_rawDescGZIP(), []int{3}
}

func (x *OpenResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

var File_configsecrets_proto protoreflect.FileDescriptor

const file_configsecrets_proto_rawDesc = "" +
	"\n" +
	"\x13configsecrets.proto\x12\rconfigsecrets\"+\n" +
	"\vSealRequest\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"F\n" +
	"\fSealResponse\x12\x16\n" +
	"\x06sealed\x18\x01 \x01(\fR\x06sealed\x12\x1e\n" +
	"\vkms_key_ref\x18\x02 \x01(\tR\tkmsKeyRef\"%\n" +
	"\vOpenRequest\x12\x16\n" +
	"\x06sealed\x18\x01 \x01(\fR\x06sealed\",\n" +
	"\fOpenResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext2\x91\x01\n" +
	"\rConfigSecrets\x12?\n" +
	"\x04Seal\x12\x1a.configsecrets.SealRequest\x1a\x1b.configsecrets.SealResponse\x12?\n" +
	"\x04Open\x12\x1a.configsecrets.OpenRequest\x1a\x1b.configsecrets.OpenResponseBCZAgithub.com/martialanouman/go-gateway/internal/configsecrets/pb;pbb\x06proto3"

var (
	file_configsecrets_proto_rawDescOnce sync.Once
	file_configsecrets_proto_rawDescData []byte
)

func file_configsecrets_proto_rawDescGZIP() []byte {
	file_configsecrets_proto_rawDescOnce.Do(func() {
		file_configsecrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configsecrets_proto_rawDesc), len(file_configsecrets_proto_rawDesc)))
	})
	return file_configsecrets_proto_rawDescData
}

var file_configsecrets_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_configsecrets_proto_goTypes = []any{
	(*SealRequest)(nil),  // 0: configsecrets.SealRequest
	(*SealResponse)(nil), // 1: configsecrets.SealResponse
	(*OpenRequest)(nil),  // 2: configsecrets.OpenRequest
	(*OpenResponse)(nil), // 3: configsecrets.OpenResponse
}
var file_configsecrets_proto_depIdxs = []int32{
	0, // 0: configsecrets.ConfigSecrets.Seal:input_type -> configsecrets.SealRequest
	2, // 1: configsecrets.ConfigSecrets.Open:input_type -> configsecrets.OpenRequest
	1, // 2: configsecrets.ConfigSecrets.Seal:output_type -> configsecrets.SealResponse
	3, // 3: configsecrets.ConfigSecrets.Open:output_type -> configsecrets.OpenResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_configsecrets_proto_init() }
func file_configsecrets_proto_init() {
	if File_configsecrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configsecrets_proto_rawDesc), len(file_configsecrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configsecrets_proto_goTypes,
		DependencyIndexes: file_configsecrets_proto_depIdxs,
		MessageInfos:      file_configsecrets_proto_msgTypes,
	}.Build()
	File_configsecrets_proto = out.File
	file_configsecrets_proto_goTypes = nil
	file_configsecrets_proto_depIdxs = nil
}
