// ContentKeys is the per-customer content-encryption key custody API (control_plane.content_keys, §6.14,
// M10). It is served by content-key-svc (gRPC :7002, step-167), a DEDICATED service: the KMS master key
// (the KEK that seals every per-customer data key) must live in as few processes as possible, and in one
// whose surface is small enough to audit. It was originally hosted by billing-svc (§14) — see ADR-0011.
//
// It is NOT gated by the billing opt-in: a customer with billing disabled still stores content and
// therefore still needs a content key.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: contentkeys.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContentKeys_GetOrCreateContentKey_FullMethodName   = "/contentkeys.ContentKeys/GetOrCreateContentKey"
	ContentKeys_RotateContentKey_FullMethodName        = "/contentkeys.ContentKeys/RotateContentKey"
	ContentKeys_GetContentEncryptionKey_FullMethodName = "/contentkeys.ContentKeys/GetContentEncryptionKey"
	ContentKeys_GetContentKey_FullMethodName           = "/contentkeys.ContentKeys/GetContentKey"
	ContentKeys_DestroyContentKeys_FullMethodName      = "/contentkeys.ContentKeys/DestroyContentKeys"
)

// ContentKeysClient is the client API for ContentKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContentKeys manages the per-customer content-encryption keys. Metadata responses carry key METADATA
// only — never the plaintext data key nor the wrapped bytes; the two RPCs that DO return usable key
// material (GetContentEncryptionKey, GetContentKey) are the guarded encrypt and decrypt paths, ride the
// intra-mesh mTLS, and their data key must never be logged nor persisted.
type ContentKeysClient interface {
	// GetOrCreateContentKey returns the customer's active content key, creating one (a fresh data key sealed
	// by the KMS) if none exists yet. Idempotent: concurrent callers converge on a single active key.
	GetOrCreateContentKey(ctx context.Context, in *GetOrCreateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error)
	// RotateContentKey makes a new active key and retires the previous one. The retired key is kept so CDRs
	// written under it stay decryptable — rotation never destroys key material (crypto-shred is separate).
	RotateContentKey(ctx context.Context, in *RotateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error)
	// GetContentEncryptionKey returns the customer's active key id AND its UNWRAPPED (plaintext) data key, so
	// the data plane can encrypt a body at CDR write without the body ever reaching the key service (§14). This is
	// the ONLY RPC that returns plaintext key material: it exists solely for the guarded encrypt path, rides
	// the intra-mesh mTLS, and the DEK must never be logged nor written to a CDR. Callers cache it briefly.
	GetContentEncryptionKey(ctx context.Context, in *GetContentEncryptionKeyRequest, opts ...grpc.CallOption) (*ContentEncryptionKeyResponse, error)
	// GetContentKey unwraps a SPECIFIC content key by id — the guarded DECRYPT path (get-message-content,
	// step-163). A CDR body may be sealed under a retired key (an old row after rotation), so the reader asks by
	// the row's key id, not by the active key. A destroyed (crypto-shredded) key returns destroyed=true and no
	// data key — the content is permanently unreadable. Like GetContentEncryptionKey the plaintext DEK is
	// sensitive: never logged, never persisted.
	GetContentKey(ctx context.Context, in *GetContentKeyRequest, opts ...grpc.CallOption) (*GetContentKeyResponse, error)
	// DestroyContentKeys crypto-shreds ALL of a customer's content keys (erase-customer-content, step-164): each
	// key is marked destroyed and its wrapped data key erased, so every body it sealed becomes permanently
	// unreadable WITHOUT rewriting the CDR. Idempotent. Returns how many keys were destroyed.
	DestroyContentKeys(ctx context.Context, in *DestroyContentKeysRequest, opts ...grpc.CallOption) (*DestroyContentKeysResponse, error)
}

type contentKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewContentKeysClient(cc grpc.ClientConnInterface) ContentKeysClient {
	return &contentKeysClient{cc}
}

func (c *contentKeysClient) GetOrCreateContentKey(ctx context.Context, in *GetOrCreateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_GetOrCreateContentKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentKeysClient) RotateContentKey(ctx context.Context, in *RotateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_RotateContentKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentKeysClient) GetContentEncryptionKey(ctx context.Context, in *GetContentEncryptionKeyRequest, opts ...grpc.CallOption) (*ContentEncryptionKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentEncryptionKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_GetContentEncryptionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentKeysClient) GetContentKey(ctx context.Context, in *GetContentKeyRequest, opts ...grpc.CallOption) (*GetContentKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContentKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_GetContentKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentKeysClient) DestroyContentKeys(ctx context.Context, in *DestroyContentKeysRequest, opts ...grpc.CallOption) (*DestroyContentKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyContentKeysResponse)
	err := c.cc.Invoke(ctx, ContentKeys_DestroyContentKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentKeysServer is the server API for ContentKeys service.
// All implementations must embed UnimplementedContentKeysServer
// for forward compatibility.
//
// ContentKeys manages the per-customer content-encryption keys. Metadata responses carry key METADATA
// only — never the plaintext data key nor the wrapped bytes; the two RPCs that DO return usable key
// material (GetContentEncryptionKey, GetContentKey) are the guarded encrypt and decrypt paths, ride the
// intra-mesh mTLS, and their data key must never be logged nor persisted.
type ContentKeysServer interface {
	// GetOrCreateContentKey returns the customer's active content key, creating one (a fresh data key sealed
	// by the KMS) if none exists yet. Idempotent: concurrent callers converge on a single active key.
	GetOrCreateContentKey(context.Context, *GetOrCreateContentKeyRequest) (*ContentKeyResponse, error)
	// RotateContentKey makes a new active key and retires the previous one. The retired key is kept so CDRs
	// written under it stay decryptable — rotation never destroys key material (crypto-shred is separate).
	RotateContentKey(context.Context, *RotateContentKeyRequest) (*ContentKeyResponse, error)
	// GetContentEncryptionKey returns the customer's active key id AND its UNWRAPPED (plaintext) data key, so
	// the data plane can encrypt a body at CDR write without the body ever reaching the key service (§14). This is
	// the ONLY RPC that returns plaintext key material: it exists solely for the guarded encrypt path, rides
	// the intra-mesh mTLS, and the DEK must never be logged nor written to a CDR. Callers cache it briefly.
	GetContentEncryptionKey(context.Context, *GetContentEncryptionKeyRequest) (*ContentEncryptionKeyResponse, error)
	// GetContentKey unwraps a SPECIFIC content key by id — the guarded DECRYPT path (get-message-content,
	// step-163). A CDR body may be sealed under a retired key (an old row after rotation), so the reader asks by
	// the row's key id, not by the active key. A destroyed (crypto-shredded) key returns destroyed=true and no
	// data key — the content is permanently unreadable. Like GetContentEncryptionKey the plaintext DEK is
	// sensitive: never logged, never persisted.
	GetContentKey(context.Context, *GetContentKeyRequest) (*GetContentKeyResponse, error)
	// DestroyContentKeys crypto-shreds ALL of a customer's content keys (erase-customer-content, step-164): each
	// key is marked destroyed and its wrapped data key erased, so every body it sealed becomes permanently
	// unreadable WITHOUT rewriting the CDR. Idempotent. Returns how many keys were destroyed.
	DestroyContentKeys(context.Context, *DestroyContentKeysRequest) (*DestroyContentKeysResponse, error)
	mustEmbedUnimplementedContentKeysServer()
}

// UnimplementedContentKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentKeysServer struct{}

func (UnimplementedContentKeysServer) GetOrCreateContentKey(context.Context, *GetOrCreateContentKeyRequest) (*ContentKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateContentKey not implemented")
}
func (UnimplementedContentKeysServer) RotateContentKey(context.Context, *RotateContentKeyRequest) (*ContentKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateContentKey not implemented")
}
func (UnimplementedContentKeysServer) GetContentEncryptionKey(context.Context, *GetContentEncryptionKeyRequest) (*ContentEncryptionKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentEncryptionKey not implemented")
}
func (UnimplementedContentKeysServer) GetContentKey(context.Context, *GetContentKeyRequest) (*GetContentKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentKey not implemented")
}
func (UnimplementedContentKeysServer) DestroyContentKeys(context.Context, *DestroyContentKeysRequest) (*DestroyContentKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyContentKeys not implemented")
}
func (UnimplementedContentKeysServer) mustEmbedUnimplementedContentKeysServer() {}
func (UnimplementedContentKeysServer) testEmbeddedByValue()                     {}

// UnsafeContentKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentKeysServer will
// result in compilation errors.
type UnsafeContentKeysServer interface {
	mustEmbedUnimplementedContentKeysServer()
}

func RegisterContentKeysServer(s grpc.ServiceRegistrar, srv ContentKeysServer) {
	// If the following call panics, it indicates UnimplementedContentKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentKeys_ServiceDesc, srv)
}

func _ContentKeys_GetOrCreateContentKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateContentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).GetOrCreateContentKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_GetOrCreateContentKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).GetOrCreateContentKey(ctx, req.(*GetOrCreateContentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentKeys_RotateContentKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateContentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).RotateContentKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_RotateContentKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).RotateContentKey(ctx, req.(*RotateContentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentKeys_GetContentEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentEncryptionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).GetContentEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_GetContentEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).GetContentEncryptionKey(ctx, req.(*GetContentEncryptionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentKeys_GetContentKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).GetContentKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_GetContentKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).GetContentKey(ctx, req.(*GetContentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentKeys_DestroyContentKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyContentKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).DestroyContentKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_DestroyContentKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).DestroyContentKeys(ctx, req.(*DestroyContentKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentKeys_ServiceDesc is the grpc.ServiceDesc for ContentKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contentkeys.ContentKeys",
	HandlerType: (*ContentKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateContentKey",
			Handler:    _ContentKeys_GetOrCreateContentKey_Handler,
		},
		{
			MethodName: "RotateContentKey",
			Handler:    _ContentKeys_RotateContentKey_Handler,
		},
		{
			MethodName: "GetContentEncryptionKey",
			Handler:    _ContentKeys_GetContentEncryptionKey_Handler,
		},
		{
			MethodName: "GetContentKey",
			Handler:    _ContentKeys_GetContentKey_Handler,
		},
		{
			MethodName: "DestroyContentKeys",
			Handler:    _ContentKeys_DestroyContentKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contentkeys.proto",
}
