// ContentKeys is the per-customer content-encryption key custody API (control_plane.content_keys, §6.14,
// M10). It is served by content-key-svc (gRPC :7002, step-167), a DEDICATED service: the KMS master key
// (the KEK that seals every per-customer data key) must live in as few processes as possible, and in one
// whose surface is small enough to audit. It was originally hosted by billing-svc (§14) — see ADR-0011.
//
// It is NOT gated by the billing opt-in: a customer with billing disabled still stores content and
// therefore still needs a content key.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: contentkeys.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetOrCreateContentKeyRequest names the customer whose active key to fetch or create.
type GetOrCreateContentKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateContentKeyRequest) Reset() {
	*x = GetOrCreateContentKeyRequest{}
	mi := &file_contentkeys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateContentKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateContentKeyRequest) ProtoMessage() {}

func (x *GetOrCreateContentKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateContentKeyRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateContentKeyRequest) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrCreateContentKeyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// RotateContentKeyRequest names the customer whose key to rotate.
type RotateContentKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateContentKeyRequest) Reset() {
	*x = RotateContentKeyRequest{}
	mi := &file_contentkeys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateContentKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateContentKeyRequest) ProtoMessage() {}

func (x *RotateContentKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateContentKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateContentKeyRequest) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{1}
}

func (x *RotateContentKeyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// ContentKeyResponse is the metadata of a content key. It never carries the plaintext or wrapped data key.
// status is one of active|retired|destroyed; created_at is RFC3339.
type ContentKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	KmsKeyRef     string                 `protobuf:"bytes,3,opt,name=kms_key_ref,json=kmsKeyRef,proto3" json:"kms_key_ref,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentKeyResponse) Reset() {
	*x = ContentKeyResponse{}
	mi := &file_contentkeys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentKeyResponse) ProtoMessage() {}

func (x *ContentKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentKeyResponse.ProtoReflect.Descriptor instead.
func (*ContentKeyResponse) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{2}
}

func (x *ContentKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ContentKeyResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ContentKeyResponse) GetKmsKeyRef() string {
	if x != nil {
		return x.KmsKeyRef
	}
	return ""
}

func (x *ContentKeyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContentKeyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// GetContentEncryptionKeyRequest names the customer whose active data key to fetch (creating one if absent).
type GetContentEncryptionKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentEncryptionKeyRequest) Reset() {
	*x = GetContentEncryptionKeyRequest{}
	mi := &file_contentkeys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentEncryptionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentEncryptionKeyRequest) ProtoMessage() {}

func (x *GetContentEncryptionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentEncryptionKeyRequest.ProtoReflect.Descriptor instead.
func (*GetContentEncryptionKeyRequest) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentEncryptionKeyRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// ContentEncryptionKeyResponse carries the active key id and its plaintext 32-byte data key. The dek is
// SENSITIVE: it must never be logged nor persisted (only the body ciphertext it produces is stored).
type ContentEncryptionKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Dek           []byte                 `protobuf:"bytes,2,opt,name=dek,proto3" json:"dek,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentEncryptionKeyResponse) Reset() {
	*x = ContentEncryptionKeyResponse{}
	mi := &file_contentkeys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentEncryptionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentEncryptionKeyResponse) ProtoMessage() {}

func (x *ContentEncryptionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentEncryptionKeyResponse.ProtoReflect.Descriptor instead.
func (*ContentEncryptionKeyResponse) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{4}
}

func (x *ContentEncryptionKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ContentEncryptionKeyResponse) GetDek() []byte {
	if x != nil {
		return x.Dek
	}
	return nil
}

// GetContentKeyRequest names a specific content key by id (the id a CDR row was sealed under).
type GetContentKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentKeyRequest) Reset() {
	*x = GetContentKeyRequest{}
	mi := &file_contentkeys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentKeyRequest) ProtoMessage() {}

func (x *GetContentKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentKeyRequest.ProtoReflect.Descriptor instead.
func (*GetContentKeyRequest) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{5}
}

func (x *GetContentKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// GetContentKeyResponse carries the unwrapped data key, OR reports the key destroyed. dek is the plaintext
// 32-byte data key (empty when destroyed); destroyed=true means the key was crypto-shredded and the content it
// sealed is permanently unreadable. The dek is SENSITIVE: never logged, never persisted.
type GetContentKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dek           []byte                 `protobuf:"bytes,1,opt,name=dek,proto3" json:"dek,omitempty"`
	Destroyed     bool                   `protobuf:"varint,2,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentKeyResponse) Reset() {
	*x = GetContentKeyResponse{}
	mi := &file_contentkeys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentKeyResponse) ProtoMessage() {}

func (x *GetContentKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentKeyResponse.ProtoReflect.Descriptor instead.
func (*GetContentKeyResponse) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{6}
}

func (x *GetContentKeyResponse) GetDek() []byte {
	if x != nil {
		return x.Dek
	}
	return nil
}

func (x *GetContentKeyResponse) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

// DestroyContentKeysRequest names the customer whose content keys to crypto-shred.
type DestroyContentKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyContentKeysRequest) Reset() {
	*x = DestroyContentKeysRequest{}
	mi := &file_contentkeys_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyContentKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyContentKeysRequest) ProtoMessage() {}

func (x *DestroyContentKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyContentKeysRequest.ProtoReflect.Descriptor instead.
func (*DestroyContentKeysRequest) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyContentKeysRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// DestroyContentKeysResponse reports how many keys were destroyed (0 when already shredded — idempotent).
type DestroyContentKeysResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DestroyedCount int32                  `protobuf:"varint,1,opt,name=destroyed_count,json=destroyedCount,proto3" json:"destroyed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DestroyContentKeysResponse) Reset() {
	*x = DestroyContentKeysResponse{}
	mi := &file_contentkeys_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyContentKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyContentKeysResponse) ProtoMessage() {}

func (x *DestroyContentKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contentkeys_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyContentKeysResponse.ProtoReflect.Descriptor instead.
func (*DestroyContentKeysResponse) Descriptor() ([]byte, []int) {
	return file_contentkeys_proto_rawDescGZIP(), []int{8}
}

func (x *DestroyContentKeysResponse) GetDestroyedCount() int32 {
	if x != nil {
		return x.DestroyedCount
	}
	return 0
}

var File_contentkeys_proto protoreflect.FileDescriptor

const file_contentkeys_proto_rawDesc = "" +
	"\n" +
	"\x11contentkeys.proto\x12\vcontentkeys\"?\n" +
	"\x1cGetOrCreateContentKeyRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\":\n" +
	"\x17RotateContentKeyRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"\xa3\x01\n" +
	"\x12ContentKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1e\n" +
	"\vkms_key_ref\x18\x03 \x01(\tR\tkmsKeyRef\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"A\n" +
	"\x1eGetContentEncryptionKeyRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"G\n" +
	"\x1cContentEncryptionKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x10\n" +
	"\x03dek\x18\x02 \x01(\fR\x03dek\"-\n" +
	"\x14GetContentKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"G\n" +
	"\x15GetContentKeyResponse\x12\x10\n" +
	"\x03dek\x18\x01 \x01(\fR\x03dek\x12\x1c\n" +
	"\tdestroyed\x18\x02 \x01(\bR\tdestroyed\"<\n" +
	"\x19DestroyContentKeysRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"E\n" +
	"\x1aDestroyContentKeysResponse\x12'\n" +
	"\x0fdestroyed_count\x18\x01 \x01(\x05R\x0edestroyedCount2\xff\x03\n" +
	"\vContentKeys\x12c\n" +
	"\x15GetOrCreateContentKey\x12).contentkeys.GetOrCreateContentKeyRequest\x1a\x1f.contentkeys.ContentKeyResponse\x12Y\n" +
	"\x10RotateContentKey\x12$.contentkeys.RotateContentKeyRequest\x1a\x1f.contentkeys.ContentKeyResponse\x12q\n" +
	"\x17GetContentEncryptionKey\x12+.contentkeys.GetContentEncryptionKeyRequest\x1a).contentkeys.ContentEncryptionKeyResponse\x12V\n" +
	"\rGetContentKey\x12!.contentkeys.GetContentKeyRequest\x1a\".contentkeys.GetContentKeyResponse\x12e\n" +
	"\x12DestroyContentKeys\x12&.contentkeys.DestroyContentKeysRequest\x1a'.contentkeys.DestroyContentKeysResponseBAZ?github.com/martialanouman/go-gateway/internal/contentkeys/pb;pbb\x06proto3"

var (
	file_contentkeys_proto_rawDescOnce sync.Once
	file_contentkeys_proto_rawDescData []byte
)

func file_contentkeys_proto_rawDescGZIP() []byte {
	file_contentkeys_proto_rawDescOnce.Do(func() {
		file_contentkeys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contentkeys_proto_rawDesc), len(file_contentkeys_proto_rawDesc)))
	})
	return file_contentkeys_proto_rawDescData
}

var file_contentkeys_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_contentkeys_proto_goTypes = []any{
	(*GetOrCreateContentKeyRequest)(nil),   // 0: contentkeys.GetOrCreateContentKeyRequest
	(*RotateContentKeyRequest)(nil),        // 1: contentkeys.RotateContentKeyRequest
	(*ContentKeyResponse)(nil),             // 2: contentkeys.ContentKeyResponse
	(*GetContentEncryptionKeyRequest)(nil), // 3: contentkeys.GetContentEncryptionKeyRequest
	(*ContentEncryptionKeyResponse)(nil),   // 4: contentkeys.ContentEncryptionKeyResponse
	(*GetContentKeyRequest)(nil),           // 5: contentkeys.GetContentKeyRequest
	(*GetContentKeyResponse)(nil),          // 6: contentkeys.GetContentKeyResponse
	(*DestroyContentKeysRequest)(nil),      // 7: contentkeys.DestroyContentKeysRequest
	(*DestroyContentKeysResponse)(nil),     // 8: contentkeys.DestroyContentKeysResponse
}
var file_contentkeys_proto_depIdxs = []int32{
	0, // 0: contentkeys.ContentKeys.GetOrCreateContentKey:input_type -> contentkeys.GetOrCreateContentKeyRequest
	1, // 1: contentkeys.ContentKeys.RotateContentKey:input_type -> contentkeys.RotateContentKeyRequest
	3, // 2: contentkeys.ContentKeys.GetContentEncryptionKey:input_type -> contentkeys.GetContentEncryptionKeyRequest
	5, // 3: contentkeys.ContentKeys.GetContentKey:input_type -> contentkeys.GetContentKeyRequest
	7, // 4: contentkeys.ContentKeys.DestroyContentKeys:input_type -> contentkeys.DestroyContentKeysRequest
	2, // 5: contentkeys.ContentKeys.GetOrCreateContentKey:output_type -> contentkeys.ContentKeyResponse
	2, // 6: contentkeys.ContentKeys.RotateContentKey:output_type -> contentkeys.ContentKeyResponse
	4, // 7: contentkeys.ContentKeys.GetContentEncryptionKey:output_type -> contentkeys.ContentEncryptionKeyResponse
	6, // 8: contentkeys.ContentKeys.GetContentKey:output_type -> contentkeys.GetContentKeyResponse
	8, // 9: contentkeys.ContentKeys.DestroyContentKeys:output_type -> contentkeys.DestroyContentKeysResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contentkeys_proto_init() }
func file_contentkeys_proto_init() {
	if File_contentkeys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contentkeys_proto_rawDesc), len(file_contentkeys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contentkeys_proto_goTypes,
		DependencyIndexes: file_contentkeys_proto_depIdxs,
		MessageInfos:      file_contentkeys_proto_msgTypes,
	}.Build()
	File_contentkeys_proto = out.File
	file_contentkeys_proto_goTypes = nil
	file_contentkeys_proto_depIdxs = nil
}
