// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO control_plane.smpp_accounts (
    customer_id, name, smpp_enabled, rest_enabled, sender_id_policy,
    query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions
) VALUES (
    $1,
    $2,
    COALESCE($3::boolean, true),
    COALESCE($4::boolean, true),
    COALESCE($5::text, 'strict'),
    COALESCE($6::boolean, true),
    COALESCE($7::boolean, true),
    COALESCE($8::text, 'trx'),
    COALESCE($9::integer, 1)
)
RETURNING id, customer_id, name, status, smpp_enabled, rest_enabled, sender_id_policy, query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions, created_at, updated_at
`

type CreateAccountParams struct {
	CustomerID       uuid.UUID
	Name             string
	SmppEnabled      *bool
	RestEnabled      *bool
	SenderIDPolicy   *string
	QuerySmEnabled   *bool
	CancelSmEnabled  *bool
	AllowedBindTypes *string
	MaxSessions      *int32
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (ControlPlaneSmppAccount, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.CustomerID,
		arg.Name,
		arg.SmppEnabled,
		arg.RestEnabled,
		arg.SenderIDPolicy,
		arg.QuerySmEnabled,
		arg.CancelSmEnabled,
		arg.AllowedBindTypes,
		arg.MaxSessions,
	)
	var i ControlPlaneSmppAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Status,
		&i.SmppEnabled,
		&i.RestEnabled,
		&i.SenderIDPolicy,
		&i.QuerySmEnabled,
		&i.CancelSmEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM control_plane.smpp_accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, customer_id, name, status, smpp_enabled, rest_enabled, sender_id_policy, query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions, created_at, updated_at FROM control_plane.smpp_accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (ControlPlaneSmppAccount, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i ControlPlaneSmppAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Status,
		&i.SmppEnabled,
		&i.RestEnabled,
		&i.SenderIDPolicy,
		&i.QuerySmEnabled,
		&i.CancelSmEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountCustomers = `-- name: ListAccountCustomers :many
SELECT id, customer_id FROM control_plane.smpp_accounts
`

type ListAccountCustomersRow struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
}

// Lightweight account -> customer projection for the MO router's snapshot (step-045): resolving an
// inbound number or keyword to an account needs the owning customer for the routed envelope.
func (q *Queries) ListAccountCustomers(ctx context.Context) ([]ListAccountCustomersRow, error) {
	rows, err := q.db.Query(ctx, listAccountCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountCustomersRow{}
	for rows.Next() {
		var i ListAccountCustomersRow
		if err := rows.Scan(&i.ID, &i.CustomerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountSenderIDPolicies = `-- name: ListAccountSenderIDPolicies :many
SELECT id, customer_id, sender_id_policy FROM control_plane.smpp_accounts
`

type ListAccountSenderIDPoliciesRow struct {
	ID             uuid.UUID
	CustomerID     uuid.UUID
	SenderIDPolicy string
}

// account -> (customer, sender_id_policy) projection for the sender-ID authorization snapshot
// (step-060). The policy is per account; the registered sender IDs it is checked against are per
// customer.
func (q *Queries) ListAccountSenderIDPolicies(ctx context.Context) ([]ListAccountSenderIDPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listAccountSenderIDPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountSenderIDPoliciesRow{}
	for rows.Next() {
		var i ListAccountSenderIDPoliciesRow
		if err := rows.Scan(&i.ID, &i.CustomerID, &i.SenderIDPolicy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT a.id, a.customer_id, a.name, a.status, a.smpp_enabled, a.rest_enabled, a.sender_id_policy, a.query_sm_enabled, a.cancel_sm_enabled, a.allowed_bind_types, a.max_sessions, a.created_at, a.updated_at FROM control_plane.smpp_accounts a
WHERE ($1::uuid IS NULL OR a.customer_id = $1)
  AND ($2::text     IS NULL OR a.status      = $2)
  AND ($3::uuid      IS NULL OR a.id          > $3)
  AND (
        $4::uuid IS NULL
        OR a.customer_id IN (
            SELECT c.id FROM control_plane.customers c WHERE c.group_id = $4
        )
      )
ORDER BY a.id
LIMIT $5
`

type ListAccountsParams struct {
	CustomerID *uuid.UUID
	Status     *string
	After      *uuid.UUID
	GroupID    *uuid.UUID
	Lim        int32
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ControlPlaneSmppAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.CustomerID,
		arg.Status,
		arg.After,
		arg.GroupID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneSmppAccount{}
	for rows.Next() {
		var i ControlPlaneSmppAccount
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Name,
			&i.Status,
			&i.SmppEnabled,
			&i.RestEnabled,
			&i.SenderIDPolicy,
			&i.QuerySmEnabled,
			&i.CancelSmEnabled,
			&i.AllowedBindTypes,
			&i.MaxSessions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountChannels = `-- name: SetAccountChannels :one
UPDATE control_plane.smpp_accounts SET smpp_enabled = $1, rest_enabled = $2
WHERE id = $3
RETURNING id, customer_id, name, status, smpp_enabled, rest_enabled, sender_id_policy, query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions, created_at, updated_at
`

type SetAccountChannelsParams struct {
	SmppEnabled bool
	RestEnabled bool
	ID          uuid.UUID
}

func (q *Queries) SetAccountChannels(ctx context.Context, arg SetAccountChannelsParams) (ControlPlaneSmppAccount, error) {
	row := q.db.QueryRow(ctx, setAccountChannels, arg.SmppEnabled, arg.RestEnabled, arg.ID)
	var i ControlPlaneSmppAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Status,
		&i.SmppEnabled,
		&i.RestEnabled,
		&i.SenderIDPolicy,
		&i.QuerySmEnabled,
		&i.CancelSmEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAccountSessionLimits = `-- name: SetAccountSessionLimits :one
UPDATE control_plane.smpp_accounts SET max_sessions = $1, allowed_bind_types = $2
WHERE id = $3
RETURNING id, customer_id, name, status, smpp_enabled, rest_enabled, sender_id_policy, query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions, created_at, updated_at
`

type SetAccountSessionLimitsParams struct {
	MaxSessions      int32
	AllowedBindTypes string
	ID               uuid.UUID
}

func (q *Queries) SetAccountSessionLimits(ctx context.Context, arg SetAccountSessionLimitsParams) (ControlPlaneSmppAccount, error) {
	row := q.db.QueryRow(ctx, setAccountSessionLimits, arg.MaxSessions, arg.AllowedBindTypes, arg.ID)
	var i ControlPlaneSmppAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Status,
		&i.SmppEnabled,
		&i.RestEnabled,
		&i.SenderIDPolicy,
		&i.QuerySmEnabled,
		&i.CancelSmEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const suspendAccount = `-- name: SuspendAccount :one
UPDATE control_plane.smpp_accounts SET status = 'suspended' WHERE id = $1 RETURNING id, customer_id, name, status, smpp_enabled, rest_enabled, sender_id_policy, query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions, created_at, updated_at
`

func (q *Queries) SuspendAccount(ctx context.Context, id uuid.UUID) (ControlPlaneSmppAccount, error) {
	row := q.db.QueryRow(ctx, suspendAccount, id)
	var i ControlPlaneSmppAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Status,
		&i.SmppEnabled,
		&i.RestEnabled,
		&i.SenderIDPolicy,
		&i.QuerySmEnabled,
		&i.CancelSmEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE control_plane.smpp_accounts SET
    name   = COALESCE($1, name),
    status = COALESCE($2, status)
WHERE id = $3
RETURNING id, customer_id, name, status, smpp_enabled, rest_enabled, sender_id_policy, query_sm_enabled, cancel_sm_enabled, allowed_bind_types, max_sessions, created_at, updated_at
`

type UpdateAccountParams struct {
	Name   *string
	Status *string
	ID     uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (ControlPlaneSmppAccount, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.Name, arg.Status, arg.ID)
	var i ControlPlaneSmppAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Name,
		&i.Status,
		&i.SmppEnabled,
		&i.RestEnabled,
		&i.SenderIDPolicy,
		&i.QuerySmEnabled,
		&i.CancelSmEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
