// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: antispam_rules.sql

package sqlcgen

import (
	"context"
)

const listActiveAntispamRules = `-- name: ListActiveAntispamRules :many
SELECT id, rule_type, scope, scope_id, config_json, action, status, created_at, updated_at FROM control_plane.antispam_rules WHERE status = 'active' ORDER BY scope, id
`

// Every active anti-spam rule, for the router's cold-loaded evaluation snapshot (step-065). Ordered
// by scope so the engine indexes account, customer and global rules deterministically.
func (q *Queries) ListActiveAntispamRules(ctx context.Context) ([]ControlPlaneAntispamRule, error) {
	rows, err := q.db.Query(ctx, listActiveAntispamRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneAntispamRule{}
	for rows.Next() {
		var i ControlPlaneAntispamRule
		if err := rows.Scan(
			&i.ID,
			&i.RuleType,
			&i.Scope,
			&i.ScopeID,
			&i.ConfigJson,
			&i.Action,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
