// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const finishAudit = `-- name: FinishAudit :exec
UPDATE control_plane.audit_log
   SET status = $2, finished_at = now()
 WHERE id = $1 AND status IS NULL
`

type FinishAuditParams struct {
	ID     uuid.UUID
	Status *int16
}

// Record the outcome of an audited request, once: an outcome already written is never replaced.
func (q *Queries) FinishAudit(ctx context.Context, arg FinishAuditParams) error {
	_, err := q.db.Exec(ctx, finishAudit, arg.ID, arg.Status)
	return err
}

const insertAuditIntent = `-- name: InsertAuditIntent :one
INSERT INTO control_plane.audit_log (operator, operation_id, method, target, request_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertAuditIntentParams struct {
	Operator    string
	OperationID string
	Method      string
	Target      string
	RequestID   *string
}

// Record an operator request before its handler runs: who, which operation, which path — never a body.
func (q *Queries) InsertAuditIntent(ctx context.Context, arg InsertAuditIntentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAuditIntent,
		arg.Operator,
		arg.OperationID,
		arg.Method,
		arg.Target,
		arg.RequestID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
