// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchUpsertExactRoute = `-- name: BatchUpsertExactRoute :batchexec
INSERT INTO control_plane.exact_routes (msisdn, target_type, target_id, source, imported_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (msisdn) DO UPDATE SET
    target_type = EXCLUDED.target_type,
    target_id   = EXCLUDED.target_id,
    source      = EXCLUDED.source,
    imported_at = EXCLUDED.imported_at,
    updated_at  = now()
`

type BatchUpsertExactRouteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertExactRouteParams struct {
	Msisdn     string
	TargetType string
	TargetID   uuid.UUID
	Source     string
	ImportedAt pgtype.Timestamptz
}

// Bulk create/update for an import (MNP / carrier feed): the repo sends one pgx.Batch of these, one
// round-trip, each row idempotent by msisdn so re-importing the same feed is safe.
func (q *Queries) BatchUpsertExactRoute(ctx context.Context, arg []BatchUpsertExactRouteParams) *BatchUpsertExactRouteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Msisdn,
			a.TargetType,
			a.TargetID,
			a.Source,
			a.ImportedAt,
		}
		batch.Queue(batchUpsertExactRoute, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertExactRouteBatchResults{br, len(arg), false}
}

func (b *BatchUpsertExactRouteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertExactRouteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
