// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adjustBalance = `-- name: AdjustBalance :one
INSERT INTO control_plane.balances (owner_type, owner_id, direction, credits)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_type, owner_id, direction)
DO UPDATE SET credits = control_plane.balances.credits + $4, updated_at = now()
RETURNING credits
`

type AdjustBalanceParams struct {
	OwnerType string
	OwnerID   uuid.UUID
	Direction string
	Delta     int32
}

// Apply a SIGNED delta to the durable owner balance for a direction (credits += delta), creating the row
// on first use, and RETURN the resulting balance. The delta form is order-independent: two concurrent
// movements for the same owner commit in any order and the balance is always the sum of every delta —
// which is exactly the append-only ledger's SUM(credits). An absolute set would let a stale write clobber
// a fresher one under the concurrency this system runs at.
func (q *Queries) AdjustBalance(ctx context.Context, arg AdjustBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, adjustBalance,
		arg.OwnerType,
		arg.OwnerID,
		arg.Direction,
		arg.Delta,
	)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const claimIdempotency = `-- name: ClaimIdempotency :execrows
INSERT INTO control_plane.billing_idempotency (message_id, entry_type)
VALUES ($1, $2)
ON CONFLICT (message_id, entry_type) DO NOTHING
`

type ClaimIdempotencyParams struct {
	MessageID uuid.UUID
	EntryType string
}

// Claim (message_id, entry_type) in the partition-free idempotency table BEFORE applying a movement
// (§6.9, invariant c). Returns the number of rows inserted: 1 = first time (proceed), 0 = the movement
// already happened on some earlier attempt (a replay, possibly across a day boundary the ledger's
// same-day index cannot see) — the caller skips the balance/ledger writes. The INSERT is the lock, so
// two concurrent replays cannot both proceed (no read-then-write race).
func (q *Queries) ClaimIdempotency(ctx context.Context, arg ClaimIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotency, arg.MessageID, arg.EntryType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumedCredits = `-- name: ConsumedCredits :one
SELECT COALESCE(-SUM(l.credits), 0)::bigint AS consumed
FROM control_plane.billing_ledger l
WHERE l.customer_id = $1 AND l.direction = 'mt' AND l.entry_type = 'reserve'
  AND EXISTS (
    SELECT 1 FROM control_plane.billing_ledger c
    WHERE c.message_id = l.message_id AND c.entry_type = 'capture'
      AND c.customer_id = l.customer_id AND c.direction = 'mt'
  )
`

// The customer's LOCALLY SETTLED MT consumption (§6.10 reconciliation): the sum of reserve debits for
// messages that were captured (not released). Reserve debits are negative, so negate to a positive consumed
// total; a message reserved-then-released nets nothing and is excluded by the capture EXISTS. In-flight holds
// (reserved, not yet captured) are legitimate skew and are excluded. Compared off the critical path against
// the external provider's reported usage; a difference is reported, never auto-corrected.
func (q *Queries) ConsumedCredits(ctx context.Context, customerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, consumedCredits, customerID)
	var consumed int64
	err := row.Scan(&consumed)
	return consumed, err
}

const getBalance = `-- name: GetBalance :one
SELECT credits
FROM control_plane.balances
WHERE owner_type = $1 AND owner_id = $2 AND direction = $3
`

type GetBalanceParams struct {
	OwnerType string
	OwnerID   uuid.UUID
	Direction string
}

// The durable authority for one owner balance (owner_type, owner_id, direction). PostgreSQL owns the
// balance; Redis caches it (§6.9). A missing row means zero credits ever recorded — the caller treats
// absence as 0, not an error.
func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.OwnerType, arg.OwnerID, arg.Direction)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT credits FROM control_plane.balances
WHERE owner_type = $1 AND owner_id = $2 AND direction = $3
FOR UPDATE
`

type GetBalanceForUpdateParams struct {
	OwnerType string
	OwnerID   uuid.UUID
	Direction string
}

// Read one owner balance and LOCK its row (§6.9, step-148 admin transfer / change-scope). The lock
// serialises this admin tx against a concurrent durable mirror write to the same balance, so a transfer's
// overdraw check and a change-scope zero-check see a stable value. A missing row is a legitimate 0.
func (q *Queries) GetBalanceForUpdate(ctx context.Context, arg GetBalanceForUpdateParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, arg.OwnerType, arg.OwnerID, arg.Direction)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const getBillingCustomer = `-- name: GetBillingCustomer :one
SELECT billing_mode, overdraft_enabled, overdraft_limit, credit_limit, credit_limit_is_hard,
       mo_billing_floor, external_billing_provider_id
FROM control_plane.customers
WHERE id = $1
`

type GetBillingCustomerRow struct {
	BillingMode               *string
	OverdraftEnabled          bool
	OverdraftLimit            *int32
	CreditLimit               *int32
	CreditLimitIsHard         bool
	MoBillingFloor            *int32
	ExternalBillingProviderID *uuid.UUID
}

// A customer's MT billing configuration. Billing config lives on the customer row itself (§6.9, step-142d
// consolidation); a missing customer row is not_found. billing_mode NULL means unset (treated as strict
// prepaid by the floor mapping).
func (q *Queries) GetBillingCustomer(ctx context.Context, customerID uuid.UUID) (GetBillingCustomerRow, error) {
	row := q.db.QueryRow(ctx, getBillingCustomer, customerID)
	var i GetBillingCustomerRow
	err := row.Scan(
		&i.BillingMode,
		&i.OverdraftEnabled,
		&i.OverdraftLimit,
		&i.CreditLimit,
		&i.CreditLimitIsHard,
		&i.MoBillingFloor,
		&i.ExternalBillingProviderID,
	)
	return i, err
}

const getReserveEntry = `-- name: GetReserveEntry :one
SELECT credits, balance_after
FROM control_plane.billing_ledger
WHERE message_id = $1 AND entry_type = 'reserve'
ORDER BY created_at DESC
LIMIT 1
`

type GetReserveEntryRow struct {
	Credits      int32
	BalanceAfter int32
}

// The reserve ledger entry for a message_id (the amount of record, §6.9). The capture and release paths
// read it to recover the reserved amount and the post-reserve balance when the short-TTL Redis hold has
// lapsed. credits is the signed reserve delta (negative); balance_after is the balance right after the
// reserve. The latest reserve wins (there is at most one per message under normal operation).
func (q *Queries) GetReserveEntry(ctx context.Context, messageID *uuid.UUID) (GetReserveEntryRow, error) {
	row := q.db.QueryRow(ctx, getReserveEntry, messageID)
	var i GetReserveEntryRow
	err := row.Scan(&i.Credits, &i.BalanceAfter)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO control_plane.billing_ledger
  (owner_type, owner_id, direction, customer_id, account_id, message_id, entry_type, credits,
   balance_after, reference)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8,
   $9, $10)
RETURNING id, created_at
`

type InsertLedgerEntryParams struct {
	OwnerType    string
	OwnerID      uuid.UUID
	Direction    string
	CustomerID   uuid.UUID
	AccountID    *uuid.UUID
	MessageID    *uuid.UUID
	EntryType    string
	Credits      int32
	BalanceAfter int32
	Reference    *string
}

type InsertLedgerEntryRow struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

// Append one ledger row and return its generated id and created_at. The ledger is APPEND-ONLY (§6.9): a row
// is never updated once written, so the history is immutable and auditable. balance_after is supplied by the
// caller's atomic path. The returned id/created_at let an admin top-up/transfer echo the created entries.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (InsertLedgerEntryRow, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.OwnerType,
		arg.OwnerID,
		arg.Direction,
		arg.CustomerID,
		arg.AccountID,
		arg.MessageID,
		arg.EntryType,
		arg.Credits,
		arg.BalanceAfter,
		arg.Reference,
	)
	var i InsertLedgerEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const ledgerEntryExists = `-- name: LedgerEntryExists :one
SELECT EXISTS (
  SELECT 1 FROM control_plane.billing_ledger
  WHERE message_id = $1 AND entry_type = $2
) AS entry_exists
`

type LedgerEntryExistsParams struct {
	MessageID *uuid.UUID
	EntryType string
}

// The AUTHORITATIVE cross-partition idempotency guard (§6.9): whether a ledger entry of entry_type
// already exists for message_id. Read before a capture so a redelivery of the same message_id never
// double-charges. The unique index billing_ledger_idem_idx is only a same-day backstop and must not be
// relied on alone at a day boundary — hence this explicit check, which spans every partition.
func (q *Queries) LedgerEntryExists(ctx context.Context, arg LedgerEntryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerEntryExists, arg.MessageID, arg.EntryType)
	var entry_exists bool
	err := row.Scan(&entry_exists)
	return entry_exists, err
}

const listBillingCustomers = `-- name: ListBillingCustomers :many
SELECT id AS customer_id, billing_mode, overdraft_enabled, overdraft_limit, credit_limit,
       credit_limit_is_hard, mo_billing_floor, external_billing_provider_id
FROM control_plane.customers
WHERE billing_enabled
`

type ListBillingCustomersRow struct {
	CustomerID                uuid.UUID
	BillingMode               *string
	OverdraftEnabled          bool
	OverdraftLimit            *int32
	CreditLimit               *int32
	CreditLimitIsHard         bool
	MoBillingFloor            *int32
	ExternalBillingProviderID *uuid.UUID
}

// The MT billing configuration of every billing-enabled customer, for config-sync to compile the
// reserve-floor snapshot (step-142b/d). Read whole and swapped atomically; a customer absent from the
// result (billing disabled, or not yet created) fails closed to strict prepaid at read time.
func (q *Queries) ListBillingCustomers(ctx context.Context) ([]ListBillingCustomersRow, error) {
	rows, err := q.db.Query(ctx, listBillingCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingCustomersRow{}
	for rows.Next() {
		var i ListBillingCustomersRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.BillingMode,
			&i.OverdraftEnabled,
			&i.OverdraftLimit,
			&i.CreditLimit,
			&i.CreditLimitIsHard,
			&i.MoBillingFloor,
			&i.ExternalBillingProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingScopes = `-- name: ListBillingScopes :many
SELECT id AS customer_id, balance_scope
FROM control_plane.customers
WHERE billing_enabled
`

type ListBillingScopesRow struct {
	CustomerID   uuid.UUID
	BalanceScope string
}

// The identity and balance scope of every billing-enabled customer, for router-svc to compile the
// credit-stage gate + owner-resolution snapshot (step-145). Presence in the result IS the billing-enabled
// flag: a customer absent from it (billing disabled, or not yet created) is not billed and makes NO billing
// round-trip. balance_scope NULL defaults to 'customer' at read time (the schema default).
func (q *Queries) ListBillingScopes(ctx context.Context) ([]ListBillingScopesRow, error) {
	rows, err := q.db.Query(ctx, listBillingScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingScopesRow{}
	for rows.Next() {
		var i ListBillingScopesRow
		if err := rows.Scan(&i.CustomerID, &i.BalanceScope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalBillingConfigs = `-- name: ListExternalBillingConfigs :many
SELECT c.id AS customer_id, p.id AS provider_id, p.mode, p.sync_call_timeout_ms,
       p.failure_policy, p.cache_ttl_ms
FROM control_plane.customers c
JOIN control_plane.external_billing_providers p ON c.external_billing_provider_id = p.id
WHERE c.billing_enabled AND p.status = 'active'
`

type ListExternalBillingConfigsRow struct {
	CustomerID        uuid.UUID
	ProviderID        uuid.UUID
	Mode              string
	SyncCallTimeoutMs *int32
	FailurePolicy     string
	CacheTtlMs        int32
}

// The ACTIVE external billing provider (§6.10) of every billing-enabled customer that references one — the
// customers→providers join, read together with ListBillingCustomers so billing-svc compiles a consistent
// snapshot. A customer with no provider, or whose provider is disabled, is absent (external layer off). The
// inner join guarantees no dangling reference; status='active' is the operator kill switch.
func (q *Queries) ListExternalBillingConfigs(ctx context.Context) ([]ListExternalBillingConfigsRow, error) {
	rows, err := q.db.Query(ctx, listExternalBillingConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalBillingConfigsRow{}
	for rows.Next() {
		var i ListExternalBillingConfigsRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.ProviderID,
			&i.Mode,
			&i.SyncCallTimeoutMs,
			&i.FailurePolicy,
			&i.CacheTtlMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedger = `-- name: ListLedger :many
SELECT id, owner_type, owner_id, direction, customer_id, account_id, message_id, entry_type, credits,
       balance_after, reference, created_at
FROM control_plane.billing_ledger
WHERE customer_id = $1
  AND ($2::text IS NULL OR direction = $2)
  AND ($3::uuid IS NULL OR account_id = $3)
  AND ($4::timestamptz IS NULL
       OR created_at < $4
       OR (created_at = $4 AND id < $5))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListLedgerParams struct {
	CustomerID   uuid.UUID
	Direction    *string
	AccountID    *uuid.UUID
	AfterCreated pgtype.Timestamptz
	AfterID      *uuid.UUID
	Lim          int32
}

// One keyset page of a customer's billing ledger, newest first (step-149 get-billing-ledger). Optional
// direction/account_id filters. The keyset is (created_at, id) DESC so rows sharing a created_at are not
// dropped (id is a time-ordered UUIDv7). A NULL after_created is the first page. Never selects a message body
// (the ledger has none). @lim is fetched as page+1 so the caller can detect a further page.
func (q *Queries) ListLedger(ctx context.Context, arg ListLedgerParams) ([]ControlPlaneBillingLedger, error) {
	rows, err := q.db.Query(ctx, listLedger,
		arg.CustomerID,
		arg.Direction,
		arg.AccountID,
		arg.AfterCreated,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneBillingLedger{}
	for rows.Next() {
		var i ControlPlaneBillingLedger
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Direction,
			&i.CustomerID,
			&i.AccountID,
			&i.MessageID,
			&i.EntryType,
			&i.Credits,
			&i.BalanceAfter,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedReservations = `-- name: ListOrphanedReservations :many
SELECT i.message_id, r.owner_type, r.owner_id, r.customer_id, r.account_id, r.credits,
       i.created_at AS reserved_at
FROM control_plane.billing_idempotency i
CROSS JOIN LATERAL (
  SELECT owner_type, owner_id, customer_id, account_id, credits
  FROM control_plane.billing_ledger
  WHERE message_id = i.message_id AND entry_type = 'reserve'
  ORDER BY created_at DESC
  LIMIT 1
) r
WHERE i.entry_type = 'reserve'
  AND i.created_at < $1
  AND NOT EXISTS (
    SELECT 1 FROM control_plane.billing_idempotency s
    WHERE s.message_id = i.message_id AND s.entry_type IN ('capture', 'release')
  )
ORDER BY i.created_at
LIMIT $2
`

type ListOrphanedReservationsParams struct {
	OlderThan pgtype.Timestamptz
	RowLimit  int32
}

type ListOrphanedReservationsRow struct {
	MessageID  uuid.UUID
	OwnerType  string
	OwnerID    uuid.UUID
	CustomerID uuid.UUID
	AccountID  *uuid.UUID
	Credits    int32
	ReservedAt pgtype.Timestamptz
}

// The reaper's detection query (step-190): reservations whose money was never closed. A message is
// orphaned when it holds a `reserve` claim but NEITHER a `capture` NOR a `release` — the settle loop in
// connector-pool fails open, so a billing outage leaves the reserve debit standing with nothing to
// reconcile it.
//
// Detection reads control_plane.billing_idempotency, NOT the ledger's own idempotency index: that index
// must include the partition key (created_at) and therefore cannot span day partitions, so a reservation
// settled across midnight would look unsettled to it. billing_idempotency is unpartitioned and
// authoritative, and its created_at index keeps this sweep cheap.
//
// The LATERAL recovers the owner and amount from the ledger, which billing_idempotency does not carry.
// It is a CROSS JOIN on purpose: a claim whose ledger partition has already been detached to object
// storage (§6.14.2) drops out of the result, because a reservation whose ledger row is archived can no
// longer be settled and must not be reported as actionable.
func (q *Queries) ListOrphanedReservations(ctx context.Context, arg ListOrphanedReservationsParams) ([]ListOrphanedReservationsRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedReservations, arg.OlderThan, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanedReservationsRow{}
	for rows.Next() {
		var i ListOrphanedReservationsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.OwnerType,
			&i.OwnerID,
			&i.CustomerID,
			&i.AccountID,
			&i.Credits,
			&i.ReservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomerScope = `-- name: LockCustomerScope :one
SELECT balance_scope FROM control_plane.customers WHERE id = $1 FOR UPDATE
`

// Read a customer's current balance_scope and LOCK the customer row, so two concurrent change-scope admin
// txns on the same customer serialise (step-148). not_found if the customer does not exist.
func (q *Queries) LockCustomerScope(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockCustomerScope, id)
	var balance_scope string
	err := row.Scan(&balance_scope)
	return balance_scope, err
}

const updateBalanceScope = `-- name: UpdateBalanceScope :execrows
UPDATE control_plane.customers
SET balance_scope = $1, updated_at = now()
WHERE id = $2
`

type UpdateBalanceScopeParams struct {
	BalanceScope string
	ID           uuid.UUID
}

// Flip a customer's balance_scope (step-148). Returns rows affected: 0 = no such customer. The same-table
// CHECK (step-142c) still rejects 'smpp_account' when a hard credit limit or overdraft is set — that raises
// a CHECK violation the caller's translate() maps to validation_error (422), not a 500.
func (q *Queries) UpdateBalanceScope(ctx context.Context, arg UpdateBalanceScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBalanceScope, arg.BalanceScope, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
