// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const adjustBalance = `-- name: AdjustBalance :one
INSERT INTO control_plane.balances (owner_type, owner_id, direction, credits)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_type, owner_id, direction)
DO UPDATE SET credits = control_plane.balances.credits + $4, updated_at = now()
RETURNING credits
`

type AdjustBalanceParams struct {
	OwnerType string
	OwnerID   uuid.UUID
	Direction string
	Delta     int32
}

// Apply a SIGNED delta to the durable owner balance for a direction (credits += delta), creating the row
// on first use, and RETURN the resulting balance. The delta form is order-independent: two concurrent
// movements for the same owner commit in any order and the balance is always the sum of every delta —
// which is exactly the append-only ledger's SUM(credits). An absolute set would let a stale write clobber
// a fresher one under the concurrency this system runs at.
func (q *Queries) AdjustBalance(ctx context.Context, arg AdjustBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, adjustBalance,
		arg.OwnerType,
		arg.OwnerID,
		arg.Direction,
		arg.Delta,
	)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const claimIdempotency = `-- name: ClaimIdempotency :execrows
INSERT INTO control_plane.billing_idempotency (message_id, entry_type)
VALUES ($1, $2)
ON CONFLICT (message_id, entry_type) DO NOTHING
`

type ClaimIdempotencyParams struct {
	MessageID uuid.UUID
	EntryType string
}

// Claim (message_id, entry_type) in the partition-free idempotency table BEFORE applying a movement
// (§6.9, invariant c). Returns the number of rows inserted: 1 = first time (proceed), 0 = the movement
// already happened on some earlier attempt (a replay, possibly across a day boundary the ledger's
// same-day index cannot see) — the caller skips the balance/ledger writes. The INSERT is the lock, so
// two concurrent replays cannot both proceed (no read-then-write race).
func (q *Queries) ClaimIdempotency(ctx context.Context, arg ClaimIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotency, arg.MessageID, arg.EntryType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBalance = `-- name: GetBalance :one
SELECT credits
FROM control_plane.balances
WHERE owner_type = $1 AND owner_id = $2 AND direction = $3
`

type GetBalanceParams struct {
	OwnerType string
	OwnerID   uuid.UUID
	Direction string
}

// The durable authority for one owner balance (owner_type, owner_id, direction). PostgreSQL owns the
// balance; Redis caches it (§6.9). A missing row means zero credits ever recorded — the caller treats
// absence as 0, not an error.
func (q *Queries) GetBalance(ctx context.Context, arg GetBalanceParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBalance, arg.OwnerType, arg.OwnerID, arg.Direction)
	var credits int32
	err := row.Scan(&credits)
	return credits, err
}

const getBillingCustomer = `-- name: GetBillingCustomer :one
SELECT billing_mode, overdraft_enabled, overdraft_limit, credit_limit, credit_limit_is_hard,
       external_billing_provider_id
FROM control_plane.billing_customers
WHERE customer_id = $1
`

type GetBillingCustomerRow struct {
	BillingMode               string
	OverdraftEnabled          bool
	OverdraftLimit            *int32
	CreditLimit               *int32
	CreditLimitIsHard         bool
	ExternalBillingProviderID *uuid.UUID
}

// A customer's MT billing configuration. A missing row means billing is not configured for the customer
// — the caller treats absence as "unconfigured", not an error.
func (q *Queries) GetBillingCustomer(ctx context.Context, customerID uuid.UUID) (GetBillingCustomerRow, error) {
	row := q.db.QueryRow(ctx, getBillingCustomer, customerID)
	var i GetBillingCustomerRow
	err := row.Scan(
		&i.BillingMode,
		&i.OverdraftEnabled,
		&i.OverdraftLimit,
		&i.CreditLimit,
		&i.CreditLimitIsHard,
		&i.ExternalBillingProviderID,
	)
	return i, err
}

const getReserveEntry = `-- name: GetReserveEntry :one
SELECT credits, balance_after
FROM control_plane.billing_ledger
WHERE message_id = $1 AND entry_type = 'reserve'
ORDER BY created_at DESC
LIMIT 1
`

type GetReserveEntryRow struct {
	Credits      int32
	BalanceAfter int32
}

// The reserve ledger entry for a message_id (the amount of record, §6.9). The capture and release paths
// read it to recover the reserved amount and the post-reserve balance when the short-TTL Redis hold has
// lapsed. credits is the signed reserve delta (negative); balance_after is the balance right after the
// reserve. The latest reserve wins (there is at most one per message under normal operation).
func (q *Queries) GetReserveEntry(ctx context.Context, messageID *uuid.UUID) (GetReserveEntryRow, error) {
	row := q.db.QueryRow(ctx, getReserveEntry, messageID)
	var i GetReserveEntryRow
	err := row.Scan(&i.Credits, &i.BalanceAfter)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO control_plane.billing_ledger
  (owner_type, owner_id, direction, customer_id, account_id, message_id, entry_type, credits,
   balance_after, reference)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8,
   $9, $10)
`

type InsertLedgerEntryParams struct {
	OwnerType    string
	OwnerID      uuid.UUID
	Direction    string
	CustomerID   uuid.UUID
	AccountID    *uuid.UUID
	MessageID    *uuid.UUID
	EntryType    string
	Credits      int32
	BalanceAfter int32
	Reference    *string
}

// Append one ledger row. The ledger is APPEND-ONLY (§6.9): a row is never updated once written, so the
// history is immutable and auditable. balance_after is supplied by the caller's atomic path.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.OwnerType,
		arg.OwnerID,
		arg.Direction,
		arg.CustomerID,
		arg.AccountID,
		arg.MessageID,
		arg.EntryType,
		arg.Credits,
		arg.BalanceAfter,
		arg.Reference,
	)
	return err
}

const ledgerEntryExists = `-- name: LedgerEntryExists :one
SELECT EXISTS (
  SELECT 1 FROM control_plane.billing_ledger
  WHERE message_id = $1 AND entry_type = $2
) AS entry_exists
`

type LedgerEntryExistsParams struct {
	MessageID *uuid.UUID
	EntryType string
}

// The AUTHORITATIVE cross-partition idempotency guard (§6.9): whether a ledger entry of entry_type
// already exists for message_id. Read before a capture so a redelivery of the same message_id never
// double-charges. The unique index billing_ledger_idem_idx is only a same-day backstop and must not be
// relied on alone at a day boundary — hence this explicit check, which spans every partition.
func (q *Queries) LedgerEntryExists(ctx context.Context, arg LedgerEntryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerEntryExists, arg.MessageID, arg.EntryType)
	var entry_exists bool
	err := row.Scan(&entry_exists)
	return entry_exists, err
}
