// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cdr_archives.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordCDRArchive = `-- name: RecordCDRArchive :one
WITH inserted AS (
  INSERT INTO control_plane.cdr_archives (day, object, row_count)
  VALUES ($1, $2, $3)
  ON CONFLICT (day) DO NOTHING
  RETURNING object
)
SELECT object FROM inserted
UNION ALL
SELECT object FROM control_plane.cdr_archives WHERE day = $1
LIMIT 1
`

type RecordCDRArchiveParams struct {
	Day      pgtype.Date
	Object   string
	RowCount int64
}

// First writer wins and the row is never rewritten: returns the object of whichever line now holds the
// day. The outer SELECT cannot see the CTE's own insert, nor a concurrent one committed while the insert
// waited on it: no row then, and the caller runs the statement again.
func (q *Queries) RecordCDRArchive(ctx context.Context, arg RecordCDRArchiveParams) (string, error) {
	row := q.db.QueryRow(ctx, recordCDRArchive, arg.Day, arg.Object, arg.RowCount)
	var object string
	err := row.Scan(&object)
	return object, err
}
