// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cdr_archives.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordCDRArchive = `-- name: RecordCDRArchive :one
WITH inserted AS (
  INSERT INTO control_plane.cdr_archives (day, object, row_count)
  VALUES ($1, $2, $3)
  ON CONFLICT (day) DO NOTHING
  RETURNING row_count
)
SELECT row_count FROM inserted
UNION ALL
SELECT row_count FROM control_plane.cdr_archives WHERE day = $1
LIMIT 1
`

type RecordCDRArchiveParams struct {
	Day      pgtype.Date
	Object   string
	RowCount int64
}

// First writer wins and the row is never rewritten: returns the row_count of whichever line now holds the
// day. The outer SELECT cannot see the CTE's own insert, so exactly one branch yields a row.
func (q *Queries) RecordCDRArchive(ctx context.Context, arg RecordCDRArchiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, recordCDRArchive, arg.Day, arg.Object, arg.RowCount)
	var row_count int64
	err := row.Scan(&row_count)
	return row_count, err
}
