// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connectors.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConnector = `-- name: CreateConnector :one
INSERT INTO control_plane.smsc_connectors (
    name, host, port, bind_type, system_id, password_hash, vendor_profile,
    interface_version, data_coding_default, window_size, bind_pool_size,
    throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, auto_reconnect_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    COALESCE($8::smallint, 52),
    $9,
    COALESCE($10::integer, 10),
    COALESCE($11::integer, 1),
    $12,
    COALESCE($13::boolean, false),
    $14,
    COALESCE($15::integer, 0),
    COALESCE($16::boolean, false)
)
RETURNING id, name, host, port, bind_type, system_id, password_hash, vendor_profile, system_type, interface_version, addr_ton, addr_npi, address_range, source_addr_ton, source_addr_npi, dest_addr_ton, dest_addr_npi, data_coding_default, registered_delivery_default, replace_if_present_flag_default, esm_class_default, priority_flag_default, validity_period_default, sm_default_msg_id, enquire_link_interval_sec, enquire_link_max_missed, bind_timeout_ms, response_timeout_ms, window_size, bind_pool_size, throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, status, auto_reconnect_enabled, reconnect_initial_delay_ms, reconnect_multiplier, reconnect_max_delay_ms, reconnect_jitter_pct, reconnect_max_attempts, created_at, updated_at
`

type CreateConnectorParams struct {
	Name                  string
	Host                  string
	Port                  int32
	BindType              string
	SystemID              string
	PasswordHash          string
	VendorProfile         *string
	InterfaceVersion      *int16
	DataCodingDefault     *int16
	WindowSize            *int32
	BindPoolSize          *int32
	ThroughputLimitPerSec *int32
	TlsEnabled            *bool
	TlsConfigJson         []byte
	PriorityTier          *int32
	AutoReconnectEnabled  *bool
}

// Only the columns ConnectorCreate settles are set here; the SMPP wire-parameter block and the
// reconnect tuning knobs take their DDL defaults. A duplicate name violates the inline UNIQUE on
// name -> 409.
func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (ControlPlaneSmscConnector, error) {
	row := q.db.QueryRow(ctx, createConnector,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.BindType,
		arg.SystemID,
		arg.PasswordHash,
		arg.VendorProfile,
		arg.InterfaceVersion,
		arg.DataCodingDefault,
		arg.WindowSize,
		arg.BindPoolSize,
		arg.ThroughputLimitPerSec,
		arg.TlsEnabled,
		arg.TlsConfigJson,
		arg.PriorityTier,
		arg.AutoReconnectEnabled,
	)
	var i ControlPlaneSmscConnector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.BindType,
		&i.SystemID,
		&i.PasswordHash,
		&i.VendorProfile,
		&i.SystemType,
		&i.InterfaceVersion,
		&i.AddrTon,
		&i.AddrNpi,
		&i.AddressRange,
		&i.SourceAddrTon,
		&i.SourceAddrNpi,
		&i.DestAddrTon,
		&i.DestAddrNpi,
		&i.DataCodingDefault,
		&i.RegisteredDeliveryDefault,
		&i.ReplaceIfPresentFlagDefault,
		&i.EsmClassDefault,
		&i.PriorityFlagDefault,
		&i.ValidityPeriodDefault,
		&i.SmDefaultMsgID,
		&i.EnquireLinkIntervalSec,
		&i.EnquireLinkMaxMissed,
		&i.BindTimeoutMs,
		&i.ResponseTimeoutMs,
		&i.WindowSize,
		&i.BindPoolSize,
		&i.ThroughputLimitPerSec,
		&i.TlsEnabled,
		&i.TlsConfigJson,
		&i.PriorityTier,
		&i.Status,
		&i.AutoReconnectEnabled,
		&i.ReconnectInitialDelayMs,
		&i.ReconnectMultiplier,
		&i.ReconnectMaxDelayMs,
		&i.ReconnectJitterPct,
		&i.ReconnectMaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnector = `-- name: DeleteConnector :execrows
DELETE FROM control_plane.smsc_connectors WHERE id = $1
`

func (q *Queries) DeleteConnector(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnector, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnector = `-- name: GetConnector :one
SELECT id, name, host, port, bind_type, system_id, password_hash, vendor_profile, system_type, interface_version, addr_ton, addr_npi, address_range, source_addr_ton, source_addr_npi, dest_addr_ton, dest_addr_npi, data_coding_default, registered_delivery_default, replace_if_present_flag_default, esm_class_default, priority_flag_default, validity_period_default, sm_default_msg_id, enquire_link_interval_sec, enquire_link_max_missed, bind_timeout_ms, response_timeout_ms, window_size, bind_pool_size, throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, status, auto_reconnect_enabled, reconnect_initial_delay_ms, reconnect_multiplier, reconnect_max_delay_ms, reconnect_jitter_pct, reconnect_max_attempts, created_at, updated_at FROM control_plane.smsc_connectors WHERE id = $1
`

func (q *Queries) GetConnector(ctx context.Context, id uuid.UUID) (ControlPlaneSmscConnector, error) {
	row := q.db.QueryRow(ctx, getConnector, id)
	var i ControlPlaneSmscConnector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.BindType,
		&i.SystemID,
		&i.PasswordHash,
		&i.VendorProfile,
		&i.SystemType,
		&i.InterfaceVersion,
		&i.AddrTon,
		&i.AddrNpi,
		&i.AddressRange,
		&i.SourceAddrTon,
		&i.SourceAddrNpi,
		&i.DestAddrTon,
		&i.DestAddrNpi,
		&i.DataCodingDefault,
		&i.RegisteredDeliveryDefault,
		&i.ReplaceIfPresentFlagDefault,
		&i.EsmClassDefault,
		&i.PriorityFlagDefault,
		&i.ValidityPeriodDefault,
		&i.SmDefaultMsgID,
		&i.EnquireLinkIntervalSec,
		&i.EnquireLinkMaxMissed,
		&i.BindTimeoutMs,
		&i.ResponseTimeoutMs,
		&i.WindowSize,
		&i.BindPoolSize,
		&i.ThroughputLimitPerSec,
		&i.TlsEnabled,
		&i.TlsConfigJson,
		&i.PriorityTier,
		&i.Status,
		&i.AutoReconnectEnabled,
		&i.ReconnectInitialDelayMs,
		&i.ReconnectMultiplier,
		&i.ReconnectMaxDelayMs,
		&i.ReconnectJitterPct,
		&i.ReconnectMaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectors = `-- name: ListConnectors :many
SELECT id, name, host, port, bind_type, system_id, password_hash, vendor_profile, system_type, interface_version, addr_ton, addr_npi, address_range, source_addr_ton, source_addr_npi, dest_addr_ton, dest_addr_npi, data_coding_default, registered_delivery_default, replace_if_present_flag_default, esm_class_default, priority_flag_default, validity_period_default, sm_default_msg_id, enquire_link_interval_sec, enquire_link_max_missed, bind_timeout_ms, response_timeout_ms, window_size, bind_pool_size, throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, status, auto_reconnect_enabled, reconnect_initial_delay_ms, reconnect_multiplier, reconnect_max_delay_ms, reconnect_jitter_pct, reconnect_max_attempts, created_at, updated_at FROM control_plane.smsc_connectors ORDER BY name
`

func (q *Queries) ListConnectors(ctx context.Context) ([]ControlPlaneSmscConnector, error) {
	rows, err := q.db.Query(ctx, listConnectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneSmscConnector{}
	for rows.Next() {
		var i ControlPlaneSmscConnector
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Host,
			&i.Port,
			&i.BindType,
			&i.SystemID,
			&i.PasswordHash,
			&i.VendorProfile,
			&i.SystemType,
			&i.InterfaceVersion,
			&i.AddrTon,
			&i.AddrNpi,
			&i.AddressRange,
			&i.SourceAddrTon,
			&i.SourceAddrNpi,
			&i.DestAddrTon,
			&i.DestAddrNpi,
			&i.DataCodingDefault,
			&i.RegisteredDeliveryDefault,
			&i.ReplaceIfPresentFlagDefault,
			&i.EsmClassDefault,
			&i.PriorityFlagDefault,
			&i.ValidityPeriodDefault,
			&i.SmDefaultMsgID,
			&i.EnquireLinkIntervalSec,
			&i.EnquireLinkMaxMissed,
			&i.BindTimeoutMs,
			&i.ResponseTimeoutMs,
			&i.WindowSize,
			&i.BindPoolSize,
			&i.ThroughputLimitPerSec,
			&i.TlsEnabled,
			&i.TlsConfigJson,
			&i.PriorityTier,
			&i.Status,
			&i.AutoReconnectEnabled,
			&i.ReconnectInitialDelayMs,
			&i.ReconnectMultiplier,
			&i.ReconnectMaxDelayMs,
			&i.ReconnectJitterPct,
			&i.ReconnectMaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnector = `-- name: UpdateConnector :one
UPDATE control_plane.smsc_connectors SET
    name                     = COALESCE($1, name),
    host                     = COALESCE($2, host),
    port                     = COALESCE($3, port),
    bind_type                = COALESCE($4, bind_type),
    system_id                = COALESCE($5, system_id),
    password_hash            = COALESCE($6, password_hash),
    vendor_profile           = COALESCE($7, vendor_profile),
    data_coding_default      = COALESCE($8, data_coding_default),
    window_size              = COALESCE($9, window_size),
    throughput_limit_per_sec = COALESCE($10, throughput_limit_per_sec),
    tls_enabled              = COALESCE($11, tls_enabled),
    tls_config_json          = COALESCE($12, tls_config_json),
    priority_tier            = COALESCE($13, priority_tier),
    status                   = COALESCE($14, status)
WHERE id = $15
RETURNING id, name, host, port, bind_type, system_id, password_hash, vendor_profile, system_type, interface_version, addr_ton, addr_npi, address_range, source_addr_ton, source_addr_npi, dest_addr_ton, dest_addr_npi, data_coding_default, registered_delivery_default, replace_if_present_flag_default, esm_class_default, priority_flag_default, validity_period_default, sm_default_msg_id, enquire_link_interval_sec, enquire_link_max_missed, bind_timeout_ms, response_timeout_ms, window_size, bind_pool_size, throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, status, auto_reconnect_enabled, reconnect_initial_delay_ms, reconnect_multiplier, reconnect_max_delay_ms, reconnect_jitter_pct, reconnect_max_attempts, created_at, updated_at
`

type UpdateConnectorParams struct {
	Name                  *string
	Host                  *string
	Port                  *int32
	BindType              *string
	SystemID              *string
	PasswordHash          *string
	VendorProfile         *string
	DataCodingDefault     *int16
	WindowSize            *int32
	ThroughputLimitPerSec *int32
	TlsEnabled            *bool
	TlsConfigJson         []byte
	PriorityTier          *int32
	Status                *string
	ID                    uuid.UUID
}

func (q *Queries) UpdateConnector(ctx context.Context, arg UpdateConnectorParams) (ControlPlaneSmscConnector, error) {
	row := q.db.QueryRow(ctx, updateConnector,
		arg.Name,
		arg.Host,
		arg.Port,
		arg.BindType,
		arg.SystemID,
		arg.PasswordHash,
		arg.VendorProfile,
		arg.DataCodingDefault,
		arg.WindowSize,
		arg.ThroughputLimitPerSec,
		arg.TlsEnabled,
		arg.TlsConfigJson,
		arg.PriorityTier,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneSmscConnector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.BindType,
		&i.SystemID,
		&i.PasswordHash,
		&i.VendorProfile,
		&i.SystemType,
		&i.InterfaceVersion,
		&i.AddrTon,
		&i.AddrNpi,
		&i.AddressRange,
		&i.SourceAddrTon,
		&i.SourceAddrNpi,
		&i.DestAddrTon,
		&i.DestAddrNpi,
		&i.DataCodingDefault,
		&i.RegisteredDeliveryDefault,
		&i.ReplaceIfPresentFlagDefault,
		&i.EsmClassDefault,
		&i.PriorityFlagDefault,
		&i.ValidityPeriodDefault,
		&i.SmDefaultMsgID,
		&i.EnquireLinkIntervalSec,
		&i.EnquireLinkMaxMissed,
		&i.BindTimeoutMs,
		&i.ResponseTimeoutMs,
		&i.WindowSize,
		&i.BindPoolSize,
		&i.ThroughputLimitPerSec,
		&i.TlsEnabled,
		&i.TlsConfigJson,
		&i.PriorityTier,
		&i.Status,
		&i.AutoReconnectEnabled,
		&i.ReconnectInitialDelayMs,
		&i.ReconnectMultiplier,
		&i.ReconnectMaxDelayMs,
		&i.ReconnectJitterPct,
		&i.ReconnectMaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectorBindPool = `-- name: UpdateConnectorBindPool :one
UPDATE control_plane.smsc_connectors SET bind_pool_size = $1 WHERE id = $2
RETURNING id, name, host, port, bind_type, system_id, password_hash, vendor_profile, system_type, interface_version, addr_ton, addr_npi, address_range, source_addr_ton, source_addr_npi, dest_addr_ton, dest_addr_npi, data_coding_default, registered_delivery_default, replace_if_present_flag_default, esm_class_default, priority_flag_default, validity_period_default, sm_default_msg_id, enquire_link_interval_sec, enquire_link_max_missed, bind_timeout_ms, response_timeout_ms, window_size, bind_pool_size, throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, status, auto_reconnect_enabled, reconnect_initial_delay_ms, reconnect_multiplier, reconnect_max_delay_ms, reconnect_jitter_pct, reconnect_max_attempts, created_at, updated_at
`

type UpdateConnectorBindPoolParams struct {
	BindPoolSize int32
	ID           uuid.UUID
}

func (q *Queries) UpdateConnectorBindPool(ctx context.Context, arg UpdateConnectorBindPoolParams) (ControlPlaneSmscConnector, error) {
	row := q.db.QueryRow(ctx, updateConnectorBindPool, arg.BindPoolSize, arg.ID)
	var i ControlPlaneSmscConnector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.BindType,
		&i.SystemID,
		&i.PasswordHash,
		&i.VendorProfile,
		&i.SystemType,
		&i.InterfaceVersion,
		&i.AddrTon,
		&i.AddrNpi,
		&i.AddressRange,
		&i.SourceAddrTon,
		&i.SourceAddrNpi,
		&i.DestAddrTon,
		&i.DestAddrNpi,
		&i.DataCodingDefault,
		&i.RegisteredDeliveryDefault,
		&i.ReplaceIfPresentFlagDefault,
		&i.EsmClassDefault,
		&i.PriorityFlagDefault,
		&i.ValidityPeriodDefault,
		&i.SmDefaultMsgID,
		&i.EnquireLinkIntervalSec,
		&i.EnquireLinkMaxMissed,
		&i.BindTimeoutMs,
		&i.ResponseTimeoutMs,
		&i.WindowSize,
		&i.BindPoolSize,
		&i.ThroughputLimitPerSec,
		&i.TlsEnabled,
		&i.TlsConfigJson,
		&i.PriorityTier,
		&i.Status,
		&i.AutoReconnectEnabled,
		&i.ReconnectInitialDelayMs,
		&i.ReconnectMultiplier,
		&i.ReconnectMaxDelayMs,
		&i.ReconnectJitterPct,
		&i.ReconnectMaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectorReconnectPolicy = `-- name: UpdateConnectorReconnectPolicy :one
UPDATE control_plane.smsc_connectors SET
    auto_reconnect_enabled     = $1,
    reconnect_initial_delay_ms = COALESCE($2, reconnect_initial_delay_ms),
    reconnect_multiplier       = COALESCE($3, reconnect_multiplier),
    reconnect_max_delay_ms     = COALESCE($4, reconnect_max_delay_ms),
    reconnect_jitter_pct       = COALESCE($5, reconnect_jitter_pct),
    reconnect_max_attempts     = COALESCE($6, reconnect_max_attempts)
WHERE id = $7
RETURNING id, name, host, port, bind_type, system_id, password_hash, vendor_profile, system_type, interface_version, addr_ton, addr_npi, address_range, source_addr_ton, source_addr_npi, dest_addr_ton, dest_addr_npi, data_coding_default, registered_delivery_default, replace_if_present_flag_default, esm_class_default, priority_flag_default, validity_period_default, sm_default_msg_id, enquire_link_interval_sec, enquire_link_max_missed, bind_timeout_ms, response_timeout_ms, window_size, bind_pool_size, throughput_limit_per_sec, tls_enabled, tls_config_json, priority_tier, status, auto_reconnect_enabled, reconnect_initial_delay_ms, reconnect_multiplier, reconnect_max_delay_ms, reconnect_jitter_pct, reconnect_max_attempts, created_at, updated_at
`

type UpdateConnectorReconnectPolicyParams struct {
	AutoReconnectEnabled    bool
	ReconnectInitialDelayMs *int32
	ReconnectMultiplier     pgtype.Numeric
	ReconnectMaxDelayMs     *int32
	ReconnectJitterPct      *int32
	ReconnectMaxAttempts    *int32
	ID                      uuid.UUID
}

func (q *Queries) UpdateConnectorReconnectPolicy(ctx context.Context, arg UpdateConnectorReconnectPolicyParams) (ControlPlaneSmscConnector, error) {
	row := q.db.QueryRow(ctx, updateConnectorReconnectPolicy,
		arg.AutoReconnectEnabled,
		arg.ReconnectInitialDelayMs,
		arg.ReconnectMultiplier,
		arg.ReconnectMaxDelayMs,
		arg.ReconnectJitterPct,
		arg.ReconnectMaxAttempts,
		arg.ID,
	)
	var i ControlPlaneSmscConnector
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Host,
		&i.Port,
		&i.BindType,
		&i.SystemID,
		&i.PasswordHash,
		&i.VendorProfile,
		&i.SystemType,
		&i.InterfaceVersion,
		&i.AddrTon,
		&i.AddrNpi,
		&i.AddressRange,
		&i.SourceAddrTon,
		&i.SourceAddrNpi,
		&i.DestAddrTon,
		&i.DestAddrNpi,
		&i.DataCodingDefault,
		&i.RegisteredDeliveryDefault,
		&i.ReplaceIfPresentFlagDefault,
		&i.EsmClassDefault,
		&i.PriorityFlagDefault,
		&i.ValidityPeriodDefault,
		&i.SmDefaultMsgID,
		&i.EnquireLinkIntervalSec,
		&i.EnquireLinkMaxMissed,
		&i.BindTimeoutMs,
		&i.ResponseTimeoutMs,
		&i.WindowSize,
		&i.BindPoolSize,
		&i.ThroughputLimitPerSec,
		&i.TlsEnabled,
		&i.TlsConfigJson,
		&i.PriorityTier,
		&i.Status,
		&i.AutoReconnectEnabled,
		&i.ReconnectInitialDelayMs,
		&i.ReconnectMultiplier,
		&i.ReconnectMaxDelayMs,
		&i.ReconnectJitterPct,
		&i.ReconnectMaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
