// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_keys.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const clearCustomerContentKey = `-- name: ClearCustomerContentKey :exec
UPDATE control_plane.customers SET content_key_id = NULL WHERE id = $1
`

// Drop the customer's pointer to its (now destroyed) active key; the next send get-or-creates a fresh one.
func (q *Queries) ClearCustomerContentKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCustomerContentKey, id)
	return err
}

const destroyContentKeysByCustomer = `-- name: DestroyContentKeysByCustomer :execrows
UPDATE control_plane.content_keys
SET status = 'destroyed', destroyed_at = now(), wrapped_key = ''::bytea
WHERE customer_id = $1 AND status != 'destroyed'
`

// Crypto-shred every non-destroyed key of a customer: mark it destroyed and ERASE the wrapped key so the
// data key can never be recovered — even by the KMS. The content_ciphertext in the CDR stays in place but
// becomes permanently undecryptable, no CDR rewrite. Idempotent: an already-destroyed key is skipped.
func (q *Queries) DestroyContentKeysByCustomer(ctx context.Context, customerID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, destroyContentKeysByCustomer, customerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveContentKey = `-- name: GetActiveContentKey :one
SELECT id, customer_id, wrapped_key, kms_key_ref, status, created_at, retired_at, destroyed_at FROM control_plane.content_keys
WHERE customer_id = $1 AND status = 'active'
`

// The customer's current active content key (at most one, guaranteed by content_keys_one_active_idx).
func (q *Queries) GetActiveContentKey(ctx context.Context, customerID uuid.UUID) (ControlPlaneContentKey, error) {
	row := q.db.QueryRow(ctx, getActiveContentKey, customerID)
	var i ControlPlaneContentKey
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WrappedKey,
		&i.KmsKeyRef,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DestroyedAt,
	)
	return i, err
}

const getContentKeyByID = `-- name: GetContentKeyByID :one
SELECT id, customer_id, wrapped_key, kms_key_ref, status, created_at, retired_at, destroyed_at FROM control_plane.content_keys WHERE id = $1
`

func (q *Queries) GetContentKeyByID(ctx context.Context, id uuid.UUID) (ControlPlaneContentKey, error) {
	row := q.db.QueryRow(ctx, getContentKeyByID, id)
	var i ControlPlaneContentKey
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WrappedKey,
		&i.KmsKeyRef,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DestroyedAt,
	)
	return i, err
}

const insertContentKey = `-- name: InsertContentKey :one
INSERT INTO control_plane.content_keys (customer_id, wrapped_key, kms_key_ref)
VALUES ($1, $2, $3)
RETURNING id, customer_id, wrapped_key, kms_key_ref, status, created_at, retired_at, destroyed_at
`

type InsertContentKeyParams struct {
	CustomerID uuid.UUID
	WrappedKey []byte
	KmsKeyRef  string
}

// Insert a new active key. The partial unique index rejects a second active key for the same customer.
func (q *Queries) InsertContentKey(ctx context.Context, arg InsertContentKeyParams) (ControlPlaneContentKey, error) {
	row := q.db.QueryRow(ctx, insertContentKey, arg.CustomerID, arg.WrappedKey, arg.KmsKeyRef)
	var i ControlPlaneContentKey
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.WrappedKey,
		&i.KmsKeyRef,
		&i.Status,
		&i.CreatedAt,
		&i.RetiredAt,
		&i.DestroyedAt,
	)
	return i, err
}

const listContentKeysByCustomer = `-- name: ListContentKeysByCustomer :many
SELECT id, customer_id, wrapped_key, kms_key_ref, status, created_at, retired_at, destroyed_at FROM control_plane.content_keys
WHERE customer_id = $1
ORDER BY created_at DESC, id DESC
`

// Every key of a customer, newest first — active plus the retired history still needed to decrypt old CDRs.
func (q *Queries) ListContentKeysByCustomer(ctx context.Context, customerID uuid.UUID) ([]ControlPlaneContentKey, error) {
	rows, err := q.db.Query(ctx, listContentKeysByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneContentKey{}
	for rows.Next() {
		var i ControlPlaneContentKey
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.WrappedKey,
			&i.KmsKeyRef,
			&i.Status,
			&i.CreatedAt,
			&i.RetiredAt,
			&i.DestroyedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomerForContentKey = `-- name: LockCustomerForContentKey :one
SELECT id FROM control_plane.customers WHERE id = $1 FOR UPDATE
`

// Serialize concurrent GetOrCreate/Rotate on a customer by locking its row for the transaction.
func (q *Queries) LockCustomerForContentKey(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCustomerForContentKey, id)
	err := row.Scan(&id)
	return id, err
}

const retireActiveContentKey = `-- name: RetireActiveContentKey :execrows
UPDATE control_plane.content_keys
SET status = 'retired', retired_at = now()
WHERE customer_id = $1 AND status = 'active'
`

// Demote the customer's active key to retired (it stays decryptable). Zero rows when there is no active key.
func (q *Queries) RetireActiveContentKey(ctx context.Context, customerID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, retireActiveContentKey, customerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCustomerContentKey = `-- name: SetCustomerContentKey :execrows
UPDATE control_plane.customers SET content_key_id = $2 WHERE id = $1
`

type SetCustomerContentKeyParams struct {
	ID           uuid.UUID
	ContentKeyID *uuid.UUID
}

// Point the customer at its current active content key (control_plane.customers.content_key_id).
func (q *Queries) SetCustomerContentKey(ctx context.Context, arg SetCustomerContentKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setCustomerContentKey, arg.ID, arg.ContentKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
