// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content_access_audit.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const insertContentAccess = `-- name: InsertContentAccess :exec
INSERT INTO control_plane.content_access_audit (operator, message_id, customer_id, outcome)
VALUES ($1, $2, $3, $4)
`

type InsertContentAccessParams struct {
	Operator   string
	MessageID  uuid.UUID
	CustomerID *uuid.UUID
	Outcome    string
}

// Record one content:read access to a message body (fact only, never the plaintext).
func (q *Queries) InsertContentAccess(ctx context.Context, arg InsertContentAccessParams) error {
	_, err := q.db.Exec(ctx, insertContentAccess,
		arg.Operator,
		arg.MessageID,
		arg.CustomerID,
		arg.Outcome,
	)
	return err
}
