// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForCopyBalanceDeltas implements pgx.CopyFromSource.
type iteratorForCopyBalanceDeltas struct {
	rows                 []CopyBalanceDeltasParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyBalanceDeltas) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyBalanceDeltas) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OwnerType,
		r.rows[0].OwnerID,
		r.rows[0].Direction,
		r.rows[0].Credits,
	}, nil
}

func (r iteratorForCopyBalanceDeltas) Err() error {
	return nil
}

func (q *Queries) CopyBalanceDeltas(ctx context.Context, arg []CopyBalanceDeltasParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"control_plane", "balance_deltas"}, []string{"owner_type", "owner_id", "direction", "credits"}, &iteratorForCopyBalanceDeltas{rows: arg})
}

// iteratorForCopyLedgerEntries implements pgx.CopyFromSource.
type iteratorForCopyLedgerEntries struct {
	rows                 []CopyLedgerEntriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyLedgerEntries) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyLedgerEntries) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OwnerType,
		r.rows[0].OwnerID,
		r.rows[0].Direction,
		r.rows[0].CustomerID,
		r.rows[0].AccountID,
		r.rows[0].MessageID,
		r.rows[0].EntryType,
		r.rows[0].Credits,
		r.rows[0].BalanceAfter,
		r.rows[0].Reference,
	}, nil
}

func (r iteratorForCopyLedgerEntries) Err() error {
	return nil
}

// COPY rather than a multi-row INSERT: the nullable account_id and reference do not ride typed unnest arrays.
func (q *Queries) CopyLedgerEntries(ctx context.Context, arg []CopyLedgerEntriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"control_plane", "billing_ledger"}, []string{"owner_type", "owner_id", "direction", "customer_id", "account_id", "message_id", "entry_type", "credits", "balance_after", "reference"}, &iteratorForCopyLedgerEntries{rows: arg})
}
