// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO control_plane.credentials (account_id, type, system_id, password_hash, api_key_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, type, system_id, password_hash, api_key_hash, status, last_used_at, previous_secret_hash, grace_expires_at, created_at, rotated_at
`

type CreateCredentialParams struct {
	AccountID    uuid.UUID
	Type         string
	SystemID     *string
	PasswordHash *string
	ApiKeyHash   *string
}

// The hashes are computed by internal/credential before this runs. The shape (system_id +
// password_hash for a bind, api_key_hash for a key) is enforced by credentials_shape_ck; a second
// credential of the same type on the account violates credentials_one_per_type_uq -> 409.
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (ControlPlaneCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.AccountID,
		arg.Type,
		arg.SystemID,
		arg.PasswordHash,
		arg.ApiKeyHash,
	)
	var i ControlPlaneCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.SystemID,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.Status,
		&i.LastUsedAt,
		&i.PreviousSecretHash,
		&i.GraceExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getAPIKeyPrincipal = `-- name: GetAPIKeyPrincipal :one
SELECT
    a.id          AS account_id,
    a.customer_id AS customer_id,
    a.status      AS account_status,
    a.rest_enabled AS rest_enabled,
    c.status      AS customer_status
FROM control_plane.credentials cr
JOIN control_plane.smpp_accounts a ON a.id = cr.account_id
JOIN control_plane.customers c ON c.id = a.customer_id
WHERE cr.type = 'api_key'
  AND cr.status = 'active'
  AND (
        cr.api_key_hash = $1
     OR (cr.previous_secret_hash = $1
         AND cr.grace_expires_at IS NOT NULL
         AND cr.grace_expires_at > now())
  )
`

type GetAPIKeyPrincipalRow struct {
	AccountID      uuid.UUID
	CustomerID     uuid.UUID
	AccountStatus  string
	RestEnabled    bool
	CustomerStatus string
}

// REST authentication lookup (§1.9): the presented key is SHA-256 hashed by internal/credential,
// then found by that hash on the single api_key credential. The rotation grace window is honoured —
// the previous secret keeps working until grace_expires_at. Only the credential status is gated
// here (a revoked key is simply invalid); rest_enabled and the account/customer statuses are
// RETURNED, not filtered, so the verifier can answer with the right code (401 vs 403) rather than a
// blanket "not found".
func (q *Queries) GetAPIKeyPrincipal(ctx context.Context, apiKeyHash *string) (GetAPIKeyPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyPrincipal, apiKeyHash)
	var i GetAPIKeyPrincipalRow
	err := row.Scan(
		&i.AccountID,
		&i.CustomerID,
		&i.AccountStatus,
		&i.RestEnabled,
		&i.CustomerStatus,
	)
	return i, err
}

const getBindPrincipal = `-- name: GetBindPrincipal :one
SELECT
    cr.password_hash     AS password_hash,
    cr.status            AS credential_status,
    a.id                 AS account_id,
    a.smpp_enabled       AS smpp_enabled,
    a.allowed_bind_types AS allowed_bind_types,
    a.max_sessions       AS max_sessions,
    a.status             AS account_status,
    c.status             AS customer_status
FROM control_plane.credentials cr
JOIN control_plane.smpp_accounts a ON a.id = cr.account_id
JOIN control_plane.customers c ON c.id = a.customer_id
WHERE cr.type = 'smpp_bind'
  AND cr.status <> 'revoked'
  AND cr.system_id = $1
`

type GetBindPrincipalRow struct {
	PasswordHash     *string
	CredentialStatus string
	AccountID        uuid.UUID
	SmppEnabled      bool
	AllowedBindTypes string
	MaxSessions      int32
	AccountStatus    string
	CustomerStatus   string
}

// SMPP bind authentication lookup (§1.9, invariant d): the presented system_id resolves the single
// live bind credential — the partial unique index credentials_system_id_uq covers exactly
// type = 'smpp_bind' AND status <> 'revoked', so this WHERE rides that index and can match at most one
// row. The argon2id password_hash is verified in Go by internal/credential (constant time), never in
// SQL. As with GetAPIKeyPrincipal the credential/channel/account/customer statuses are RETURNED, not
// filtered, so the caller answers with the right SMPP command_status (ESME_RINVPASWD vs ESME_RBINDFAIL)
// rather than a blanket "not found". Rotation grace (previous_secret_hash/grace_expires_at) lands in
// step-027; step-024 verifies only the current password_hash.
func (q *Queries) GetBindPrincipal(ctx context.Context, systemID *string) (GetBindPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getBindPrincipal, systemID)
	var i GetBindPrincipalRow
	err := row.Scan(
		&i.PasswordHash,
		&i.CredentialStatus,
		&i.AccountID,
		&i.SmppEnabled,
		&i.AllowedBindTypes,
		&i.MaxSessions,
		&i.AccountStatus,
		&i.CustomerStatus,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT id, account_id, type, system_id, password_hash, api_key_hash, status, last_used_at, previous_secret_hash, grace_expires_at, created_at, rotated_at FROM control_plane.credentials WHERE account_id = $1 AND id = $2
`

type GetCredentialParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (ControlPlaneCredential, error) {
	row := q.db.QueryRow(ctx, getCredential, arg.AccountID, arg.ID)
	var i ControlPlaneCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.SystemID,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.Status,
		&i.LastUsedAt,
		&i.PreviousSecretHash,
		&i.GraceExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const listCredentialsByAccount = `-- name: ListCredentialsByAccount :many
SELECT id, account_id, type, system_id, password_hash, api_key_hash, status, last_used_at, previous_secret_hash, grace_expires_at, created_at, rotated_at FROM control_plane.credentials WHERE account_id = $1 ORDER BY type
`

func (q *Queries) ListCredentialsByAccount(ctx context.Context, accountID uuid.UUID) ([]ControlPlaneCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneCredential{}
	for rows.Next() {
		var i ControlPlaneCredential
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.SystemID,
			&i.PasswordHash,
			&i.ApiKeyHash,
			&i.Status,
			&i.LastUsedAt,
			&i.PreviousSecretHash,
			&i.GraceExpiresAt,
			&i.CreatedAt,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateCredential = `-- name: RotateCredential :one
UPDATE control_plane.credentials SET
    password_hash = CASE WHEN type = 'smpp_bind' THEN $1 ELSE password_hash END,
    api_key_hash  = CASE WHEN type = 'api_key'   THEN $1 ELSE api_key_hash END,
    previous_secret_hash = CASE
        WHEN $2::int IS NOT NULL THEN COALESCE(password_hash, api_key_hash)
        ELSE NULL END,
    grace_expires_at = CASE
        WHEN $2::int IS NOT NULL
            THEN now() + make_interval(secs => $2::int)
        ELSE NULL END,
    rotated_at = now()
WHERE account_id = $3 AND id = $4
RETURNING id, account_id, type, system_id, password_hash, api_key_hash, status, last_used_at, previous_secret_hash, grace_expires_at, created_at, rotated_at
`

type RotateCredentialParams struct {
	NewHash      *string
	GraceSeconds *int32
	AccountID    uuid.UUID
	ID           uuid.UUID
}

// Writes the freshly hashed secret into the column that matches the credential's type. When a grace
// period is given, the OLD hash (visible on the right-hand side of the UPDATE) is preserved in
// previous_secret_hash and grace_expires_at is set now()+grace, so the previous secret keeps working
// in parallel until it expires; a null grace is an immediate cutover.
func (q *Queries) RotateCredential(ctx context.Context, arg RotateCredentialParams) (ControlPlaneCredential, error) {
	row := q.db.QueryRow(ctx, rotateCredential,
		arg.NewHash,
		arg.GraceSeconds,
		arg.AccountID,
		arg.ID,
	)
	var i ControlPlaneCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.SystemID,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.Status,
		&i.LastUsedAt,
		&i.PreviousSecretHash,
		&i.GraceExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const setCredentialStatus = `-- name: SetCredentialStatus :one
UPDATE control_plane.credentials SET status = $1
WHERE account_id = $2 AND id = $3
RETURNING id, account_id, type, system_id, password_hash, api_key_hash, status, last_used_at, previous_secret_hash, grace_expires_at, created_at, rotated_at
`

type SetCredentialStatusParams struct {
	Status    string
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SetCredentialStatus(ctx context.Context, arg SetCredentialStatusParams) (ControlPlaneCredential, error) {
	row := q.db.QueryRow(ctx, setCredentialStatus, arg.Status, arg.AccountID, arg.ID)
	var i ControlPlaneCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.SystemID,
		&i.PasswordHash,
		&i.ApiKeyHash,
		&i.Status,
		&i.LastUsedAt,
		&i.PreviousSecretHash,
		&i.GraceExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}
