// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_groups.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCustomerGroup = `-- name: CreateCustomerGroup :one
INSERT INTO control_plane.customer_groups (name, description)
VALUES ($1, $2)
RETURNING id, name, description, status, created_by, created_at, updated_at
`

type CreateCustomerGroupParams struct {
	Name        string
	Description *string
}

// status falls back to the DDL default ('active'), and created_by stays NULL until real operator
// auth lands (step-310) — the column exists to satisfy the FK to the dashboard.operators stub.
func (q *Queries) CreateCustomerGroup(ctx context.Context, arg CreateCustomerGroupParams) (ControlPlaneCustomerGroup, error) {
	row := q.db.QueryRow(ctx, createCustomerGroup, arg.Name, arg.Description)
	var i ControlPlaneCustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomerGroup = `-- name: DeleteCustomerGroup :execrows
DELETE FROM control_plane.customer_groups WHERE id = $1
`

// Non-destructive by schema (§6.17): customers.group_id references this table ON DELETE SET NULL,
// so deleting a group detaches its customers and deletes none of them. There is deliberately no
// application-side cascade to contradict it.
func (q *Queries) DeleteCustomerGroup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomerGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomerGroup = `-- name: GetCustomerGroup :one
SELECT id, name, description, status, created_by, created_at, updated_at FROM control_plane.customer_groups WHERE id = $1
`

func (q *Queries) GetCustomerGroup(ctx context.Context, id uuid.UUID) (ControlPlaneCustomerGroup, error) {
	row := q.db.QueryRow(ctx, getCustomerGroup, id)
	var i ControlPlaneCustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerGroups = `-- name: ListCustomerGroups :many
SELECT id, name, description, status, created_by, created_at, updated_at FROM control_plane.customer_groups
WHERE ($1::text IS NULL OR status = $1)
ORDER BY name
`

// Not paginated: the contract returns a bare array. A group count is an operator-scale number —
// one row per commercial segment — not a subscriber-scale one, so there is no keyset here.
func (q *Queries) ListCustomerGroups(ctx context.Context, status *string) ([]ControlPlaneCustomerGroup, error) {
	rows, err := q.db.Query(ctx, listCustomerGroups, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneCustomerGroup{}
	for rows.Next() {
		var i ControlPlaneCustomerGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerGroup = `-- name: UpdateCustomerGroup :one
UPDATE control_plane.customer_groups SET
    name        = COALESCE($1, name),
    description = COALESCE($2, description),
    status      = COALESCE($3, status)
WHERE id = $4
RETURNING id, name, description, status, created_by, created_at, updated_at
`

type UpdateCustomerGroupParams struct {
	Name        *string
	Description *string
	Status      *string
	ID          uuid.UUID
}

// Partial update: a NULL argument leaves its column unchanged (COALESCE). updated_at is not set
// here — the customer_groups_touch trigger does it. Consequence of COALESCE: description cannot be
// cleared back to NULL through this path, although the contract marks it nullable
// (debts/patch-null-ne-peut-pas-effacer-un-champ.md).
func (q *Queries) UpdateCustomerGroup(ctx context.Context, arg UpdateCustomerGroupParams) (ControlPlaneCustomerGroup, error) {
	row := q.db.QueryRow(ctx, updateCustomerGroup,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneCustomerGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
