// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO control_plane.customers (
    name, group_id, rate_plan_id, billing_enabled, billing_mode,
    overdraft_enabled, overdraft_limit, balance_scope, mo_billing_floor,
    content_storage, content_retention_days
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    COALESCE($8::text, 'customer'),
    $9,
    COALESCE($10::text, 'inherit'),
    $11
)
RETURNING id, name, status, group_id, rate_plan_id, billing_enabled, billing_mode, overdraft_enabled, overdraft_limit, balance_scope, mo_billing_floor, content_storage, content_retention_days, content_key_id, created_at, updated_at
`

type CreateCustomerParams struct {
	Name                 string
	GroupID              *uuid.UUID
	RatePlanID           *uuid.UUID
	BillingEnabled       bool
	BillingMode          *string
	OverdraftEnabled     bool
	OverdraftLimit       *int32
	BalanceScope         *string
	MoBillingFloor       *int32
	ContentStorage       *string
	ContentRetentionDays *int32
}

// Optional columns fall back to their DDL defaults via COALESCE, so the schema stays the one
// authority on what a defaulted value is.
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (ControlPlaneCustomer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.GroupID,
		arg.RatePlanID,
		arg.BillingEnabled,
		arg.BillingMode,
		arg.OverdraftEnabled,
		arg.OverdraftLimit,
		arg.BalanceScope,
		arg.MoBillingFloor,
		arg.ContentStorage,
		arg.ContentRetentionDays,
	)
	var i ControlPlaneCustomer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.GroupID,
		&i.RatePlanID,
		&i.BillingEnabled,
		&i.BillingMode,
		&i.OverdraftEnabled,
		&i.OverdraftLimit,
		&i.BalanceScope,
		&i.MoBillingFloor,
		&i.ContentStorage,
		&i.ContentRetentionDays,
		&i.ContentKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :execrows
DELETE FROM control_plane.customers WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, status, group_id, rate_plan_id, billing_enabled, billing_mode, overdraft_enabled, overdraft_limit, balance_scope, mo_billing_floor, content_storage, content_retention_days, content_key_id, created_at, updated_at FROM control_plane.customers WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (ControlPlaneCustomer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i ControlPlaneCustomer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.GroupID,
		&i.RatePlanID,
		&i.BillingEnabled,
		&i.BillingMode,
		&i.OverdraftEnabled,
		&i.OverdraftLimit,
		&i.BalanceScope,
		&i.MoBillingFloor,
		&i.ContentStorage,
		&i.ContentRetentionDays,
		&i.ContentKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, status, group_id, rate_plan_id, billing_enabled, billing_mode, overdraft_enabled, overdraft_limit, balance_scope, mo_billing_floor, content_storage, content_retention_days, content_key_id, created_at, updated_at FROM control_plane.customers
WHERE ($1::uuid IS NULL OR group_id = $1)
  AND ($2::text  IS NULL OR status   = $2)
  AND ($3::uuid   IS NULL OR id       > $3)
ORDER BY id
LIMIT $4
`

type ListCustomersParams struct {
	GroupID *uuid.UUID
	Status  *string
	After   *uuid.UUID
	Lim     int32
}

// Keyset pagination on the UUIDv7 primary key (time-ordered). The caller asks for limit+1 rows to
// learn whether a further page exists.
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]ControlPlaneCustomer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.GroupID,
		arg.Status,
		arg.After,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneCustomer{}
	for rows.Next() {
		var i ControlPlaneCustomer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.GroupID,
			&i.RatePlanID,
			&i.BillingEnabled,
			&i.BillingMode,
			&i.OverdraftEnabled,
			&i.OverdraftLimit,
			&i.BalanceScope,
			&i.MoBillingFloor,
			&i.ContentStorage,
			&i.ContentRetentionDays,
			&i.ContentKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suspendCustomer = `-- name: SuspendCustomer :one
UPDATE control_plane.customers SET status = 'suspended' WHERE id = $1 RETURNING id, name, status, group_id, rate_plan_id, billing_enabled, billing_mode, overdraft_enabled, overdraft_limit, balance_scope, mo_billing_floor, content_storage, content_retention_days, content_key_id, created_at, updated_at
`

func (q *Queries) SuspendCustomer(ctx context.Context, id uuid.UUID) (ControlPlaneCustomer, error) {
	row := q.db.QueryRow(ctx, suspendCustomer, id)
	var i ControlPlaneCustomer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.GroupID,
		&i.RatePlanID,
		&i.BillingEnabled,
		&i.BillingMode,
		&i.OverdraftEnabled,
		&i.OverdraftLimit,
		&i.BalanceScope,
		&i.MoBillingFloor,
		&i.ContentStorage,
		&i.ContentRetentionDays,
		&i.ContentKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const suspendCustomerAccounts = `-- name: SuspendCustomerAccounts :exec
UPDATE control_plane.smpp_accounts SET status = 'suspended' WHERE customer_id = $1
`

func (q *Queries) SuspendCustomerAccounts(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, suspendCustomerAccounts, customerID)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE control_plane.customers SET
    name                   = COALESCE($1, name),
    status                 = COALESCE($2, status),
    rate_plan_id           = COALESCE($3, rate_plan_id),
    billing_enabled        = COALESCE($4, billing_enabled),
    billing_mode           = COALESCE($5, billing_mode),
    overdraft_enabled      = COALESCE($6, overdraft_enabled),
    overdraft_limit        = COALESCE($7, overdraft_limit),
    mo_billing_floor       = COALESCE($8, mo_billing_floor),
    content_storage        = COALESCE($9, content_storage),
    content_retention_days = COALESCE($10, content_retention_days)
WHERE id = $11
RETURNING id, name, status, group_id, rate_plan_id, billing_enabled, billing_mode, overdraft_enabled, overdraft_limit, balance_scope, mo_billing_floor, content_storage, content_retention_days, content_key_id, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name                 *string
	Status               *string
	RatePlanID           *uuid.UUID
	BillingEnabled       *bool
	BillingMode          *string
	OverdraftEnabled     *bool
	OverdraftLimit       *int32
	MoBillingFloor       *int32
	ContentStorage       *string
	ContentRetentionDays *int32
	ID                   uuid.UUID
}

// Partial update: a NULL argument leaves its column unchanged (COALESCE). group_id is not here —
// group membership has its own endpoint.
func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (ControlPlaneCustomer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.Status,
		arg.RatePlanID,
		arg.BillingEnabled,
		arg.BillingMode,
		arg.OverdraftEnabled,
		arg.OverdraftLimit,
		arg.MoBillingFloor,
		arg.ContentStorage,
		arg.ContentRetentionDays,
		arg.ID,
	)
	var i ControlPlaneCustomer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.GroupID,
		&i.RatePlanID,
		&i.BillingEnabled,
		&i.BillingMode,
		&i.OverdraftEnabled,
		&i.OverdraftLimit,
		&i.BalanceScope,
		&i.MoBillingFloor,
		&i.ContentStorage,
		&i.ContentRetentionDays,
		&i.ContentKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
