// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exact_routes.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExactRoute = `-- name: DeleteExactRoute :execrows
DELETE FROM control_plane.exact_routes WHERE msisdn = $1
`

func (q *Queries) DeleteExactRoute(ctx context.Context, msisdn string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExactRoute, msisdn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExactRoute = `-- name: GetExactRoute :one
SELECT msisdn, target_type, target_id, source, imported_at, updated_at
FROM control_plane.exact_routes
WHERE msisdn = $1
`

// The exact route for one MSISDN, if any. A missing row means "no exact override" — the caller falls
// back to normal route resolution, not an error.
func (q *Queries) GetExactRoute(ctx context.Context, msisdn string) (ControlPlaneExactRoute, error) {
	row := q.db.QueryRow(ctx, getExactRoute, msisdn)
	var i ControlPlaneExactRoute
	err := row.Scan(
		&i.Msisdn,
		&i.TargetType,
		&i.TargetID,
		&i.Source,
		&i.ImportedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExactRoutes = `-- name: ListExactRoutes :many
SELECT msisdn, target_type, target_id, source, imported_at, updated_at
FROM control_plane.exact_routes
WHERE msisdn > $1
ORDER BY msisdn
LIMIT $2
`

type ListExactRoutesParams struct {
	After string
	Lim   int32
}

// A page of exact routes in msisdn order, keyset-paginated: pass the last msisdn of the previous page
// as @after (the empty string for the first page, since every msisdn sorts after it). @lim is the page
// size; callers request size+1 to detect a further page.
func (q *Queries) ListExactRoutes(ctx context.Context, arg ListExactRoutesParams) ([]ControlPlaneExactRoute, error) {
	rows, err := q.db.Query(ctx, listExactRoutes, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneExactRoute{}
	for rows.Next() {
		var i ControlPlaneExactRoute
		if err := rows.Scan(
			&i.Msisdn,
			&i.TargetType,
			&i.TargetID,
			&i.Source,
			&i.ImportedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExactRoute = `-- name: UpsertExactRoute :one
INSERT INTO control_plane.exact_routes (msisdn, target_type, target_id, source, imported_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (msisdn) DO UPDATE SET
    target_type = EXCLUDED.target_type,
    target_id   = EXCLUDED.target_id,
    source      = EXCLUDED.source,
    imported_at = EXCLUDED.imported_at,
    updated_at  = now()
RETURNING msisdn, target_type, target_id, source, imported_at, updated_at
`

type UpsertExactRouteParams struct {
	Msisdn     string
	TargetType string
	TargetID   uuid.UUID
	Source     string
	ImportedAt pgtype.Timestamptz
}

// Idempotent by msisdn (the primary key): a repeated upsert of the same number overwrites the target,
// source and imported_at, and refreshes updated_at. This is the single-row create/update path.
func (q *Queries) UpsertExactRoute(ctx context.Context, arg UpsertExactRouteParams) (ControlPlaneExactRoute, error) {
	row := q.db.QueryRow(ctx, upsertExactRoute,
		arg.Msisdn,
		arg.TargetType,
		arg.TargetID,
		arg.Source,
		arg.ImportedAt,
	)
	var i ControlPlaneExactRoute
	err := row.Scan(
		&i.Msisdn,
		&i.TargetType,
		&i.TargetID,
		&i.Source,
		&i.ImportedAt,
		&i.UpdatedAt,
	)
	return i, err
}
