// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_billing_providers.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createExternalProvider = `-- name: CreateExternalProvider :one
INSERT INTO control_plane.external_billing_providers
  (name, base_url, auth_config_json, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy)
VALUES
  ($1, $2, COALESCE($3, '{}'::jsonb), $4,
   COALESCE($5, 1000), $6,
   COALESCE($7, 'fail_open'))
RETURNING id, name, base_url, auth_config_json, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status,
          created_at, updated_at
`

type CreateExternalProviderParams struct {
	Name              string
	BaseUrl           string
	AuthConfigJson    interface{}
	Mode              string
	CacheTtlMs        interface{}
	SyncCallTimeoutMs *int32
	FailurePolicy     interface{}
}

// Insert a provider; nil cache_ttl_ms/failure_policy apply the schema defaults (1000 / fail_open); a nil
// auth_config_json defaults to an empty object.
func (q *Queries) CreateExternalProvider(ctx context.Context, arg CreateExternalProviderParams) (ControlPlaneExternalBillingProvider, error) {
	row := q.db.QueryRow(ctx, createExternalProvider,
		arg.Name,
		arg.BaseUrl,
		arg.AuthConfigJson,
		arg.Mode,
		arg.CacheTtlMs,
		arg.SyncCallTimeoutMs,
		arg.FailurePolicy,
	)
	var i ControlPlaneExternalBillingProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthConfigJson,
		&i.Mode,
		&i.CacheTtlMs,
		&i.SyncCallTimeoutMs,
		&i.FailurePolicy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExternalProvider = `-- name: DeleteExternalProvider :execrows
DELETE FROM control_plane.external_billing_providers WHERE id = $1
`

// Delete a provider. customers.external_billing_provider_id references it ON DELETE SET NULL, so deleting a
// provider in use simply unassigns it from its customers.
func (q *Queries) DeleteExternalProvider(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExternalProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExternalProvider = `-- name: GetExternalProvider :one
SELECT id, name, base_url, auth_config_json, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status,
       created_at, updated_at
FROM control_plane.external_billing_providers
WHERE id = $1
`

// One provider by id, for the connectivity test to load its config. not_found if absent.
func (q *Queries) GetExternalProvider(ctx context.Context, id uuid.UUID) (ControlPlaneExternalBillingProvider, error) {
	row := q.db.QueryRow(ctx, getExternalProvider, id)
	var i ControlPlaneExternalBillingProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthConfigJson,
		&i.Mode,
		&i.CacheTtlMs,
		&i.SyncCallTimeoutMs,
		&i.FailurePolicy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExternalProviders = `-- name: ListExternalProviders :many
SELECT id, name, base_url, auth_config_json, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status,
       created_at, updated_at
FROM control_plane.external_billing_providers
ORDER BY name
`

// Every external billing provider, ordered by name (§6.10). auth_config_json is returned raw; the handler
// masks it before it reaches a client.
func (q *Queries) ListExternalProviders(ctx context.Context) ([]ControlPlaneExternalBillingProvider, error) {
	rows, err := q.db.Query(ctx, listExternalProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneExternalBillingProvider{}
	for rows.Next() {
		var i ControlPlaneExternalBillingProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.AuthConfigJson,
			&i.Mode,
			&i.CacheTtlMs,
			&i.SyncCallTimeoutMs,
			&i.FailurePolicy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExternalProvider = `-- name: UpdateExternalProvider :one
UPDATE control_plane.external_billing_providers SET
    name                 = COALESCE($1, name),
    base_url             = COALESCE($2, base_url),
    auth_config_json     = COALESCE($3, auth_config_json),
    mode                 = COALESCE($4, mode),
    cache_ttl_ms         = COALESCE($5, cache_ttl_ms),
    sync_call_timeout_ms = COALESCE($6, sync_call_timeout_ms),
    failure_policy       = COALESCE($7, failure_policy),
    status               = COALESCE($8, status),
    updated_at           = now()
WHERE id = $9
RETURNING id, name, base_url, auth_config_json, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status,
          created_at, updated_at
`

type UpdateExternalProviderParams struct {
	Name              *string
	BaseUrl           *string
	AuthConfigJson    []byte
	Mode              *string
	CacheTtlMs        *int32
	SyncCallTimeoutMs *int32
	FailurePolicy     *string
	Status            *string
	ID                uuid.UUID
}

// Partial update: a NULL argument leaves its column unchanged (COALESCE). sync_call_timeout_ms cannot be
// cleared back to NULL via COALESCE (a documented follow-up).
func (q *Queries) UpdateExternalProvider(ctx context.Context, arg UpdateExternalProviderParams) (ControlPlaneExternalBillingProvider, error) {
	row := q.db.QueryRow(ctx, updateExternalProvider,
		arg.Name,
		arg.BaseUrl,
		arg.AuthConfigJson,
		arg.Mode,
		arg.CacheTtlMs,
		arg.SyncCallTimeoutMs,
		arg.FailurePolicy,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneExternalBillingProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthConfigJson,
		&i.Mode,
		&i.CacheTtlMs,
		&i.SyncCallTimeoutMs,
		&i.FailurePolicy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
