// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_billing_providers.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createExternalProvider = `-- name: CreateExternalProvider :one
INSERT INTO control_plane.external_billing_providers
  (name, base_url, auth_config_sealed, auth_config_kms_key_ref, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy)
VALUES
  ($1, $2, $3, $4, $5,
   COALESCE($6, 1000), $7,
   COALESCE($8, 'fail_open'))
RETURNING id, name, base_url, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status, created_at, updated_at, auth_config_sealed, auth_config_kms_key_ref
`

type CreateExternalProviderParams struct {
	Name                string
	BaseUrl             string
	AuthConfigSealed    []byte
	AuthConfigKmsKeyRef string
	Mode                string
	CacheTtlMs          interface{}
	SyncCallTimeoutMs   *int32
	FailurePolicy       interface{}
}

// Insert a provider; nil cache_ttl_ms/failure_policy apply the schema defaults (1000 / fail_open). The
// sealed credentials are NOT optional: the handler seals '{}' when none are given, because the sealed
// form of an empty document is not a constant the DDL could default to.
func (q *Queries) CreateExternalProvider(ctx context.Context, arg CreateExternalProviderParams) (ControlPlaneExternalBillingProvider, error) {
	row := q.db.QueryRow(ctx, createExternalProvider,
		arg.Name,
		arg.BaseUrl,
		arg.AuthConfigSealed,
		arg.AuthConfigKmsKeyRef,
		arg.Mode,
		arg.CacheTtlMs,
		arg.SyncCallTimeoutMs,
		arg.FailurePolicy,
	)
	var i ControlPlaneExternalBillingProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Mode,
		&i.CacheTtlMs,
		&i.SyncCallTimeoutMs,
		&i.FailurePolicy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthConfigSealed,
		&i.AuthConfigKmsKeyRef,
	)
	return i, err
}

const deleteExternalProvider = `-- name: DeleteExternalProvider :execrows
DELETE FROM control_plane.external_billing_providers WHERE id = $1
`

// Delete a provider. customers.external_billing_provider_id references it ON DELETE SET NULL, so deleting a
// provider in use simply unassigns it from its customers.
func (q *Queries) DeleteExternalProvider(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExternalProvider, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExternalProvider = `-- name: GetExternalProvider :one
SELECT id, name, base_url, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status, created_at, updated_at, auth_config_sealed, auth_config_kms_key_ref FROM control_plane.external_billing_providers
WHERE id = $1
`

// One provider by id, for the connectivity test to load its config. not_found if absent.
func (q *Queries) GetExternalProvider(ctx context.Context, id uuid.UUID) (ControlPlaneExternalBillingProvider, error) {
	row := q.db.QueryRow(ctx, getExternalProvider, id)
	var i ControlPlaneExternalBillingProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Mode,
		&i.CacheTtlMs,
		&i.SyncCallTimeoutMs,
		&i.FailurePolicy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthConfigSealed,
		&i.AuthConfigKmsKeyRef,
	)
	return i, err
}

const listExternalProviders = `-- name: ListExternalProviders :many
SELECT id, name, base_url, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status, created_at, updated_at, auth_config_sealed, auth_config_kms_key_ref FROM control_plane.external_billing_providers
ORDER BY name
`

// Every external billing provider, ordered by name (§6.10). auth_config_sealed is returned as stored — sealed
// (ADR-0016); the handler never unseals it, it returns a constant mask.
func (q *Queries) ListExternalProviders(ctx context.Context) ([]ControlPlaneExternalBillingProvider, error) {
	rows, err := q.db.Query(ctx, listExternalProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneExternalBillingProvider{}
	for rows.Next() {
		var i ControlPlaneExternalBillingProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.Mode,
			&i.CacheTtlMs,
			&i.SyncCallTimeoutMs,
			&i.FailurePolicy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthConfigSealed,
			&i.AuthConfigKmsKeyRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExternalProvider = `-- name: UpdateExternalProvider :one
UPDATE control_plane.external_billing_providers SET
    name                 = COALESCE($1, name),
    base_url             = COALESCE($2, base_url),
    auth_config_sealed   = COALESCE($3, auth_config_sealed),
    auth_config_kms_key_ref = COALESCE($4, auth_config_kms_key_ref),
    mode                 = COALESCE($5, mode),
    cache_ttl_ms         = COALESCE($6, cache_ttl_ms),
    sync_call_timeout_ms = COALESCE($7, sync_call_timeout_ms),
    failure_policy       = COALESCE($8, failure_policy),
    status               = COALESCE($9, status),
    updated_at           = now()
WHERE id = $10
RETURNING id, name, base_url, mode, cache_ttl_ms, sync_call_timeout_ms, failure_policy, status, created_at, updated_at, auth_config_sealed, auth_config_kms_key_ref
`

type UpdateExternalProviderParams struct {
	Name                *string
	BaseUrl             *string
	AuthConfigSealed    []byte
	AuthConfigKmsKeyRef *string
	Mode                *string
	CacheTtlMs          *int32
	SyncCallTimeoutMs   *int32
	FailurePolicy       *string
	Status              *string
	ID                  uuid.UUID
}

// Partial update: a NULL argument leaves its column unchanged (COALESCE). sync_call_timeout_ms cannot be
// cleared back to NULL via COALESCE (a documented follow-up).
func (q *Queries) UpdateExternalProvider(ctx context.Context, arg UpdateExternalProviderParams) (ControlPlaneExternalBillingProvider, error) {
	row := q.db.QueryRow(ctx, updateExternalProvider,
		arg.Name,
		arg.BaseUrl,
		arg.AuthConfigSealed,
		arg.AuthConfigKmsKeyRef,
		arg.Mode,
		arg.CacheTtlMs,
		arg.SyncCallTimeoutMs,
		arg.FailurePolicy,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneExternalBillingProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.Mode,
		&i.CacheTtlMs,
		&i.SyncCallTimeoutMs,
		&i.FailurePolicy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthConfigSealed,
		&i.AuthConfigKmsKeyRef,
	)
	return i, err
}
