// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gdpr_erase_jobs.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createGDPREraseJob = `-- name: CreateGDPREraseJob :one
INSERT INTO control_plane.gdpr_erase_jobs (subject_type, subject_id, operator)
VALUES ($1, $2, $3)
RETURNING id, subject_type, subject_id, status, attestation, operator, created_at, finished_at
`

type CreateGDPREraseJobParams struct {
	SubjectType string
	SubjectID   string
	Operator    string
}

// Queue an erasure. The job row is the durable record of the request, written before any erasure starts.
func (q *Queries) CreateGDPREraseJob(ctx context.Context, arg CreateGDPREraseJobParams) (ControlPlaneGdprEraseJob, error) {
	row := q.db.QueryRow(ctx, createGDPREraseJob, arg.SubjectType, arg.SubjectID, arg.Operator)
	var i ControlPlaneGdprEraseJob
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Status,
		&i.Attestation,
		&i.Operator,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishGDPREraseJob = `-- name: FinishGDPREraseJob :exec
UPDATE control_plane.gdpr_erase_jobs
SET status = $2, attestation = $3, finished_at = now()
WHERE id = $1
`

type FinishGDPREraseJobParams struct {
	ID          uuid.UUID
	Status      string
	Attestation *string
}

// Close a job with its outcome and attestation (the proof of execution, never erased content).
func (q *Queries) FinishGDPREraseJob(ctx context.Context, arg FinishGDPREraseJobParams) error {
	_, err := q.db.Exec(ctx, finishGDPREraseJob, arg.ID, arg.Status, arg.Attestation)
	return err
}

const getGDPREraseJob = `-- name: GetGDPREraseJob :one
SELECT id, subject_type, subject_id, status, attestation, operator, created_at, finished_at FROM control_plane.gdpr_erase_jobs WHERE id = $1
`

func (q *Queries) GetGDPREraseJob(ctx context.Context, id uuid.UUID) (ControlPlaneGdprEraseJob, error) {
	row := q.db.QueryRow(ctx, getGDPREraseJob, id)
	var i ControlPlaneGdprEraseJob
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Status,
		&i.Attestation,
		&i.Operator,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markGDPREraseJobRunning = `-- name: MarkGDPREraseJobRunning :exec
UPDATE control_plane.gdpr_erase_jobs SET status = 'running' WHERE id = $1 AND status = 'queued'
`

func (q *Queries) MarkGDPREraseJobRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markGDPREraseJobRunning, id)
	return err
}
