// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbound_numbers.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const assignInboundNumber = `-- name: AssignInboundNumber :one
UPDATE control_plane.inbound_numbers SET account_id = $1
WHERE id = $2
RETURNING id, address, number_type, country_code, mccmnc, connector_id, account_id, status, created_at, updated_at
`

type AssignInboundNumberParams struct {
	AccountID *uuid.UUID
	ID        uuid.UUID
}

// Sets account_id unconditionally (no COALESCE): a NULL clears the dedication so the number becomes
// shared (keyword-resolved), which COALESCE would wrongly read as "leave unchanged".
func (q *Queries) AssignInboundNumber(ctx context.Context, arg AssignInboundNumberParams) (ControlPlaneInboundNumber, error) {
	row := q.db.QueryRow(ctx, assignInboundNumber, arg.AccountID, arg.ID)
	var i ControlPlaneInboundNumber
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.NumberType,
		&i.CountryCode,
		&i.Mccmnc,
		&i.ConnectorID,
		&i.AccountID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInboundNumber = `-- name: CreateInboundNumber :one
INSERT INTO control_plane.inbound_numbers (
    address, number_type, country_code, mccmnc, connector_id, account_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, address, number_type, country_code, mccmnc, connector_id, account_id, status, created_at, updated_at
`

type CreateInboundNumberParams struct {
	Address     string
	NumberType  string
	CountryCode string
	Mccmnc      *string
	ConnectorID *uuid.UUID
	AccountID   *uuid.UUID
}

func (q *Queries) CreateInboundNumber(ctx context.Context, arg CreateInboundNumberParams) (ControlPlaneInboundNumber, error) {
	row := q.db.QueryRow(ctx, createInboundNumber,
		arg.Address,
		arg.NumberType,
		arg.CountryCode,
		arg.Mccmnc,
		arg.ConnectorID,
		arg.AccountID,
	)
	var i ControlPlaneInboundNumber
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.NumberType,
		&i.CountryCode,
		&i.Mccmnc,
		&i.ConnectorID,
		&i.AccountID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInboundNumber = `-- name: DeleteInboundNumber :execrows
DELETE FROM control_plane.inbound_numbers WHERE id = $1
`

func (q *Queries) DeleteInboundNumber(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboundNumber, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listInboundNumbers = `-- name: ListInboundNumbers :many
SELECT id, address, number_type, country_code, mccmnc, connector_id, account_id, status, created_at, updated_at FROM control_plane.inbound_numbers ORDER BY id
`

func (q *Queries) ListInboundNumbers(ctx context.Context) ([]ControlPlaneInboundNumber, error) {
	rows, err := q.db.Query(ctx, listInboundNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneInboundNumber{}
	for rows.Next() {
		var i ControlPlaneInboundNumber
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.NumberType,
			&i.CountryCode,
			&i.Mccmnc,
			&i.ConnectorID,
			&i.AccountID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInboundNumber = `-- name: UpdateInboundNumber :one
UPDATE control_plane.inbound_numbers SET
    number_type  = COALESCE($1, number_type),
    mccmnc       = COALESCE($2, mccmnc),
    connector_id = COALESCE($3, connector_id),
    status       = COALESCE($4, status)
WHERE id = $5
RETURNING id, address, number_type, country_code, mccmnc, connector_id, account_id, status, created_at, updated_at
`

type UpdateInboundNumberParams struct {
	NumberType  *string
	Mccmnc      *string
	ConnectorID *uuid.UUID
	Status      *string
	ID          uuid.UUID
}

func (q *Queries) UpdateInboundNumber(ctx context.Context, arg UpdateInboundNumberParams) (ControlPlaneInboundNumber, error) {
	row := q.db.QueryRow(ctx, updateInboundNumber,
		arg.NumberType,
		arg.Mccmnc,
		arg.ConnectorID,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneInboundNumber
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.NumberType,
		&i.CountryCode,
		&i.Mccmnc,
		&i.ConnectorID,
		&i.AccountID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
