// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbound_keywords.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createInboundKeyword = `-- name: CreateInboundKeyword :one
INSERT INTO control_plane.inbound_keywords (
    inbound_number_id, keyword, match_type, account_id, priority
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, inbound_number_id, keyword, match_type, account_id, priority, status, created_at, updated_at
`

type CreateInboundKeywordParams struct {
	InboundNumberID uuid.UUID
	Keyword         string
	MatchType       string
	AccountID       uuid.UUID
	Priority        int32
}

// match_type and priority are inserted non-null: the handler resolves the DDL defaults ('prefix', 0)
// before calling, so no column is ever left to a COALESCE here.
func (q *Queries) CreateInboundKeyword(ctx context.Context, arg CreateInboundKeywordParams) (ControlPlaneInboundKeyword, error) {
	row := q.db.QueryRow(ctx, createInboundKeyword,
		arg.InboundNumberID,
		arg.Keyword,
		arg.MatchType,
		arg.AccountID,
		arg.Priority,
	)
	var i ControlPlaneInboundKeyword
	err := row.Scan(
		&i.ID,
		&i.InboundNumberID,
		&i.Keyword,
		&i.MatchType,
		&i.AccountID,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInboundKeyword = `-- name: DeleteInboundKeyword :execrows
DELETE FROM control_plane.inbound_keywords
WHERE id = $1 AND inbound_number_id = $2
`

type DeleteInboundKeywordParams struct {
	ID              uuid.UUID
	InboundNumberID uuid.UUID
}

func (q *Queries) DeleteInboundKeyword(ctx context.Context, arg DeleteInboundKeywordParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboundKeyword, arg.ID, arg.InboundNumberID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllInboundKeywords = `-- name: ListAllInboundKeywords :many
SELECT id, inbound_number_id, keyword, match_type, account_id, priority, status, created_at, updated_at FROM control_plane.inbound_keywords
WHERE status = 'active'
ORDER BY inbound_number_id, priority, id
`

// Every active keyword across all shared numbers, for the MO router's in-memory snapshot (step-045).
// Ordered by number then priority then id so the snapshot evaluates keywords in the right order.
func (q *Queries) ListAllInboundKeywords(ctx context.Context) ([]ControlPlaneInboundKeyword, error) {
	rows, err := q.db.Query(ctx, listAllInboundKeywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneInboundKeyword{}
	for rows.Next() {
		var i ControlPlaneInboundKeyword
		if err := rows.Scan(
			&i.ID,
			&i.InboundNumberID,
			&i.Keyword,
			&i.MatchType,
			&i.AccountID,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboundKeywords = `-- name: ListInboundKeywords :many
SELECT id, inbound_number_id, keyword, match_type, account_id, priority, status, created_at, updated_at FROM control_plane.inbound_keywords
WHERE inbound_number_id = $1
ORDER BY priority, id
`

// Ordered by priority then id: priority drives MO evaluation (inbound_keywords_lookup_idx), and id is
// a stable tie-break so equal priorities list deterministically.
func (q *Queries) ListInboundKeywords(ctx context.Context, inboundNumberID uuid.UUID) ([]ControlPlaneInboundKeyword, error) {
	rows, err := q.db.Query(ctx, listInboundKeywords, inboundNumberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneInboundKeyword{}
	for rows.Next() {
		var i ControlPlaneInboundKeyword
		if err := rows.Scan(
			&i.ID,
			&i.InboundNumberID,
			&i.Keyword,
			&i.MatchType,
			&i.AccountID,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInboundKeyword = `-- name: UpdateInboundKeyword :one
UPDATE control_plane.inbound_keywords SET
    keyword    = COALESCE($1, keyword),
    match_type = COALESCE($2, match_type),
    account_id = COALESCE($3, account_id),
    priority   = COALESCE($4, priority),
    status     = COALESCE($5, status)
WHERE id = $6 AND inbound_number_id = $7
RETURNING id, inbound_number_id, keyword, match_type, account_id, priority, status, created_at, updated_at
`

type UpdateInboundKeywordParams struct {
	Keyword         *string
	MatchType       *string
	AccountID       *uuid.UUID
	Priority        *int32
	Status          *string
	ID              uuid.UUID
	InboundNumberID uuid.UUID
}

// Scoped by both keyword id and inbound_number_id: a keyword can only be patched within its own
// number, so a mismatched pair matches no row (reported as ErrNotFound).
func (q *Queries) UpdateInboundKeyword(ctx context.Context, arg UpdateInboundKeywordParams) (ControlPlaneInboundKeyword, error) {
	row := q.db.QueryRow(ctx, updateInboundKeyword,
		arg.Keyword,
		arg.MatchType,
		arg.AccountID,
		arg.Priority,
		arg.Status,
		arg.ID,
		arg.InboundNumberID,
	)
	var i ControlPlaneInboundKeyword
	err := row.Scan(
		&i.ID,
		&i.InboundNumberID,
		&i.Keyword,
		&i.MatchType,
		&i.AccountID,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
