// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ControlPlaneAntispamRule struct {
	ID         uuid.UUID
	RuleType   string
	Scope      string
	ScopeID    *uuid.UUID
	ConfigJson []byte
	Action     string
	Status     string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ControlPlaneBalance struct {
	OwnerType string
	OwnerID   uuid.UUID
	Direction string
	Credits   int32
	UpdatedAt pgtype.Timestamptz
}

type ControlPlaneBillingIdempotency struct {
	MessageID uuid.UUID
	EntryType string
	CreatedAt pgtype.Timestamptz
}

type ControlPlaneBillingLedger struct {
	ID           uuid.UUID
	OwnerType    string
	OwnerID      uuid.UUID
	Direction    string
	CustomerID   uuid.UUID
	AccountID    *uuid.UUID
	MessageID    *uuid.UUID
	EntryType    string
	Credits      int32
	BalanceAfter int32
	Reference    *string
	CreatedAt    pgtype.Timestamptz
}

type ControlPlaneBillingLedgerDefault struct {
	ID           uuid.UUID
	OwnerType    string
	OwnerID      uuid.UUID
	Direction    string
	CustomerID   uuid.UUID
	AccountID    *uuid.UUID
	MessageID    *uuid.UUID
	EntryType    string
	Credits      int32
	BalanceAfter int32
	Reference    *string
	CreatedAt    pgtype.Timestamptz
}

type ControlPlaneContentAccessAudit struct {
	ID         uuid.UUID
	Operator   string
	MessageID  uuid.UUID
	CustomerID *uuid.UUID
	Outcome    string
	AccessedAt pgtype.Timestamptz
}

type ControlPlaneContentKey struct {
	ID          uuid.UUID
	CustomerID  uuid.UUID
	WrappedKey  []byte
	KmsKeyRef   string
	Status      string
	CreatedAt   pgtype.Timestamptz
	RetiredAt   pgtype.Timestamptz
	DestroyedAt pgtype.Timestamptz
}

type ControlPlaneCredential struct {
	ID                 uuid.UUID
	AccountID          uuid.UUID
	Type               string
	SystemID           *string
	PasswordHash       *string
	ApiKeyHash         *string
	Status             string
	LastUsedAt         pgtype.Timestamptz
	PreviousSecretHash *string
	GraceExpiresAt     pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	RotatedAt          pgtype.Timestamptz
}

type ControlPlaneCustomer struct {
	ID                        uuid.UUID
	Name                      string
	Status                    string
	GroupID                   *uuid.UUID
	RatePlanID                *uuid.UUID
	BillingEnabled            bool
	BillingMode               *string
	OverdraftEnabled          bool
	OverdraftLimit            *int32
	BalanceScope              string
	MoBillingFloor            *int32
	ContentStorage            string
	ContentRetentionDays      *int32
	ContentKeyID              *uuid.UUID
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	CreditLimit               *int32
	CreditLimitIsHard         bool
	ExternalBillingProviderID *uuid.UUID
}

type ControlPlaneCustomerGroup struct {
	ID          uuid.UUID
	Name        string
	Description *string
	Status      string
	CreatedBy   *uuid.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ControlPlaneExactRoute struct {
	Msisdn     string
	TargetType string
	TargetID   uuid.UUID
	Source     string
	ImportedAt pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ControlPlaneExternalBillingProvider struct {
	ID                uuid.UUID
	Name              string
	BaseUrl           string
	AuthConfigJson    []byte
	Mode              string
	CacheTtlMs        int32
	SyncCallTimeoutMs *int32
	FailurePolicy     string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ControlPlaneGdprEraseJob struct {
	ID          uuid.UUID
	SubjectType string
	SubjectID   string
	Status      string
	Attestation *string
	Operator    string
	CreatedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type ControlPlaneInboundKeyword struct {
	ID              uuid.UUID
	InboundNumberID uuid.UUID
	Keyword         string
	MatchType       string
	AccountID       uuid.UUID
	Priority        int32
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ControlPlaneInboundNumber struct {
	ID          uuid.UUID
	Address     string
	NumberType  string
	CountryCode string
	Mccmnc      *string
	ConnectorID *uuid.UUID
	AccountID   *uuid.UUID
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ControlPlaneMessageExportJob struct {
	ID          uuid.UUID
	Status      string
	Format      string
	Masked      bool
	Filters     []byte
	RowCount    *int32
	ArtefactUri *string
	Error       *string
	Operator    string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
}

type ControlPlaneOptOutKeyword struct {
	ID                uuid.UUID
	CountryCode       *string
	Keyword           string
	Action            string
	MatchType         string
	AutoReplyTemplate *string
	Status            string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type ControlPlaneRateLimit struct {
	ID            uuid.UUID
	EntityType    string
	EntityID      uuid.UUID
	MaxPerSec     *int32
	MaxPerDay     *int32
	BurstCapacity *int32
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type ControlPlaneRatePlan struct {
	ID                      uuid.UUID
	Name                    string
	CreditsPerSegmentMtJson []byte
	CreditsPerSegmentMoJson []byte
	BillingMode             string
	ChargeOn                string
	Status                  string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ControlPlaneRoute struct {
	ID                   uuid.UUID
	Name                 string
	Priority             int32
	MatchAccountID       *uuid.UUID
	MatchCustomerID      *uuid.UUID
	MatchSenderPattern   *string
	MatchDestPattern     *string
	MatchContentPattern  *string
	DistributionStrategy string
	TargetConnectorID    *uuid.UUID
	FallbackRouteID      *uuid.UUID
	Status               string
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type ControlPlaneRouteTarget struct {
	RouteID     uuid.UUID
	ConnectorID uuid.UUID
	Weight      int32
	Priority    int32
}

type ControlPlaneRoutingScript struct {
	ID              uuid.UUID
	Scope           string
	ScopeID         *uuid.UUID
	Name            string
	Language        string
	SourceCode      string
	Checksum        string
	Status          string
	TimeoutMs       int32
	MaxInstructions *int64
	MaxMemoryKb     *int32
	CreatedBy       *uuid.UUID
	CreatedAt       pgtype.Timestamptz
	PublishedAt     pgtype.Timestamptz
}

type ControlPlaneSenderID struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Address    string
	Status     string
	CreatedBy  *uuid.UUID
	ApprovedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type ControlPlaneSenderIDRewriteRule struct {
	ID                  uuid.UUID
	Scope               string
	ScopeID             *uuid.UUID
	Direction           string
	MatchSenderPattern  *string
	MatchDestPattern    *string
	RewriteType         string
	RewriteTo           *string
	FallbackPoolJson    []byte
	MaxLength           *int32
	SanitizeCharsetJson []byte
	Priority            int32
	Reason              *string
	Status              string
	CreatedBy           *uuid.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type ControlPlaneSmppAccount struct {
	ID               uuid.UUID
	CustomerID       uuid.UUID
	Name             string
	Status           string
	SmppEnabled      bool
	RestEnabled      bool
	SenderIDPolicy   string
	QuerySmEnabled   bool
	CancelSmEnabled  bool
	AllowedBindTypes string
	MaxSessions      int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type ControlPlaneSmscConnector struct {
	ID                          uuid.UUID
	Name                        string
	Host                        string
	Port                        int32
	BindType                    string
	SystemID                    string
	PasswordHash                string
	VendorProfile               *string
	SystemType                  string
	InterfaceVersion            int16
	AddrTon                     int16
	AddrNpi                     int16
	AddressRange                string
	SourceAddrTon               int16
	SourceAddrNpi               int16
	DestAddrTon                 int16
	DestAddrNpi                 int16
	DataCodingDefault           *int16
	RegisteredDeliveryDefault   int16
	ReplaceIfPresentFlagDefault int16
	EsmClassDefault             int16
	PriorityFlagDefault         int16
	ValidityPeriodDefault       *string
	SmDefaultMsgID              int16
	EnquireLinkIntervalSec      int32
	EnquireLinkMaxMissed        int32
	BindTimeoutMs               int32
	ResponseTimeoutMs           int32
	WindowSize                  int32
	BindPoolSize                int32
	ThroughputLimitPerSec       *int32
	TlsEnabled                  bool
	TlsConfigJson               []byte
	PriorityTier                int32
	Status                      string
	AutoReconnectEnabled        bool
	ReconnectInitialDelayMs     int32
	ReconnectMultiplier         pgtype.Numeric
	ReconnectMaxDelayMs         int32
	ReconnectJitterPct          int32
	ReconnectMaxAttempts        int32
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

type ControlPlaneSuppression struct {
	ID        uuid.UUID
	Scope     string
	ScopeID   *uuid.UUID
	Msisdn    string
	Source    string
	Reason    *string
	CreatedAt pgtype.Timestamptz
}

type ControlPlaneUnroutedMo struct {
	ID              uuid.UUID
	ReceivedAt      pgtype.Timestamptz
	ConnectorID     *uuid.UUID
	InboundNumberID *uuid.UUID
	SourceAddr      string
	DestAddr        string
	SegmentCount    int32
	Encoding        string
	Reason          string
}

type ControlPlaneWebhook struct {
	ID              uuid.UUID
	AccountID       uuid.UUID
	EventType       string
	Url             string
	Secret          string
	RetryPolicyJson []byte
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

// STUB — canonical definition lives in the Admin Dashboard spec. Present only to satisfy created_by FKs.
type DashboardOperator struct {
	ID          uuid.UUID
	Email       string
	DisplayName *string
	Status      string
	CreatedAt   pgtype.Timestamptz
}
