// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opt_out_keywords.sql

package sqlcgen

import (
	"context"
)

const listActiveOptOutKeywords = `-- name: ListActiveOptOutKeywords :many
SELECT id, country_code, keyword, action, match_type, auto_reply_template, status, created_at, updated_at FROM control_plane.opt_out_keywords WHERE status = 'active' ORDER BY country_code, keyword
`

// Every active opt-out keyword, for the MO STOP-detection snapshot (step-063) and the pipeline
// opt-out stage. A disabled keyword must not trigger a suppression or auto-reply.
func (q *Queries) ListActiveOptOutKeywords(ctx context.Context) ([]ControlPlaneOptOutKeyword, error) {
	rows, err := q.db.Query(ctx, listActiveOptOutKeywords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneOptOutKeyword{}
	for rows.Next() {
		var i ControlPlaneOptOutKeyword
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Keyword,
			&i.Action,
			&i.MatchType,
			&i.AutoReplyTemplate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
