// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_limits.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const getRateLimit = `-- name: GetRateLimit :one
SELECT max_per_sec, max_per_day, burst_capacity
FROM control_plane.rate_limits
WHERE entity_type = $1 AND entity_id = $2
`

type GetRateLimitParams struct {
	EntityType string
	EntityID   uuid.UUID
}

type GetRateLimitRow struct {
	MaxPerSec     *int32
	MaxPerDay     *int32
	BurstCapacity *int32
}

// Throughput limits for one entity (smpp_account/connector/route). A missing row means "no explicit
// limit configured" -> the caller treats it as absent, not an error. rate_limits_uq guarantees :one.
func (q *Queries) GetRateLimit(ctx context.Context, arg GetRateLimitParams) (GetRateLimitRow, error) {
	row := q.db.QueryRow(ctx, getRateLimit, arg.EntityType, arg.EntityID)
	var i GetRateLimitRow
	err := row.Scan(&i.MaxPerSec, &i.MaxPerDay, &i.BurstCapacity)
	return i, err
}
