// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rate_plans.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createRatePlan = `-- name: CreateRatePlan :one
INSERT INTO control_plane.rate_plans
  (name, credits_per_segment_mt_json, credits_per_segment_mo_json, billing_mode, charge_on)
VALUES
  ($1, $2, $3,
   COALESCE($4, 'either'), COALESCE($5, 'submission'))
RETURNING id, name, credits_per_segment_mt_json, credits_per_segment_mo_json, billing_mode, charge_on, status,
          created_at, updated_at
`

type CreateRatePlanParams struct {
	Name                    string
	CreditsPerSegmentMtJson []byte
	CreditsPerSegmentMoJson []byte
	BillingMode             interface{}
	ChargeOn                interface{}
}

// Insert a rate plan; nil billing_mode/charge_on apply the schema defaults (either / submission).
func (q *Queries) CreateRatePlan(ctx context.Context, arg CreateRatePlanParams) (ControlPlaneRatePlan, error) {
	row := q.db.QueryRow(ctx, createRatePlan,
		arg.Name,
		arg.CreditsPerSegmentMtJson,
		arg.CreditsPerSegmentMoJson,
		arg.BillingMode,
		arg.ChargeOn,
	)
	var i ControlPlaneRatePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreditsPerSegmentMtJson,
		&i.CreditsPerSegmentMoJson,
		&i.BillingMode,
		&i.ChargeOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRatePlan = `-- name: DeleteRatePlan :execrows
DELETE FROM control_plane.rate_plans WHERE id = $1
`

// Delete a rate plan. customers.rate_plan_id references it with no ON DELETE clause (RESTRICT), so a plan
// still assigned to a customer raises a foreign-key violation the caller maps to a 409 conflict.
func (q *Queries) DeleteRatePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRatePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRatePlans = `-- name: ListRatePlans :many
SELECT id, name, credits_per_segment_mt_json, credits_per_segment_mo_json, billing_mode, charge_on, status,
       created_at, updated_at
FROM control_plane.rate_plans
ORDER BY name
`

// Every rate plan, ordered by name. Rate plans are few (per-operator pricing), so the list is unpaginated
// (the contract returns a bare array).
func (q *Queries) ListRatePlans(ctx context.Context) ([]ControlPlaneRatePlan, error) {
	rows, err := q.db.Query(ctx, listRatePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneRatePlan{}
	for rows.Next() {
		var i ControlPlaneRatePlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreditsPerSegmentMtJson,
			&i.CreditsPerSegmentMoJson,
			&i.BillingMode,
			&i.ChargeOn,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRatePlan = `-- name: UpdateRatePlan :one
UPDATE control_plane.rate_plans SET
    name                        = COALESCE($1, name),
    credits_per_segment_mt_json = COALESCE($2, credits_per_segment_mt_json),
    credits_per_segment_mo_json = COALESCE($3, credits_per_segment_mo_json),
    billing_mode                = COALESCE($4, billing_mode),
    charge_on                   = COALESCE($5, charge_on),
    status                      = COALESCE($6, status),
    updated_at                  = now()
WHERE id = $7
RETURNING id, name, credits_per_segment_mt_json, credits_per_segment_mo_json, billing_mode, charge_on, status,
          created_at, updated_at
`

type UpdateRatePlanParams struct {
	Name                    *string
	CreditsPerSegmentMtJson []byte
	CreditsPerSegmentMoJson []byte
	BillingMode             *string
	ChargeOn                *string
	Status                  *string
	ID                      uuid.UUID
}

// Partial update: a NULL argument leaves its column unchanged (COALESCE).
func (q *Queries) UpdateRatePlan(ctx context.Context, arg UpdateRatePlanParams) (ControlPlaneRatePlan, error) {
	row := q.db.QueryRow(ctx, updateRatePlan,
		arg.Name,
		arg.CreditsPerSegmentMtJson,
		arg.CreditsPerSegmentMoJson,
		arg.BillingMode,
		arg.ChargeOn,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneRatePlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreditsPerSegmentMtJson,
		&i.CreditsPerSegmentMoJson,
		&i.BillingMode,
		&i.ChargeOn,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
