// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO control_plane.routes (
    name, priority, match_account_id, match_customer_id, match_sender_pattern,
    match_dest_pattern, match_content_pattern, distribution_strategy,
    target_connector_id, fallback_route_id
) VALUES (
    $1,
    COALESCE($2::int, 100),
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, name, priority, match_account_id, match_customer_id, match_sender_pattern, match_dest_pattern, match_content_pattern, distribution_strategy, target_connector_id, fallback_route_id, status, created_at, updated_at
`

type CreateRouteParams struct {
	Name                 string
	Priority             *int32
	MatchAccountID       *uuid.UUID
	MatchCustomerID      *uuid.UUID
	MatchSenderPattern   *string
	MatchDestPattern     *string
	MatchContentPattern  *string
	DistributionStrategy string
	TargetConnectorID    *uuid.UUID
	FallbackRouteID      *uuid.UUID
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (ControlPlaneRoute, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Name,
		arg.Priority,
		arg.MatchAccountID,
		arg.MatchCustomerID,
		arg.MatchSenderPattern,
		arg.MatchDestPattern,
		arg.MatchContentPattern,
		arg.DistributionStrategy,
		arg.TargetConnectorID,
		arg.FallbackRouteID,
	)
	var i ControlPlaneRoute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.MatchAccountID,
		&i.MatchCustomerID,
		&i.MatchSenderPattern,
		&i.MatchDestPattern,
		&i.MatchContentPattern,
		&i.DistributionStrategy,
		&i.TargetConnectorID,
		&i.FallbackRouteID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :execrows
DELETE FROM control_plane.routes WHERE id = $1
`

func (q *Queries) DeleteRoute(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRouteTargets = `-- name: DeleteRouteTargets :exec
DELETE FROM control_plane.route_targets WHERE route_id = $1
`

func (q *Queries) DeleteRouteTargets(ctx context.Context, routeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRouteTargets, routeID)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, name, priority, match_account_id, match_customer_id, match_sender_pattern, match_dest_pattern, match_content_pattern, distribution_strategy, target_connector_id, fallback_route_id, status, created_at, updated_at FROM control_plane.routes WHERE id = $1
`

func (q *Queries) GetRoute(ctx context.Context, id uuid.UUID) (ControlPlaneRoute, error) {
	row := q.db.QueryRow(ctx, getRoute, id)
	var i ControlPlaneRoute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.MatchAccountID,
		&i.MatchCustomerID,
		&i.MatchSenderPattern,
		&i.MatchDestPattern,
		&i.MatchContentPattern,
		&i.DistributionStrategy,
		&i.TargetConnectorID,
		&i.FallbackRouteID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRouteTarget = `-- name: InsertRouteTarget :exec
INSERT INTO control_plane.route_targets (route_id, connector_id, weight, priority)
VALUES ($1, $2, COALESCE($3::int, 1), COALESCE($4::int, 0))
`

type InsertRouteTargetParams struct {
	RouteID     uuid.UUID
	ConnectorID uuid.UUID
	Weight      *int32
	Priority    *int32
}

func (q *Queries) InsertRouteTarget(ctx context.Context, arg InsertRouteTargetParams) error {
	_, err := q.db.Exec(ctx, insertRouteTarget,
		arg.RouteID,
		arg.ConnectorID,
		arg.Weight,
		arg.Priority,
	)
	return err
}

const listRouteTargets = `-- name: ListRouteTargets :many
SELECT route_id, connector_id, weight, priority FROM control_plane.route_targets WHERE route_id = $1 ORDER BY priority, connector_id
`

func (q *Queries) ListRouteTargets(ctx context.Context, routeID uuid.UUID) ([]ControlPlaneRouteTarget, error) {
	rows, err := q.db.Query(ctx, listRouteTargets, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneRouteTarget{}
	for rows.Next() {
		var i ControlPlaneRouteTarget
		if err := rows.Scan(
			&i.RouteID,
			&i.ConnectorID,
			&i.Weight,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutes = `-- name: ListRoutes :many
SELECT id, name, priority, match_account_id, match_customer_id, match_sender_pattern, match_dest_pattern, match_content_pattern, distribution_strategy, target_connector_id, fallback_route_id, status, created_at, updated_at FROM control_plane.routes ORDER BY priority, id
`

// Ordered by priority (lower first), the evaluation order of the router.
func (q *Queries) ListRoutes(ctx context.Context) ([]ControlPlaneRoute, error) {
	rows, err := q.db.Query(ctx, listRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneRoute{}
	for rows.Next() {
		var i ControlPlaneRoute
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.MatchAccountID,
			&i.MatchCustomerID,
			&i.MatchSenderPattern,
			&i.MatchDestPattern,
			&i.MatchContentPattern,
			&i.DistributionStrategy,
			&i.TargetConnectorID,
			&i.FallbackRouteID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE control_plane.routes SET
    name                  = COALESCE($1, name),
    priority              = COALESCE($2, priority),
    match_account_id      = COALESCE($3, match_account_id),
    match_customer_id     = COALESCE($4, match_customer_id),
    match_sender_pattern  = COALESCE($5, match_sender_pattern),
    match_dest_pattern    = COALESCE($6, match_dest_pattern),
    match_content_pattern = COALESCE($7, match_content_pattern),
    distribution_strategy = COALESCE($8, distribution_strategy),
    target_connector_id   = COALESCE($9, target_connector_id),
    fallback_route_id     = COALESCE($10, fallback_route_id),
    status                = COALESCE($11, status)
WHERE id = $12
RETURNING id, name, priority, match_account_id, match_customer_id, match_sender_pattern, match_dest_pattern, match_content_pattern, distribution_strategy, target_connector_id, fallback_route_id, status, created_at, updated_at
`

type UpdateRouteParams struct {
	Name                 *string
	Priority             *int32
	MatchAccountID       *uuid.UUID
	MatchCustomerID      *uuid.UUID
	MatchSenderPattern   *string
	MatchDestPattern     *string
	MatchContentPattern  *string
	DistributionStrategy *string
	TargetConnectorID    *uuid.UUID
	FallbackRouteID      *uuid.UUID
	Status               *string
	ID                   uuid.UUID
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (ControlPlaneRoute, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.Name,
		arg.Priority,
		arg.MatchAccountID,
		arg.MatchCustomerID,
		arg.MatchSenderPattern,
		arg.MatchDestPattern,
		arg.MatchContentPattern,
		arg.DistributionStrategy,
		arg.TargetConnectorID,
		arg.FallbackRouteID,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneRoute
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.MatchAccountID,
		&i.MatchCustomerID,
		&i.MatchSenderPattern,
		&i.MatchDestPattern,
		&i.MatchContentPattern,
		&i.DistributionStrategy,
		&i.TargetConnectorID,
		&i.FallbackRouteID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
