// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routing_scripts.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createRoutingScript = `-- name: CreateRoutingScript :one
INSERT INTO control_plane.routing_scripts
    (scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by)
VALUES ($1, $2, $3, $4, $5, $6, 'draft', $7,
        $8, $9, $10)
RETURNING id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
`

type CreateRoutingScriptParams struct {
	Scope           string
	ScopeID         *uuid.UUID
	Name            string
	Language        string
	SourceCode      string
	Checksum        string
	TimeoutMs       int32
	MaxInstructions *int64
	MaxMemoryKb     *int32
	CreatedBy       *uuid.UUID
}

// Create a routing script. It always starts as a draft (publish is a separate transactional step, so
// creation never contends the one-active-per-scope index). checksum is computed by the caller.
func (q *Queries) CreateRoutingScript(ctx context.Context, arg CreateRoutingScriptParams) (ControlPlaneRoutingScript, error) {
	row := q.db.QueryRow(ctx, createRoutingScript,
		arg.Scope,
		arg.ScopeID,
		arg.Name,
		arg.Language,
		arg.SourceCode,
		arg.Checksum,
		arg.TimeoutMs,
		arg.MaxInstructions,
		arg.MaxMemoryKb,
		arg.CreatedBy,
	)
	var i ControlPlaneRoutingScript
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.Checksum,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxInstructions,
		&i.MaxMemoryKb,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const deleteRoutingScript = `-- name: DeleteRoutingScript :execrows
DELETE FROM control_plane.routing_scripts WHERE id = $1
`

func (q *Queries) DeleteRoutingScript(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoutingScript, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const demoteActiveRoutingScript = `-- name: DemoteActiveRoutingScript :execrows
UPDATE control_plane.routing_scripts SET status = 'disabled'
WHERE scope = $1 AND scope_id IS NOT DISTINCT FROM $2 AND status = 'active'
`

type DemoteActiveRoutingScriptParams struct {
	Scope   string
	ScopeID *uuid.UUID
}

// Disable the current active script for a scope, so a new one can be promoted without violating the
// one-active-per-scope unique index. Run inside the publish transaction, before PromoteRoutingScript.
func (q *Queries) DemoteActiveRoutingScript(ctx context.Context, arg DemoteActiveRoutingScriptParams) (int64, error) {
	result, err := q.db.Exec(ctx, demoteActiveRoutingScript, arg.Scope, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveRoutingScript = `-- name: GetActiveRoutingScript :one
SELECT id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
FROM control_plane.routing_scripts
WHERE scope = $1 AND scope_id IS NOT DISTINCT FROM $2 AND status = 'active'
`

type GetActiveRoutingScriptParams struct {
	Scope   string
	ScopeID *uuid.UUID
}

// The single active script for a scope, if any. NULLS NOT DISTINCT matching so the platform scope
// (scope_id NULL) resolves. Used by the runtime's scope resolution (step-110).
func (q *Queries) GetActiveRoutingScript(ctx context.Context, arg GetActiveRoutingScriptParams) (ControlPlaneRoutingScript, error) {
	row := q.db.QueryRow(ctx, getActiveRoutingScript, arg.Scope, arg.ScopeID)
	var i ControlPlaneRoutingScript
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.Checksum,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxInstructions,
		&i.MaxMemoryKb,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const getRoutingScript = `-- name: GetRoutingScript :one
SELECT id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
FROM control_plane.routing_scripts
WHERE id = $1
`

func (q *Queries) GetRoutingScript(ctx context.Context, id uuid.UUID) (ControlPlaneRoutingScript, error) {
	row := q.db.QueryRow(ctx, getRoutingScript, id)
	var i ControlPlaneRoutingScript
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.Checksum,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxInstructions,
		&i.MaxMemoryKb,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listActiveRoutingScripts = `-- name: ListActiveRoutingScripts :many
SELECT id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
FROM control_plane.routing_scripts
WHERE status = 'active'
ORDER BY scope, scope_id
`

// Every active script across all scopes, to build the router's immutable script snapshot (step-110).
func (q *Queries) ListActiveRoutingScripts(ctx context.Context) ([]ControlPlaneRoutingScript, error) {
	rows, err := q.db.Query(ctx, listActiveRoutingScripts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneRoutingScript{}
	for rows.Next() {
		var i ControlPlaneRoutingScript
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Name,
			&i.Language,
			&i.SourceCode,
			&i.Checksum,
			&i.Status,
			&i.TimeoutMs,
			&i.MaxInstructions,
			&i.MaxMemoryKb,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingScriptVersions = `-- name: ListRoutingScriptVersions :many
SELECT id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
FROM control_plane.routing_scripts
WHERE scope = $1 AND scope_id IS NOT DISTINCT FROM $2
ORDER BY created_at DESC, id DESC
`

type ListRoutingScriptVersionsParams struct {
	Scope   string
	ScopeID *uuid.UUID
}

// Every version for a (scope, scope_id), newest first — the version history for one target.
func (q *Queries) ListRoutingScriptVersions(ctx context.Context, arg ListRoutingScriptVersionsParams) ([]ControlPlaneRoutingScript, error) {
	rows, err := q.db.Query(ctx, listRoutingScriptVersions, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneRoutingScript{}
	for rows.Next() {
		var i ControlPlaneRoutingScript
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Name,
			&i.Language,
			&i.SourceCode,
			&i.Checksum,
			&i.Status,
			&i.TimeoutMs,
			&i.MaxInstructions,
			&i.MaxMemoryKb,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutingScripts = `-- name: ListRoutingScripts :many
SELECT id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
FROM control_plane.routing_scripts
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListRoutingScriptsParams struct {
	After uuid.UUID
	Lim   int32
}

// A page of all routing scripts, keyset-paginated by id.
func (q *Queries) ListRoutingScripts(ctx context.Context, arg ListRoutingScriptsParams) ([]ControlPlaneRoutingScript, error) {
	rows, err := q.db.Query(ctx, listRoutingScripts, arg.After, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneRoutingScript{}
	for rows.Next() {
		var i ControlPlaneRoutingScript
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Name,
			&i.Language,
			&i.SourceCode,
			&i.Checksum,
			&i.Status,
			&i.TimeoutMs,
			&i.MaxInstructions,
			&i.MaxMemoryKb,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteRoutingScript = `-- name: PromoteRoutingScript :one
UPDATE control_plane.routing_scripts SET status = 'active', published_at = now()
WHERE id = $1
RETURNING id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
`

// Promote a script to active and stamp published_at. Paired with DemoteActiveRoutingScript in the
// publish transaction.
func (q *Queries) PromoteRoutingScript(ctx context.Context, id uuid.UUID) (ControlPlaneRoutingScript, error) {
	row := q.db.QueryRow(ctx, promoteRoutingScript, id)
	var i ControlPlaneRoutingScript
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.Checksum,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxInstructions,
		&i.MaxMemoryKb,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const updateRoutingScript = `-- name: UpdateRoutingScript :one
UPDATE control_plane.routing_scripts SET
    name = $1, language = $2, source_code = $3, checksum = $4,
    timeout_ms = $5, max_instructions = $6, max_memory_kb = $7
WHERE id = $8
RETURNING id, scope, scope_id, name, language, source_code, checksum, status, timeout_ms, max_instructions, max_memory_kb, created_by, created_at, published_at
`

type UpdateRoutingScriptParams struct {
	Name            string
	Language        string
	SourceCode      string
	Checksum        string
	TimeoutMs       int32
	MaxInstructions *int64
	MaxMemoryKb     *int32
	ID              uuid.UUID
}

// Update a script's editable fields (draft edits). checksum is recomputed by the caller from the new
// source. Status transitions go through the dedicated publish path, not here.
func (q *Queries) UpdateRoutingScript(ctx context.Context, arg UpdateRoutingScriptParams) (ControlPlaneRoutingScript, error) {
	row := q.db.QueryRow(ctx, updateRoutingScript,
		arg.Name,
		arg.Language,
		arg.SourceCode,
		arg.Checksum,
		arg.TimeoutMs,
		arg.MaxInstructions,
		arg.MaxMemoryKb,
		arg.ID,
	)
	var i ControlPlaneRoutingScript
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Name,
		&i.Language,
		&i.SourceCode,
		&i.Checksum,
		&i.Status,
		&i.TimeoutMs,
		&i.MaxInstructions,
		&i.MaxMemoryKb,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
