// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sender_rewrite_rules.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSenderRewriteRule = `-- name: CreateSenderRewriteRule :one
INSERT INTO control_plane.sender_id_rewrite_rules (
    scope, scope_id, match_sender_pattern, match_dest_pattern, rewrite_type, rewrite_to,
    fallback_pool_json, max_length, sanitize_charset_json, priority, reason
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
RETURNING id, scope, scope_id, direction, match_sender_pattern, match_dest_pattern, rewrite_type, rewrite_to, fallback_pool_json, max_length, sanitize_charset_json, priority, reason, status, created_by, created_at, updated_at
`

type CreateSenderRewriteRuleParams struct {
	Scope               string
	ScopeID             *uuid.UUID
	MatchSenderPattern  *string
	MatchDestPattern    *string
	RewriteType         string
	RewriteTo           *string
	FallbackPoolJson    []byte
	MaxLength           *int32
	SanitizeCharsetJson []byte
	Priority            int32
	Reason              *string
}

func (q *Queries) CreateSenderRewriteRule(ctx context.Context, arg CreateSenderRewriteRuleParams) (ControlPlaneSenderIDRewriteRule, error) {
	row := q.db.QueryRow(ctx, createSenderRewriteRule,
		arg.Scope,
		arg.ScopeID,
		arg.MatchSenderPattern,
		arg.MatchDestPattern,
		arg.RewriteType,
		arg.RewriteTo,
		arg.FallbackPoolJson,
		arg.MaxLength,
		arg.SanitizeCharsetJson,
		arg.Priority,
		arg.Reason,
	)
	var i ControlPlaneSenderIDRewriteRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Direction,
		&i.MatchSenderPattern,
		&i.MatchDestPattern,
		&i.RewriteType,
		&i.RewriteTo,
		&i.FallbackPoolJson,
		&i.MaxLength,
		&i.SanitizeCharsetJson,
		&i.Priority,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSenderRewriteRule = `-- name: DeleteSenderRewriteRule :execrows
DELETE FROM control_plane.sender_id_rewrite_rules WHERE id = $1
`

func (q *Queries) DeleteSenderRewriteRule(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSenderRewriteRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSenderRewriteRule = `-- name: GetSenderRewriteRule :one
SELECT id, scope, scope_id, direction, match_sender_pattern, match_dest_pattern, rewrite_type, rewrite_to, fallback_pool_json, max_length, sanitize_charset_json, priority, reason, status, created_by, created_at, updated_at FROM control_plane.sender_id_rewrite_rules WHERE id = $1
`

func (q *Queries) GetSenderRewriteRule(ctx context.Context, id uuid.UUID) (ControlPlaneSenderIDRewriteRule, error) {
	row := q.db.QueryRow(ctx, getSenderRewriteRule, id)
	var i ControlPlaneSenderIDRewriteRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Direction,
		&i.MatchSenderPattern,
		&i.MatchDestPattern,
		&i.RewriteType,
		&i.RewriteTo,
		&i.FallbackPoolJson,
		&i.MaxLength,
		&i.SanitizeCharsetJson,
		&i.Priority,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSenderRewriteRules = `-- name: ListSenderRewriteRules :many
SELECT id, scope, scope_id, direction, match_sender_pattern, match_dest_pattern, rewrite_type, rewrite_to, fallback_pool_json, max_length, sanitize_charset_json, priority, reason, status, created_by, created_at, updated_at FROM control_plane.sender_id_rewrite_rules
WHERE ($1::text IS NULL OR scope = $1)
  AND ($2::uuid IS NULL OR scope_id = $2)
ORDER BY CASE scope WHEN 'connector' THEN 0 WHEN 'smpp_account' THEN 1 WHEN 'customer' THEN 2 ELSE 3 END,
         priority, id
`

type ListSenderRewriteRulesParams struct {
	Scope   *string
	ScopeID *uuid.UUID
}

// The evaluation order of connector-pool (§6.16): scope precedence first, then priority (lower
// first), then id. A sort on priority alone would let a platform rule outrank a connector rule.
func (q *Queries) ListSenderRewriteRules(ctx context.Context, arg ListSenderRewriteRulesParams) ([]ControlPlaneSenderIDRewriteRule, error) {
	rows, err := q.db.Query(ctx, listSenderRewriteRules, arg.Scope, arg.ScopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneSenderIDRewriteRule{}
	for rows.Next() {
		var i ControlPlaneSenderIDRewriteRule
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Direction,
			&i.MatchSenderPattern,
			&i.MatchDestPattern,
			&i.RewriteType,
			&i.RewriteTo,
			&i.FallbackPoolJson,
			&i.MaxLength,
			&i.SanitizeCharsetJson,
			&i.Priority,
			&i.Reason,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSenderRewriteRule = `-- name: UpdateSenderRewriteRule :one
UPDATE control_plane.sender_id_rewrite_rules SET
    match_sender_pattern  = COALESCE($1, match_sender_pattern),
    match_dest_pattern    = COALESCE($2, match_dest_pattern),
    rewrite_type          = COALESCE($3, rewrite_type),
    rewrite_to            = COALESCE($4, rewrite_to),
    fallback_pool_json    = COALESCE($5, fallback_pool_json),
    max_length            = COALESCE($6, max_length),
    sanitize_charset_json = COALESCE($7, sanitize_charset_json),
    priority              = COALESCE($8, priority),
    reason                = COALESCE($9, reason),
    status                = COALESCE($10, status),
    updated_at            = now()
WHERE id = $11
RETURNING id, scope, scope_id, direction, match_sender_pattern, match_dest_pattern, rewrite_type, rewrite_to, fallback_pool_json, max_length, sanitize_charset_json, priority, reason, status, created_by, created_at, updated_at
`

type UpdateSenderRewriteRuleParams struct {
	MatchSenderPattern  *string
	MatchDestPattern    *string
	RewriteType         *string
	RewriteTo           *string
	FallbackPoolJson    []byte
	MaxLength           *int32
	SanitizeCharsetJson []byte
	Priority            *int32
	Reason              *string
	Status              *string
	ID                  uuid.UUID
}

func (q *Queries) UpdateSenderRewriteRule(ctx context.Context, arg UpdateSenderRewriteRuleParams) (ControlPlaneSenderIDRewriteRule, error) {
	row := q.db.QueryRow(ctx, updateSenderRewriteRule,
		arg.MatchSenderPattern,
		arg.MatchDestPattern,
		arg.RewriteType,
		arg.RewriteTo,
		arg.FallbackPoolJson,
		arg.MaxLength,
		arg.SanitizeCharsetJson,
		arg.Priority,
		arg.Reason,
		arg.Status,
		arg.ID,
	)
	var i ControlPlaneSenderIDRewriteRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.ScopeID,
		&i.Direction,
		&i.MatchSenderPattern,
		&i.MatchDestPattern,
		&i.RewriteType,
		&i.RewriteTo,
		&i.FallbackPoolJson,
		&i.MaxLength,
		&i.SanitizeCharsetJson,
		&i.Priority,
		&i.Reason,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
