// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sender_ids.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSenderID = `-- name: CreateSenderID :one
INSERT INTO control_plane.sender_ids (customer_id, address, created_by)
VALUES ($1, $2, $3)
RETURNING id, customer_id, address, status, created_by, approved_at, created_at, updated_at
`

type CreateSenderIDParams struct {
	CustomerID uuid.UUID
	Address    string
	CreatedBy  *uuid.UUID
}

// The customer_id comes from the path; an unknown one violates the FK -> 422. A duplicate address
// for the customer violates sender_ids_uq -> 409.
func (q *Queries) CreateSenderID(ctx context.Context, arg CreateSenderIDParams) (ControlPlaneSenderID, error) {
	row := q.db.QueryRow(ctx, createSenderID, arg.CustomerID, arg.Address, arg.CreatedBy)
	var i ControlPlaneSenderID
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Address,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSenderID = `-- name: DeleteSenderID :execrows
DELETE FROM control_plane.sender_ids WHERE customer_id = $1 AND id = $2
`

type DeleteSenderIDParams struct {
	CustomerID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) DeleteSenderID(ctx context.Context, arg DeleteSenderIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSenderID, arg.CustomerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSenderIDsByCustomer = `-- name: ListSenderIDsByCustomer :many
SELECT id, customer_id, address, status, created_by, approved_at, created_at, updated_at FROM control_plane.sender_ids WHERE customer_id = $1 ORDER BY address
`

func (q *Queries) ListSenderIDsByCustomer(ctx context.Context, customerID uuid.UUID) ([]ControlPlaneSenderID, error) {
	rows, err := q.db.Query(ctx, listSenderIDsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneSenderID{}
	for rows.Next() {
		var i ControlPlaneSenderID
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Address,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSenderID = `-- name: UpdateSenderID :one
UPDATE control_plane.sender_ids SET status = COALESCE($1, status)
WHERE customer_id = $2 AND id = $3
RETURNING id, customer_id, address, status, created_by, approved_at, created_at, updated_at
`

type UpdateSenderIDParams struct {
	Status     *string
	CustomerID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) UpdateSenderID(ctx context.Context, arg UpdateSenderIDParams) (ControlPlaneSenderID, error) {
	row := q.db.QueryRow(ctx, updateSenderID, arg.Status, arg.CustomerID, arg.ID)
	var i ControlPlaneSenderID
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Address,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
