// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sender_ids.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSenderID = `-- name: CreateSenderID :one
INSERT INTO control_plane.sender_ids (customer_id, address, traffic_category, created_by)
VALUES ($1, $2, COALESCE($3::text, 'marketing'), $4)
RETURNING id, customer_id, address, status, created_by, approved_at, created_at, updated_at, first_used_at, traffic_category
`

type CreateSenderIDParams struct {
	CustomerID      uuid.UUID
	Address         string
	TrafficCategory *string
	CreatedBy       *uuid.UUID
}

// The customer_id comes from the path; an unknown one violates the FK -> 422. A duplicate address
// for the customer violates sender_ids_uq -> 409.
func (q *Queries) CreateSenderID(ctx context.Context, arg CreateSenderIDParams) (ControlPlaneSenderID, error) {
	row := q.db.QueryRow(ctx, createSenderID,
		arg.CustomerID,
		arg.Address,
		arg.TrafficCategory,
		arg.CreatedBy,
	)
	var i ControlPlaneSenderID
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Address,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstUsedAt,
		&i.TrafficCategory,
	)
	return i, err
}

const deleteSenderID = `-- name: DeleteSenderID :execrows
DELETE FROM control_plane.sender_ids
WHERE customer_id = $1 AND id = $2 AND first_used_at IS NULL
`

type DeleteSenderIDParams struct {
	CustomerID uuid.UUID
	ID         uuid.UUID
}

// A sender ID that has sent is never deleted (ADR-0023): zero rows is then a conflict, not a miss.
func (q *Queries) DeleteSenderID(ctx context.Context, arg DeleteSenderIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSenderID, arg.CustomerID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSenderIDRateLimit = `-- name: DeleteSenderIDRateLimit :exec
DELETE FROM control_plane.rate_limits WHERE entity_type = 'sender_id' AND entity_id = $1
`

func (q *Queries) DeleteSenderIDRateLimit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSenderIDRateLimit, id)
	return err
}

const getSenderID = `-- name: GetSenderID :one
SELECT id, customer_id, address, status, created_by, approved_at, created_at, updated_at, first_used_at, traffic_category FROM control_plane.sender_ids WHERE customer_id = $1 AND id = $2
`

type GetSenderIDParams struct {
	CustomerID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) GetSenderID(ctx context.Context, arg GetSenderIDParams) (ControlPlaneSenderID, error) {
	row := q.db.QueryRow(ctx, getSenderID, arg.CustomerID, arg.ID)
	var i ControlPlaneSenderID
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Address,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstUsedAt,
		&i.TrafficCategory,
	)
	return i, err
}

const getSenderIDWithRateLimit = `-- name: GetSenderIDWithRateLimit :one
SELECT s.id, s.customer_id, s.address, s.status, s.created_by, s.approved_at, s.created_at, s.updated_at, s.first_used_at, s.traffic_category, rl.max_per_sec AS rate_max_per_sec, rl.burst_capacity AS rate_burst_capacity
FROM control_plane.sender_ids s
LEFT JOIN control_plane.rate_limits rl ON rl.entity_type = 'sender_id' AND rl.entity_id = s.id
WHERE s.customer_id = $1 AND s.id = $2
`

type GetSenderIDWithRateLimitParams struct {
	CustomerID uuid.UUID
	ID         uuid.UUID
}

type GetSenderIDWithRateLimitRow struct {
	ControlPlaneSenderID ControlPlaneSenderID
	RateMaxPerSec        *int32
	RateBurstCapacity    *int32
}

func (q *Queries) GetSenderIDWithRateLimit(ctx context.Context, arg GetSenderIDWithRateLimitParams) (GetSenderIDWithRateLimitRow, error) {
	row := q.db.QueryRow(ctx, getSenderIDWithRateLimit, arg.CustomerID, arg.ID)
	var i GetSenderIDWithRateLimitRow
	err := row.Scan(
		&i.ControlPlaneSenderID.ID,
		&i.ControlPlaneSenderID.CustomerID,
		&i.ControlPlaneSenderID.Address,
		&i.ControlPlaneSenderID.Status,
		&i.ControlPlaneSenderID.CreatedBy,
		&i.ControlPlaneSenderID.ApprovedAt,
		&i.ControlPlaneSenderID.CreatedAt,
		&i.ControlPlaneSenderID.UpdatedAt,
		&i.ControlPlaneSenderID.FirstUsedAt,
		&i.ControlPlaneSenderID.TrafficCategory,
		&i.RateMaxPerSec,
		&i.RateBurstCapacity,
	)
	return i, err
}

const listActiveSenderIDs = `-- name: ListActiveSenderIDs :many
SELECT id, customer_id, address, status, created_by, approved_at, created_at, updated_at, first_used_at, traffic_category FROM control_plane.sender_ids WHERE status = 'active'
`

// All active sender IDs across customers, for the sender-ID authorization snapshot (step-060). Only
// 'active' rows count: a pending or disabled registration must not authorize a source address.
func (q *Queries) ListActiveSenderIDs(ctx context.Context) ([]ControlPlaneSenderID, error) {
	rows, err := q.db.Query(ctx, listActiveSenderIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneSenderID{}
	for rows.Next() {
		var i ControlPlaneSenderID
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Address,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstUsedAt,
			&i.TrafficCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSenderIDsByCustomer = `-- name: ListSenderIDsByCustomer :many
SELECT s.id, s.customer_id, s.address, s.status, s.created_by, s.approved_at, s.created_at, s.updated_at, s.first_used_at, s.traffic_category, rl.max_per_sec AS rate_max_per_sec, rl.burst_capacity AS rate_burst_capacity
FROM control_plane.sender_ids s
LEFT JOIN control_plane.rate_limits rl ON rl.entity_type = 'sender_id' AND rl.entity_id = s.id
WHERE s.customer_id = $1
  AND ($2::text IS NULL OR s.traffic_category = $2)
ORDER BY s.address
`

type ListSenderIDsByCustomerParams struct {
	CustomerID      uuid.UUID
	TrafficCategory *string
}

type ListSenderIDsByCustomerRow struct {
	ControlPlaneSenderID ControlPlaneSenderID
	RateMaxPerSec        *int32
	RateBurstCapacity    *int32
}

func (q *Queries) ListSenderIDsByCustomer(ctx context.Context, arg ListSenderIDsByCustomerParams) ([]ListSenderIDsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listSenderIDsByCustomer, arg.CustomerID, arg.TrafficCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSenderIDsByCustomerRow{}
	for rows.Next() {
		var i ListSenderIDsByCustomerRow
		if err := rows.Scan(
			&i.ControlPlaneSenderID.ID,
			&i.ControlPlaneSenderID.CustomerID,
			&i.ControlPlaneSenderID.Address,
			&i.ControlPlaneSenderID.Status,
			&i.ControlPlaneSenderID.CreatedBy,
			&i.ControlPlaneSenderID.ApprovedAt,
			&i.ControlPlaneSenderID.CreatedAt,
			&i.ControlPlaneSenderID.UpdatedAt,
			&i.ControlPlaneSenderID.FirstUsedAt,
			&i.ControlPlaneSenderID.TrafficCategory,
			&i.RateMaxPerSec,
			&i.RateBurstCapacity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSenderIDsFirstUsed = `-- name: MarkSenderIDsFirstUsed :exec
UPDATE control_plane.sender_ids s SET first_used_at = u.used_at
FROM (SELECT unnest($1::uuid[]) AS customer_id, unnest($2::text[]) AS address,
             unnest($3::timestamptz[]) AS used_at) u
WHERE s.customer_id = u.customer_id AND s.address = u.address AND s.first_used_at IS NULL
`

type MarkSenderIDsFirstUsedParams struct {
	CustomerIds []uuid.UUID
	Addresses   []string
	UsedAts     []pgtype.Timestamptz
}

func (q *Queries) MarkSenderIDsFirstUsed(ctx context.Context, arg MarkSenderIDsFirstUsedParams) error {
	_, err := q.db.Exec(ctx, markSenderIDsFirstUsed, arg.CustomerIds, arg.Addresses, arg.UsedAts)
	return err
}

const setSenderIDRateLimit = `-- name: SetSenderIDRateLimit :execrows
INSERT INTO control_plane.rate_limits (entity_type, entity_id, max_per_sec, burst_capacity)
SELECT 'sender_id', s.id, $1, $2
FROM control_plane.sender_ids s WHERE s.customer_id = $3 AND s.id = $4
ON CONFLICT (entity_type, entity_id)
DO UPDATE SET max_per_sec = EXCLUDED.max_per_sec, burst_capacity = EXCLUDED.burst_capacity
`

type SetSenderIDRateLimitParams struct {
	MaxPerSec     *int32
	BurstCapacity *int32
	CustomerID    uuid.UUID
	ID            uuid.UUID
}

// Zero rows: no such sender ID under this customer.
func (q *Queries) SetSenderIDRateLimit(ctx context.Context, arg SetSenderIDRateLimitParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSenderIDRateLimit,
		arg.MaxPerSec,
		arg.BurstCapacity,
		arg.CustomerID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSenderID = `-- name: UpdateSenderID :one
UPDATE control_plane.sender_ids SET
    status           = COALESCE($1, status),
    traffic_category = COALESCE($2, traffic_category)
WHERE customer_id = $3 AND id = $4
RETURNING id, customer_id, address, status, created_by, approved_at, created_at, updated_at, first_used_at, traffic_category
`

type UpdateSenderIDParams struct {
	Status          *string
	TrafficCategory *string
	CustomerID      uuid.UUID
	ID              uuid.UUID
}

func (q *Queries) UpdateSenderID(ctx context.Context, arg UpdateSenderIDParams) (ControlPlaneSenderID, error) {
	row := q.db.QueryRow(ctx, updateSenderID,
		arg.Status,
		arg.TrafficCategory,
		arg.CustomerID,
		arg.ID,
	)
	var i ControlPlaneSenderID
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Address,
		&i.Status,
		&i.CreatedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstUsedAt,
		&i.TrafficCategory,
	)
	return i, err
}
