// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppressions.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSuppression = `-- name: CreateSuppression :execrows
INSERT INTO control_plane.suppressions (scope, scope_id, msisdn, source, reason)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT suppressions_uq DO NOTHING
`

type CreateSuppressionParams struct {
	Scope   string
	ScopeID *uuid.UUID
	Msisdn  string
	Source  string
	Reason  *string
}

// Idempotent write (step-063): a repeated STOP for the same (scope, scope_id, msisdn) does not
// duplicate. ON CONFLICT targets suppressions_uq (NULLS NOT DISTINCT), so the platform scope
// (scope_id NULL) dedups too. Returns rows affected: 0 = already suppressed.
func (q *Queries) CreateSuppression(ctx context.Context, arg CreateSuppressionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createSuppression,
		arg.Scope,
		arg.ScopeID,
		arg.Msisdn,
		arg.Source,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSuppressionByKey = `-- name: DeleteSuppressionByKey :execrows
DELETE FROM control_plane.suppressions
WHERE scope = $1 AND scope_id IS NOT DISTINCT FROM $2 AND msisdn = $3
`

type DeleteSuppressionByKeyParams struct {
	Scope   string
	ScopeID *uuid.UUID
	Msisdn  string
}

// Remove a suppression by its natural key (step-063 unsuppress / START). scope_id compared with IS
// NOT DISTINCT FROM so the platform scope matches a NULL argument.
func (q *Queries) DeleteSuppressionByKey(ctx context.Context, arg DeleteSuppressionByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSuppressionByKey, arg.Scope, arg.ScopeID, arg.Msisdn)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isSuppressed = `-- name: IsSuppressed :one
SELECT EXISTS (
  SELECT 1 FROM control_plane.suppressions
  WHERE scope = $1
    AND scope_id IS NOT DISTINCT FROM $2
    AND msisdn = $3
) AS suppressed
`

type IsSuppressedParams struct {
	Scope   string
	ScopeID *uuid.UUID
	Msisdn  string
}

// Exact confirmation of a Bloom hit (step-061). scope_id is compared with IS NOT DISTINCT FROM so the
// platform scope (scope_id NULL) matches a NULL argument, mirroring suppressions_uq's NULLS NOT
// DISTINCT.
func (q *Queries) IsSuppressed(ctx context.Context, arg IsSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isSuppressed, arg.Scope, arg.ScopeID, arg.Msisdn)
	var suppressed bool
	err := row.Scan(&suppressed)
	return suppressed, err
}

const listSuppressions = `-- name: ListSuppressions :many
SELECT id, scope, scope_id, msisdn, source, reason, created_at FROM control_plane.suppressions
`

// Every suppression, for the opt-out Bloom snapshot (step-061): each scope's filter is seeded from
// these rows at boot. The msisdn is already E.164-normalized at write.
func (q *Queries) ListSuppressions(ctx context.Context) ([]ControlPlaneSuppression, error) {
	rows, err := q.db.Query(ctx, listSuppressions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneSuppression{}
	for rows.Next() {
		var i ControlPlaneSuppression
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.ScopeID,
			&i.Msisdn,
			&i.Source,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
