// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unrouted_mo.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUnroutedMO = `-- name: CreateUnroutedMO :one
INSERT INTO control_plane.unrouted_mo (
    received_at, connector_id, inbound_number_id, source_addr, dest_addr, segment_count, encoding, reason
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7, $8
)
RETURNING id, received_at, connector_id, inbound_number_id, source_addr, dest_addr, segment_count, encoding, reason
`

type CreateUnroutedMOParams struct {
	ReceivedAt      pgtype.Timestamptz
	ConnectorID     *uuid.UUID
	InboundNumberID *uuid.UUID
	SourceAddr      string
	DestAddr        string
	SegmentCount    int32
	Encoding        string
	Reason          string
}

// Records an MO that resolved to no account. Never stores the message body (invariant a).
func (q *Queries) CreateUnroutedMO(ctx context.Context, arg CreateUnroutedMOParams) (ControlPlaneUnroutedMo, error) {
	row := q.db.QueryRow(ctx, createUnroutedMO,
		arg.ReceivedAt,
		arg.ConnectorID,
		arg.InboundNumberID,
		arg.SourceAddr,
		arg.DestAddr,
		arg.SegmentCount,
		arg.Encoding,
		arg.Reason,
	)
	var i ControlPlaneUnroutedMo
	err := row.Scan(
		&i.ID,
		&i.ReceivedAt,
		&i.ConnectorID,
		&i.InboundNumberID,
		&i.SourceAddr,
		&i.DestAddr,
		&i.SegmentCount,
		&i.Encoding,
		&i.Reason,
	)
	return i, err
}

const listUnroutedMOAfter = `-- name: ListUnroutedMOAfter :many
SELECT id, received_at, connector_id, inbound_number_id, source_addr, dest_addr, segment_count, encoding, reason FROM control_plane.unrouted_mo
WHERE received_at < $1
   OR (received_at = $1 AND id < $2)
ORDER BY received_at DESC, id DESC
LIMIT $3
`

type ListUnroutedMOAfterParams struct {
	AfterReceivedAt pgtype.Timestamptz
	AfterID         uuid.UUID
	Lim             int32
}

// Keyset page after (received_at, id): strictly older rows, same order. Column-wise (not a row-value
// comparison) so sqlc infers each parameter's type correctly (timestamptz, then uuid).
func (q *Queries) ListUnroutedMOAfter(ctx context.Context, arg ListUnroutedMOAfterParams) ([]ControlPlaneUnroutedMo, error) {
	rows, err := q.db.Query(ctx, listUnroutedMOAfter, arg.AfterReceivedAt, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneUnroutedMo{}
	for rows.Next() {
		var i ControlPlaneUnroutedMo
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.ConnectorID,
			&i.InboundNumberID,
			&i.SourceAddr,
			&i.DestAddr,
			&i.SegmentCount,
			&i.Encoding,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnroutedMOFirst = `-- name: ListUnroutedMOFirst :many
SELECT id, received_at, connector_id, inbound_number_id, source_addr, dest_addr, segment_count, encoding, reason FROM control_plane.unrouted_mo
ORDER BY received_at DESC, id DESC
LIMIT $1
`

// First page: newest first, id breaks ties (matches unrouted_mo_page_idx).
func (q *Queries) ListUnroutedMOFirst(ctx context.Context, lim int32) ([]ControlPlaneUnroutedMo, error) {
	rows, err := q.db.Query(ctx, listUnroutedMOFirst, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneUnroutedMo{}
	for rows.Next() {
		var i ControlPlaneUnroutedMo
		if err := rows.Scan(
			&i.ID,
			&i.ReceivedAt,
			&i.ConnectorID,
			&i.InboundNumberID,
			&i.SourceAddr,
			&i.DestAddr,
			&i.SegmentCount,
			&i.Encoding,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
