// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const getWebhook = `-- name: GetWebhook :one
SELECT id, account_id, event_type, url, secret, retry_policy_json, status, created_at, updated_at FROM control_plane.webhooks
WHERE account_id = $1 AND event_type = $2
`

type GetWebhookParams struct {
	AccountID uuid.UUID
	EventType string
}

// The account's webhook for an event type (mo|dlr). One row per (account_id, event_type) — the unique
// key — so this returns at most one; no rows means the account has no webhook for that event.
func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (ControlPlaneWebhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.AccountID, arg.EventType)
	var i ControlPlaneWebhook
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EventType,
		&i.Url,
		&i.Secret,
		&i.RetryPolicyJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
