// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlcgen

import (
	"context"

	uuid "github.com/google/uuid"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO control_plane.webhooks (account_id, event_type, url, secret_sealed, secret_kms_key_ref, retry_policy_json)
VALUES ($1, $2, $3, $4, $5,
        COALESCE($6::jsonb, '{}'::jsonb))
RETURNING id, account_id, event_type, url, retry_policy_json, status, created_at, updated_at, secret_sealed, secret_kms_key_ref
`

type CreateWebhookParams struct {
	AccountID       uuid.UUID
	EventType       string
	Url             string
	SecretSealed    []byte
	SecretKmsKeyRef string
	RetryPolicyJson []byte
}

// status falls back to the DDL default ('active'), retry_policy_json to '{}'. A second webhook for an
// event type the account already subscribes to hits webhooks_uq and comes back as a conflict.
func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (ControlPlaneWebhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.AccountID,
		arg.EventType,
		arg.Url,
		arg.SecretSealed,
		arg.SecretKmsKeyRef,
		arg.RetryPolicyJson,
	)
	var i ControlPlaneWebhook
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EventType,
		&i.Url,
		&i.RetryPolicyJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretSealed,
		&i.SecretKmsKeyRef,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :execrows
DELETE FROM control_plane.webhooks WHERE id = $1 AND account_id = $2
`

type DeleteWebhookParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

// Deleting the configuration stops future deliveries; it never touches the events already delivered
// or parked. 0 rows means the id is unknown to this account.
func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhook, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, account_id, event_type, url, retry_policy_json, status, created_at, updated_at, secret_sealed, secret_kms_key_ref FROM control_plane.webhooks
WHERE account_id = $1 AND event_type = $2
`

type GetWebhookParams struct {
	AccountID uuid.UUID
	EventType string
}

// The account's webhook for an event type (mo|dlr). One row per (account_id, event_type) — the unique
// key — so this returns at most one; no rows means the account has no webhook for that event.
//
// Disabled rows are returned, NOT filtered out here: the two delivery paths both have to know the
// difference. A first delivery dead-letters either way, but the deferred retry runner drops a deleted
// webhook's event and parks a disabled one's — switching a webhook off is a pause, not an order to
// destroy the backlog, and a query that hid the status would take that decision away from it.
func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (ControlPlaneWebhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.AccountID, arg.EventType)
	var i ControlPlaneWebhook
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EventType,
		&i.Url,
		&i.RetryPolicyJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretSealed,
		&i.SecretKmsKeyRef,
	)
	return i, err
}

const listWebhooksByAccount = `-- name: ListWebhooksByAccount :many
SELECT id, account_id, event_type, url, retry_policy_json, status, created_at, updated_at, secret_sealed, secret_kms_key_ref FROM control_plane.webhooks
WHERE account_id = $1
ORDER BY event_type
`

// Not paginated: at most two rows per account (one per event type), bounded by webhooks_uq.
func (q *Queries) ListWebhooksByAccount(ctx context.Context, accountID uuid.UUID) ([]ControlPlaneWebhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ControlPlaneWebhook{}
	for rows.Next() {
		var i ControlPlaneWebhook
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EventType,
			&i.Url,
			&i.RetryPolicyJson,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SecretSealed,
			&i.SecretKmsKeyRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE control_plane.webhooks SET
    url                = COALESCE($1, url),
    secret_sealed      = COALESCE($2, secret_sealed),
    secret_kms_key_ref = COALESCE($3, secret_kms_key_ref),
    retry_policy_json  = COALESCE($4, retry_policy_json),
    status             = COALESCE($5, status)
WHERE id = $6 AND account_id = $7
RETURNING id, account_id, event_type, url, retry_policy_json, status, created_at, updated_at, secret_sealed, secret_kms_key_ref
`

type UpdateWebhookParams struct {
	Url             *string
	SecretSealed    []byte
	SecretKmsKeyRef *string
	RetryPolicyJson []byte
	Status          *string
	ID              uuid.UUID
	AccountID       uuid.UUID
}

// Partial update: a NULL argument leaves its column unchanged (COALESCE). event_type is absent on
// purpose — it is the identity of the subscription, not a setting. updated_at is set by the
// webhooks_touch trigger. retry_policy_json IS resettable here, unlike the nullable columns of
// debts/patch-null-ne-peut-pas-effacer-un-champ.md: an omitted field arrives as a nil RawMessage (SQL
// NULL, COALESCE keeps the column) and a supplied {} arrives as two non-nil bytes, which COALESCE takes.
//
// The two halves of the sealed secret are COALESCE'd on the SAME argument being present or absent, so a
// rotation cannot write the ciphertext while keeping the reference of the key that sealed the previous one
// — a row that opens today and stops opening at the first master-key rotation.
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (ControlPlaneWebhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.Url,
		arg.SecretSealed,
		arg.SecretKmsKeyRef,
		arg.RetryPolicyJson,
		arg.Status,
		arg.ID,
		arg.AccountID,
	)
	var i ControlPlaneWebhook
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EventType,
		&i.Url,
		&i.RetryPolicyJson,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SecretSealed,
		&i.SecretKmsKeyRef,
	)
	return i, err
}
