// Billing is the opt-in credit-accounting service (plan §6.9/§13, M9). It reserves, captures and
// releases MT credits before/after an SMSC send and records MO usage, all keyed by message_id for
// idempotency under at-least-once delivery (invariant c). Credits are integer counts, never monetary;
// balances are kept separately per direction (mt/mo) and per owner (customer or smpp_account, chosen by
// the customer's balance_scope). The enums mirror db/schema_passerelle_sms.sql (tables balances,
// billing_ledger). This file is the source of truth for the billing API; billing-svc implements it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: billing.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Billing_Reserve_FullMethodName     = "/billing.Billing/Reserve"
	Billing_Capture_FullMethodName     = "/billing.Billing/Capture"
	Billing_Release_FullMethodName     = "/billing.Billing/Release"
	Billing_GetBalances_FullMethodName = "/billing.Billing/GetBalances"
	Billing_RecordMO_FullMethodName    = "/billing.Billing/RecordMO"
)

// BillingClient is the client API for Billing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Billing is served by billing-svc (gRPC :7001, plan §1.4). Reserve/Capture/Release account MT credits
// along the send path; GetBalances reads; RecordMO decrements the separate MO counter. When billing is
// disabled for a customer the router never calls this service at all (§6.9) — the opt-in is a control
// upstream of the RPC, not a flag on it.
type BillingClient interface {
	// Reserve holds `credits` against the owner's MT balance for message_id, before the SMSC send
	// (pipeline step 8, §6.1). Idempotent: a repeat Reserve for the same message_id returns the existing
	// reservation rather than double-reserving. A denial (insufficient credit, no overdraft) sets
	// reserved=false with a machine reason.
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// Capture commits a prior reservation once the SMSC accepted the message, moving the held credits out
	// of the balance for good. Idempotent by message_id: a duplicate Capture (double delivery) is a no-op
	// that returns the same outcome. The amount committed is the one Reserve recorded — the ledger `reserve`
	// entry for message_id is the amount of record, so Capture recovers it even if the short-TTL Redis
	// reservation has lapsed (§6.9); the response returns it as credits_charged for the CDR (step-146).
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	// Release returns a prior reservation to the balance when the message failed before it was sent.
	// Idempotent by message_id.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// GetBalances returns the owner's current credit balances (one entry per direction that exists).
	GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*GetBalancesResponse, error)
	// RecordMO decrements the owner's separate MO counter for a received message (§6.9). It is advisory:
	// MO accounting never blocks MT traffic, so a hit floor is reported, not enforced, here. Idempotent by
	// message_id: the mo-dlr return path is Kafka at-least-once, so a redelivered MO must not double-count.
	RecordMO(ctx context.Context, in *RecordMORequest, opts ...grpc.CallOption) (*RecordMOResponse, error)
}

type billingClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient {
	return &billingClient{cc}
}

func (c *billingClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, Billing_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, Billing_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, Billing_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*GetBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalancesResponse)
	err := c.cc.Invoke(ctx, Billing_GetBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) RecordMO(ctx context.Context, in *RecordMORequest, opts ...grpc.CallOption) (*RecordMOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordMOResponse)
	err := c.cc.Invoke(ctx, Billing_RecordMO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServer is the server API for Billing service.
// All implementations must embed UnimplementedBillingServer
// for forward compatibility.
//
// Billing is served by billing-svc (gRPC :7001, plan §1.4). Reserve/Capture/Release account MT credits
// along the send path; GetBalances reads; RecordMO decrements the separate MO counter. When billing is
// disabled for a customer the router never calls this service at all (§6.9) — the opt-in is a control
// upstream of the RPC, not a flag on it.
type BillingServer interface {
	// Reserve holds `credits` against the owner's MT balance for message_id, before the SMSC send
	// (pipeline step 8, §6.1). Idempotent: a repeat Reserve for the same message_id returns the existing
	// reservation rather than double-reserving. A denial (insufficient credit, no overdraft) sets
	// reserved=false with a machine reason.
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// Capture commits a prior reservation once the SMSC accepted the message, moving the held credits out
	// of the balance for good. Idempotent by message_id: a duplicate Capture (double delivery) is a no-op
	// that returns the same outcome. The amount committed is the one Reserve recorded — the ledger `reserve`
	// entry for message_id is the amount of record, so Capture recovers it even if the short-TTL Redis
	// reservation has lapsed (§6.9); the response returns it as credits_charged for the CDR (step-146).
	Capture(context.Context, *CaptureRequest) (*CaptureResponse, error)
	// Release returns a prior reservation to the balance when the message failed before it was sent.
	// Idempotent by message_id.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// GetBalances returns the owner's current credit balances (one entry per direction that exists).
	GetBalances(context.Context, *GetBalancesRequest) (*GetBalancesResponse, error)
	// RecordMO decrements the owner's separate MO counter for a received message (§6.9). It is advisory:
	// MO accounting never blocks MT traffic, so a hit floor is reported, not enforced, here. Idempotent by
	// message_id: the mo-dlr return path is Kafka at-least-once, so a redelivered MO must not double-count.
	RecordMO(context.Context, *RecordMORequest) (*RecordMOResponse, error)
	mustEmbedUnimplementedBillingServer()
}

// UnimplementedBillingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServer struct{}

func (UnimplementedBillingServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedBillingServer) Capture(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedBillingServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedBillingServer) GetBalances(context.Context, *GetBalancesRequest) (*GetBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalances not implemented")
}
func (UnimplementedBillingServer) RecordMO(context.Context, *RecordMORequest) (*RecordMOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMO not implemented")
}
func (UnimplementedBillingServer) mustEmbedUnimplementedBillingServer() {}
func (UnimplementedBillingServer) testEmbeddedByValue()                 {}

// UnsafeBillingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServer will
// result in compilation errors.
type UnsafeBillingServer interface {
	mustEmbedUnimplementedBillingServer()
}

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) {
	// If the following call panics, it indicates UnimplementedBillingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Billing_ServiceDesc, srv)
}

func _Billing_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_GetBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).GetBalances(ctx, req.(*GetBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_RecordMO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).RecordMO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_RecordMO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).RecordMO(ctx, req.(*RecordMORequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Billing_ServiceDesc is the grpc.ServiceDesc for Billing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Billing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Billing",
	HandlerType: (*BillingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _Billing_Reserve_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _Billing_Capture_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Billing_Release_Handler,
		},
		{
			MethodName: "GetBalances",
			Handler:    _Billing_GetBalances_Handler,
		},
		{
			MethodName: "RecordMO",
			Handler:    _Billing_RecordMO_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
