// Billing is the opt-in credit-accounting service (plan §6.9/§13, M9). It reserves, captures and
// releases MT credits before/after an SMSC send and records MO usage, all keyed by message_id for
// idempotency under at-least-once delivery (invariant c). Credits are integer counts, never monetary;
// balances are kept separately per direction (mt/mo) and per owner (customer or smpp_account, chosen by
// the customer's balance_scope). The enums mirror db/schema_passerelle_sms.sql (tables balances,
// billing_ledger). This file is the source of truth for the billing API; billing-svc implements it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction separates MT (mobile-terminated, billed on send) from MO (mobile-originated, counted on
// receipt). Balances and the ledger are per direction (balances.direction, billing_ledger.direction).
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_DIRECTION_MT          Direction = 1
	Direction_DIRECTION_MO          Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "DIRECTION_MT",
		2: "DIRECTION_MO",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"DIRECTION_MT":          1,
		"DIRECTION_MO":          2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_billing_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

// OwnerType is who a balance belongs to, decided by the customer's balance_scope: the whole customer or
// a single smpp_account (balances.owner_type, billing_ledger.owner_type).
type OwnerType int32

const (
	OwnerType_OWNER_TYPE_UNSPECIFIED  OwnerType = 0
	OwnerType_OWNER_TYPE_CUSTOMER     OwnerType = 1
	OwnerType_OWNER_TYPE_SMPP_ACCOUNT OwnerType = 2
)

// Enum value maps for OwnerType.
var (
	OwnerType_name = map[int32]string{
		0: "OWNER_TYPE_UNSPECIFIED",
		1: "OWNER_TYPE_CUSTOMER",
		2: "OWNER_TYPE_SMPP_ACCOUNT",
	}
	OwnerType_value = map[string]int32{
		"OWNER_TYPE_UNSPECIFIED":  0,
		"OWNER_TYPE_CUSTOMER":     1,
		"OWNER_TYPE_SMPP_ACCOUNT": 2,
	}
)

func (x OwnerType) Enum() *OwnerType {
	p := new(OwnerType)
	*p = x
	return p
}

func (x OwnerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OwnerType) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_proto_enumTypes[1].Descriptor()
}

func (OwnerType) Type() protoreflect.EnumType {
	return &file_billing_proto_enumTypes[1]
}

func (x OwnerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OwnerType.Descriptor instead.
func (OwnerType) EnumDescriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

// Owner names the balance holder and carries the attribution the ledger records. owner_type + owner_id
// key the balance; customer_id and account_id mirror billing_ledger.customer_id / account_id so a
// smpp_account-scoped charge on a shared customer pool is still attributed to the originating account.
// All ids are UUIDs encoded as strings; account_id is empty when not applicable.
type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerType     OwnerType              `protobuf:"varint,1,opt,name=owner_type,json=ownerType,proto3,enum=billing.OwnerType" json:"owner_type,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Owner) GetOwnerType() OwnerType {
	if x != nil {
		return x.OwnerType
	}
	return OwnerType_OWNER_TYPE_UNSPECIFIED
}

func (x *Owner) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Owner) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Owner) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// ReserveRequest asks to hold `credits` (the message's segment count, positive) against the owner's MT
// balance. message_id is the idempotency key (invariant c).
type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Credits       int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReserveRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ReserveRequest) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

// ReserveResponse reports whether the hold succeeded. A denial (insufficient credit, no overdraft) is a
// deterministic BUSINESS outcome carried in the response, not a gRPC error — callers must distinguish it
// from a retryable transport fault. balance_after is the owner's MT balance after the reservation (or the
// unchanged current balance when denied). code is drawn from the shared platform/errors vocabulary (e.g.
// "insufficient_balance", which maps to REST 402) so the denial reason never drifts from the one `code`
// contract shared across REST / SMPP command_status / cdr.error_code; empty on success.
type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reserved      bool                   `protobuf:"varint,1,opt,name=reserved,proto3" json:"reserved,omitempty"`
	BalanceAfter  int32                  `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveResponse) GetReserved() bool {
	if x != nil {
		return x.Reserved
	}
	return false
}

func (x *ReserveResponse) GetBalanceAfter() int32 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *ReserveResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// CaptureRequest commits the reservation held for message_id. The held amount is the one Reserve
// recorded, so only the key and owner are needed.
type CaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

func (x *CaptureRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CaptureRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

// CaptureResponse confirms the commit and returns credits_charged — the reserved amount actually moved
// out of the balance, which the connector pool writes to the CDR (credits_charged, billed=true; step-146).
// It is NOT necessarily the segment count: credits per segment vary by destination and sender type
// (credits_per_segment_mt), so the caller must use this value rather than recomputing.
type CaptureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Captured       bool                   `protobuf:"varint,1,opt,name=captured,proto3" json:"captured,omitempty"`
	BalanceAfter   int32                  `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	CreditsCharged int32                  `protobuf:"varint,3,opt,name=credits_charged,json=creditsCharged,proto3" json:"credits_charged,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureResponse) GetCaptured() bool {
	if x != nil {
		return x.Captured
	}
	return false
}

func (x *CaptureResponse) GetBalanceAfter() int32 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *CaptureResponse) GetCreditsCharged() int32 {
	if x != nil {
		return x.CreditsCharged
	}
	return 0
}

// ReleaseRequest returns the reservation held for message_id to the balance.
type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ReleaseRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Released      bool                   `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	BalanceAfter  int32                  `protobuf:"varint,2,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *ReleaseResponse) GetBalanceAfter() int32 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

type GetBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Owner                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesRequest) Reset() {
	*x = GetBalancesRequest{}
	mi := &file_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesRequest) ProtoMessage() {}

func (x *GetBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesRequest.ProtoReflect.Descriptor instead.
func (*GetBalancesRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalancesRequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

// Balance is one owner balance for a direction.
type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     Direction              `protobuf:"varint,1,opt,name=direction,proto3,enum=billing.Direction" json:"direction,omitempty"`
	Credits       int32                  `protobuf:"varint,2,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{8}
}

func (x *Balance) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNSPECIFIED
}

func (x *Balance) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

type GetBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalancesResponse) Reset() {
	*x = GetBalancesResponse{}
	mi := &file_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancesResponse) ProtoMessage() {}

func (x *GetBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancesResponse.ProtoReflect.Descriptor instead.
func (*GetBalancesResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

// RecordMORequest decrements the owner's MO counter by `credits` (segments, positive) for message_id.
type RecordMORequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Credits       int32                  `protobuf:"varint,3,opt,name=credits,proto3" json:"credits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMORequest) Reset() {
	*x = RecordMORequest{}
	mi := &file_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMORequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMORequest) ProtoMessage() {}

func (x *RecordMORequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMORequest.ProtoReflect.Descriptor instead.
func (*RecordMORequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{10}
}

func (x *RecordMORequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *RecordMORequest) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *RecordMORequest) GetCredits() int32 {
	if x != nil {
		return x.Credits
	}
	return 0
}

// RecordMOResponse reports the MO counter after the decrement and whether it fell to/through the
// configured floor (a "stop + alert" signal, §6.9). It never denies: MO accounting is non-blocking.
type RecordMOResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BalanceAfter  int32                  `protobuf:"varint,1,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Floored       bool                   `protobuf:"varint,2,opt,name=floored,proto3" json:"floored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMOResponse) Reset() {
	*x = RecordMOResponse{}
	mi := &file_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMOResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMOResponse) ProtoMessage() {}

func (x *RecordMOResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMOResponse.ProtoReflect.Descriptor instead.
func (*RecordMOResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{11}
}

func (x *RecordMOResponse) GetBalanceAfter() int32 {
	if x != nil {
		return x.BalanceAfter
	}
	return 0
}

func (x *RecordMOResponse) GetFloored() bool {
	if x != nil {
		return x.Floored
	}
	return false
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\abilling\"\x95\x01\n" +
	"\x05Owner\x121\n" +
	"\n" +
	"owner_type\x18\x01 \x01(\x0e2\x12.billing.OwnerTypeR\townerType\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\"o\n" +
	"\x0eReserveRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x05owner\x18\x02 \x01(\v2\x0e.billing.OwnerR\x05owner\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\"f\n" +
	"\x0fReserveResponse\x12\x1a\n" +
	"\breserved\x18\x01 \x01(\bR\breserved\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x05R\fbalanceAfter\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"U\n" +
	"\x0eCaptureRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x05owner\x18\x02 \x01(\v2\x0e.billing.OwnerR\x05owner\"{\n" +
	"\x0fCaptureResponse\x12\x1a\n" +
	"\bcaptured\x18\x01 \x01(\bR\bcaptured\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x05R\fbalanceAfter\x12'\n" +
	"\x0fcredits_charged\x18\x03 \x01(\x05R\x0ecreditsCharged\"U\n" +
	"\x0eReleaseRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x05owner\x18\x02 \x01(\v2\x0e.billing.OwnerR\x05owner\"R\n" +
	"\x0fReleaseResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12#\n" +
	"\rbalance_after\x18\x02 \x01(\x05R\fbalanceAfter\":\n" +
	"\x12GetBalancesRequest\x12$\n" +
	"\x05owner\x18\x01 \x01(\v2\x0e.billing.OwnerR\x05owner\"U\n" +
	"\aBalance\x120\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x12.billing.DirectionR\tdirection\x12\x18\n" +
	"\acredits\x18\x02 \x01(\x05R\acredits\"C\n" +
	"\x13GetBalancesResponse\x12,\n" +
	"\bbalances\x18\x01 \x03(\v2\x10.billing.BalanceR\bbalances\"p\n" +
	"\x0fRecordMORequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12$\n" +
	"\x05owner\x18\x02 \x01(\v2\x0e.billing.OwnerR\x05owner\x12\x18\n" +
	"\acredits\x18\x03 \x01(\x05R\acredits\"Q\n" +
	"\x10RecordMOResponse\x12#\n" +
	"\rbalance_after\x18\x01 \x01(\x05R\fbalanceAfter\x12\x18\n" +
	"\afloored\x18\x02 \x01(\bR\afloored*J\n" +
	"\tDirection\x12\x19\n" +
	"\x15DIRECTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDIRECTION_MT\x10\x01\x12\x10\n" +
	"\fDIRECTION_MO\x10\x02*]\n" +
	"\tOwnerType\x12\x1a\n" +
	"\x16OWNER_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OWNER_TYPE_CUSTOMER\x10\x01\x12\x1b\n" +
	"\x17OWNER_TYPE_SMPP_ACCOUNT\x10\x022\xce\x02\n" +
	"\aBilling\x12<\n" +
	"\aReserve\x12\x17.billing.ReserveRequest\x1a\x18.billing.ReserveResponse\x12<\n" +
	"\aCapture\x12\x17.billing.CaptureRequest\x1a\x18.billing.CaptureResponse\x12<\n" +
	"\aRelease\x12\x17.billing.ReleaseRequest\x1a\x18.billing.ReleaseResponse\x12H\n" +
	"\vGetBalances\x12\x1b.billing.GetBalancesRequest\x1a\x1c.billing.GetBalancesResponse\x12?\n" +
	"\bRecordMO\x12\x18.billing.RecordMORequest\x1a\x19.billing.RecordMOResponseB=Z;github.com/martialanouman/go-gateway/internal/billing/pb;pbb\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_billing_proto_goTypes = []any{
	(Direction)(0),              // 0: billing.Direction
	(OwnerType)(0),              // 1: billing.OwnerType
	(*Owner)(nil),               // 2: billing.Owner
	(*ReserveRequest)(nil),      // 3: billing.ReserveRequest
	(*ReserveResponse)(nil),     // 4: billing.ReserveResponse
	(*CaptureRequest)(nil),      // 5: billing.CaptureRequest
	(*CaptureResponse)(nil),     // 6: billing.CaptureResponse
	(*ReleaseRequest)(nil),      // 7: billing.ReleaseRequest
	(*ReleaseResponse)(nil),     // 8: billing.ReleaseResponse
	(*GetBalancesRequest)(nil),  // 9: billing.GetBalancesRequest
	(*Balance)(nil),             // 10: billing.Balance
	(*GetBalancesResponse)(nil), // 11: billing.GetBalancesResponse
	(*RecordMORequest)(nil),     // 12: billing.RecordMORequest
	(*RecordMOResponse)(nil),    // 13: billing.RecordMOResponse
}
var file_billing_proto_depIdxs = []int32{
	1,  // 0: billing.Owner.owner_type:type_name -> billing.OwnerType
	2,  // 1: billing.ReserveRequest.owner:type_name -> billing.Owner
	2,  // 2: billing.CaptureRequest.owner:type_name -> billing.Owner
	2,  // 3: billing.ReleaseRequest.owner:type_name -> billing.Owner
	2,  // 4: billing.GetBalancesRequest.owner:type_name -> billing.Owner
	0,  // 5: billing.Balance.direction:type_name -> billing.Direction
	10, // 6: billing.GetBalancesResponse.balances:type_name -> billing.Balance
	2,  // 7: billing.RecordMORequest.owner:type_name -> billing.Owner
	3,  // 8: billing.Billing.Reserve:input_type -> billing.ReserveRequest
	5,  // 9: billing.Billing.Capture:input_type -> billing.CaptureRequest
	7,  // 10: billing.Billing.Release:input_type -> billing.ReleaseRequest
	9,  // 11: billing.Billing.GetBalances:input_type -> billing.GetBalancesRequest
	12, // 12: billing.Billing.RecordMO:input_type -> billing.RecordMORequest
	4,  // 13: billing.Billing.Reserve:output_type -> billing.ReserveResponse
	6,  // 14: billing.Billing.Capture:output_type -> billing.CaptureResponse
	8,  // 15: billing.Billing.Release:output_type -> billing.ReleaseResponse
	11, // 16: billing.Billing.GetBalances:output_type -> billing.GetBalancesResponse
	13, // 17: billing.Billing.RecordMO:output_type -> billing.RecordMOResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		EnumInfos:         file_billing_proto_enumTypes,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}
