// Billing is the opt-in credit-accounting service (plan §6.9/§13, M9). It reserves, captures and
// releases MT credits before/after an SMSC send and records MO usage, all keyed by message_id for
// idempotency under at-least-once delivery (invariant c). Credits are integer counts, never monetary;
// balances are kept separately per direction (mt/mo) and per owner (customer or smpp_account, chosen by
// the customer's balance_scope). The enums mirror db/schema_passerelle_sms.sql (tables balances,
// billing_ledger). This file is the source of truth for the billing API; billing-svc implements it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: billing.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Billing_Reserve_FullMethodName     = "/billing.Billing/Reserve"
	Billing_Capture_FullMethodName     = "/billing.Billing/Capture"
	Billing_Release_FullMethodName     = "/billing.Billing/Release"
	Billing_GetBalances_FullMethodName = "/billing.Billing/GetBalances"
	Billing_RecordMO_FullMethodName    = "/billing.Billing/RecordMO"
)

// BillingClient is the client API for Billing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Billing is served by billing-svc (gRPC :7001, plan §1.4). Reserve/Capture/Release account MT credits
// along the send path; GetBalances reads; RecordMO decrements the separate MO counter. When billing is
// disabled for a customer the router never calls this service at all (§6.9) — the opt-in is a control
// upstream of the RPC, not a flag on it.
type BillingClient interface {
	// Reserve holds `credits` against the owner's MT balance for message_id, before the SMSC send
	// (pipeline step 8, §6.1). Idempotent: a repeat Reserve for the same message_id returns the existing
	// reservation rather than double-reserving. A denial (insufficient credit, no overdraft) sets
	// reserved=false with a machine reason.
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// Capture commits a prior reservation once the SMSC accepted the message, moving the held credits out
	// of the balance for good. Idempotent by message_id: a duplicate Capture (double delivery) is a no-op
	// that returns the same outcome. The amount committed is the one Reserve recorded — the ledger `reserve`
	// entry for message_id is the amount of record, so Capture recovers it even if the short-TTL Redis
	// reservation has lapsed (§6.9); the response returns it as credits_charged for the CDR (step-146).
	Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	// Release returns a prior reservation to the balance when the message failed before it was sent.
	// Idempotent by message_id.
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
	// GetBalances returns the owner's current credit balances (one entry per direction that exists).
	GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*GetBalancesResponse, error)
	// RecordMO decrements the owner's separate MO counter for a received message (§6.9). It is advisory:
	// MO accounting never blocks MT traffic, so a hit floor is reported, not enforced, here. Idempotent by
	// message_id: the mo-dlr return path is Kafka at-least-once, so a redelivered MO must not double-count.
	RecordMO(ctx context.Context, in *RecordMORequest, opts ...grpc.CallOption) (*RecordMOResponse, error)
}

type billingClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingClient(cc grpc.ClientConnInterface) BillingClient {
	return &billingClient{cc}
}

func (c *billingClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, Billing_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) Capture(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, Billing_Capture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, Billing_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) GetBalances(ctx context.Context, in *GetBalancesRequest, opts ...grpc.CallOption) (*GetBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalancesResponse)
	err := c.cc.Invoke(ctx, Billing_GetBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingClient) RecordMO(ctx context.Context, in *RecordMORequest, opts ...grpc.CallOption) (*RecordMOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordMOResponse)
	err := c.cc.Invoke(ctx, Billing_RecordMO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServer is the server API for Billing service.
// All implementations must embed UnimplementedBillingServer
// for forward compatibility.
//
// Billing is served by billing-svc (gRPC :7001, plan §1.4). Reserve/Capture/Release account MT credits
// along the send path; GetBalances reads; RecordMO decrements the separate MO counter. When billing is
// disabled for a customer the router never calls this service at all (§6.9) — the opt-in is a control
// upstream of the RPC, not a flag on it.
type BillingServer interface {
	// Reserve holds `credits` against the owner's MT balance for message_id, before the SMSC send
	// (pipeline step 8, §6.1). Idempotent: a repeat Reserve for the same message_id returns the existing
	// reservation rather than double-reserving. A denial (insufficient credit, no overdraft) sets
	// reserved=false with a machine reason.
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// Capture commits a prior reservation once the SMSC accepted the message, moving the held credits out
	// of the balance for good. Idempotent by message_id: a duplicate Capture (double delivery) is a no-op
	// that returns the same outcome. The amount committed is the one Reserve recorded — the ledger `reserve`
	// entry for message_id is the amount of record, so Capture recovers it even if the short-TTL Redis
	// reservation has lapsed (§6.9); the response returns it as credits_charged for the CDR (step-146).
	Capture(context.Context, *CaptureRequest) (*CaptureResponse, error)
	// Release returns a prior reservation to the balance when the message failed before it was sent.
	// Idempotent by message_id.
	Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	// GetBalances returns the owner's current credit balances (one entry per direction that exists).
	GetBalances(context.Context, *GetBalancesRequest) (*GetBalancesResponse, error)
	// RecordMO decrements the owner's separate MO counter for a received message (§6.9). It is advisory:
	// MO accounting never blocks MT traffic, so a hit floor is reported, not enforced, here. Idempotent by
	// message_id: the mo-dlr return path is Kafka at-least-once, so a redelivered MO must not double-count.
	RecordMO(context.Context, *RecordMORequest) (*RecordMOResponse, error)
	mustEmbedUnimplementedBillingServer()
}

// UnimplementedBillingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServer struct{}

func (UnimplementedBillingServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedBillingServer) Capture(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capture not implemented")
}
func (UnimplementedBillingServer) Release(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedBillingServer) GetBalances(context.Context, *GetBalancesRequest) (*GetBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalances not implemented")
}
func (UnimplementedBillingServer) RecordMO(context.Context, *RecordMORequest) (*RecordMOResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMO not implemented")
}
func (UnimplementedBillingServer) mustEmbedUnimplementedBillingServer() {}
func (UnimplementedBillingServer) testEmbeddedByValue()                 {}

// UnsafeBillingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServer will
// result in compilation errors.
type UnsafeBillingServer interface {
	mustEmbedUnimplementedBillingServer()
}

func RegisterBillingServer(s grpc.ServiceRegistrar, srv BillingServer) {
	// If the following call panics, it indicates UnimplementedBillingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Billing_ServiceDesc, srv)
}

func _Billing_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_Capture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).Capture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_Capture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).Capture(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_GetBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).GetBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_GetBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).GetBalances(ctx, req.(*GetBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Billing_RecordMO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServer).RecordMO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Billing_RecordMO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServer).RecordMO(ctx, req.(*RecordMORequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Billing_ServiceDesc is the grpc.ServiceDesc for Billing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Billing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.Billing",
	HandlerType: (*BillingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _Billing_Reserve_Handler,
		},
		{
			MethodName: "Capture",
			Handler:    _Billing_Capture_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _Billing_Release_Handler,
		},
		{
			MethodName: "GetBalances",
			Handler:    _Billing_GetBalances_Handler,
		},
		{
			MethodName: "RecordMO",
			Handler:    _Billing_RecordMO_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}

const (
	ContentKeys_GetOrCreateContentKey_FullMethodName   = "/billing.ContentKeys/GetOrCreateContentKey"
	ContentKeys_RotateContentKey_FullMethodName        = "/billing.ContentKeys/RotateContentKey"
	ContentKeys_GetContentEncryptionKey_FullMethodName = "/billing.ContentKeys/GetContentEncryptionKey"
)

// ContentKeysClient is the client API for ContentKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContentKeys manages the per-customer content-encryption keys (control_plane.content_keys, §6.14, M10).
// It is hosted by billing-svc because billing-svc is the sole holder of the KMS (envelope encryption:
// a per-customer AES-256 data key seals the body, the KMS seals the data key). It is DELIBERATELY separate
// from the Billing service and NOT gated by the billing opt-in: a customer with billing disabled still
// stores content and therefore still needs a content key. Responses carry key METADATA only — never the
// plaintext data key nor the wrapped bytes; the data plane obtains usable key material through a separate
// guarded path (later M10 steps).
type ContentKeysClient interface {
	// GetOrCreateContentKey returns the customer's active content key, creating one (a fresh data key sealed
	// by the KMS) if none exists yet. Idempotent: concurrent callers converge on a single active key.
	GetOrCreateContentKey(ctx context.Context, in *GetOrCreateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error)
	// RotateContentKey makes a new active key and retires the previous one. The retired key is kept so CDRs
	// written under it stay decryptable — rotation never destroys key material (crypto-shred is separate).
	RotateContentKey(ctx context.Context, in *RotateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error)
	// GetContentEncryptionKey returns the customer's active key id AND its UNWRAPPED (plaintext) data key, so
	// the data plane can encrypt a body at CDR write without the body ever reaching billing-svc (§14). This is
	// the ONLY RPC that returns plaintext key material: it exists solely for the guarded encrypt path, rides
	// the intra-mesh mTLS, and the DEK must never be logged nor written to a CDR. Callers cache it briefly.
	GetContentEncryptionKey(ctx context.Context, in *GetContentEncryptionKeyRequest, opts ...grpc.CallOption) (*ContentEncryptionKeyResponse, error)
}

type contentKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewContentKeysClient(cc grpc.ClientConnInterface) ContentKeysClient {
	return &contentKeysClient{cc}
}

func (c *contentKeysClient) GetOrCreateContentKey(ctx context.Context, in *GetOrCreateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_GetOrCreateContentKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentKeysClient) RotateContentKey(ctx context.Context, in *RotateContentKeyRequest, opts ...grpc.CallOption) (*ContentKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_RotateContentKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentKeysClient) GetContentEncryptionKey(ctx context.Context, in *GetContentEncryptionKeyRequest, opts ...grpc.CallOption) (*ContentEncryptionKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContentEncryptionKeyResponse)
	err := c.cc.Invoke(ctx, ContentKeys_GetContentEncryptionKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentKeysServer is the server API for ContentKeys service.
// All implementations must embed UnimplementedContentKeysServer
// for forward compatibility.
//
// ContentKeys manages the per-customer content-encryption keys (control_plane.content_keys, §6.14, M10).
// It is hosted by billing-svc because billing-svc is the sole holder of the KMS (envelope encryption:
// a per-customer AES-256 data key seals the body, the KMS seals the data key). It is DELIBERATELY separate
// from the Billing service and NOT gated by the billing opt-in: a customer with billing disabled still
// stores content and therefore still needs a content key. Responses carry key METADATA only — never the
// plaintext data key nor the wrapped bytes; the data plane obtains usable key material through a separate
// guarded path (later M10 steps).
type ContentKeysServer interface {
	// GetOrCreateContentKey returns the customer's active content key, creating one (a fresh data key sealed
	// by the KMS) if none exists yet. Idempotent: concurrent callers converge on a single active key.
	GetOrCreateContentKey(context.Context, *GetOrCreateContentKeyRequest) (*ContentKeyResponse, error)
	// RotateContentKey makes a new active key and retires the previous one. The retired key is kept so CDRs
	// written under it stay decryptable — rotation never destroys key material (crypto-shred is separate).
	RotateContentKey(context.Context, *RotateContentKeyRequest) (*ContentKeyResponse, error)
	// GetContentEncryptionKey returns the customer's active key id AND its UNWRAPPED (plaintext) data key, so
	// the data plane can encrypt a body at CDR write without the body ever reaching billing-svc (§14). This is
	// the ONLY RPC that returns plaintext key material: it exists solely for the guarded encrypt path, rides
	// the intra-mesh mTLS, and the DEK must never be logged nor written to a CDR. Callers cache it briefly.
	GetContentEncryptionKey(context.Context, *GetContentEncryptionKeyRequest) (*ContentEncryptionKeyResponse, error)
	mustEmbedUnimplementedContentKeysServer()
}

// UnimplementedContentKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentKeysServer struct{}

func (UnimplementedContentKeysServer) GetOrCreateContentKey(context.Context, *GetOrCreateContentKeyRequest) (*ContentKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateContentKey not implemented")
}
func (UnimplementedContentKeysServer) RotateContentKey(context.Context, *RotateContentKeyRequest) (*ContentKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateContentKey not implemented")
}
func (UnimplementedContentKeysServer) GetContentEncryptionKey(context.Context, *GetContentEncryptionKeyRequest) (*ContentEncryptionKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContentEncryptionKey not implemented")
}
func (UnimplementedContentKeysServer) mustEmbedUnimplementedContentKeysServer() {}
func (UnimplementedContentKeysServer) testEmbeddedByValue()                     {}

// UnsafeContentKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentKeysServer will
// result in compilation errors.
type UnsafeContentKeysServer interface {
	mustEmbedUnimplementedContentKeysServer()
}

func RegisterContentKeysServer(s grpc.ServiceRegistrar, srv ContentKeysServer) {
	// If the following call panics, it indicates UnimplementedContentKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContentKeys_ServiceDesc, srv)
}

func _ContentKeys_GetOrCreateContentKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateContentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).GetOrCreateContentKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_GetOrCreateContentKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).GetOrCreateContentKey(ctx, req.(*GetOrCreateContentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentKeys_RotateContentKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateContentKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).RotateContentKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_RotateContentKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).RotateContentKey(ctx, req.(*RotateContentKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentKeys_GetContentEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentEncryptionKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentKeysServer).GetContentEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContentKeys_GetContentEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentKeysServer).GetContentEncryptionKey(ctx, req.(*GetContentEncryptionKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContentKeys_ServiceDesc is the grpc.ServiceDesc for ContentKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContentKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billing.ContentKeys",
	HandlerType: (*ContentKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrCreateContentKey",
			Handler:    _ContentKeys_GetOrCreateContentKey_Handler,
		},
		{
			MethodName: "RotateContentKey",
			Handler:    _ContentKeys_RotateContentKey_Handler,
		},
		{
			MethodName: "GetContentEncryptionKey",
			Handler:    _ContentKeys_GetContentEncryptionKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
